/* Generated by xf2c.py from xalloc_func.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

static int ret_positive_n = 0;

float *positive(const int n, const float *x);

float *positive(const int n, const float *x) {
   /* n: extent of x (dimension 1) */
   float *y = NULL;
   int n_y = 0;
   {
      int pack_n = 0;
      for (int i_fill = 0; i_fill < n; ++i_fill) if (x[i_fill] > 0) ++pack_n;
      if (y) free(y);
      y = (float*) malloc(sizeof(float) * pack_n);
      if (!y && pack_n > 0) return NULL;
      n_y = pack_n;
      for (int i_fill = 0, j_fill = 0; i_fill < n; ++i_fill) {
         if (x[i_fill] > 0) {
            y[j_fill] = x[i_fill];
            ++j_fill;
         }
      }
   }
   ret_positive_n = n_y;
   return y;
}

int main(void) {
   {
      float *arr_call_0 = positive(4, ((float[]){-10.0, 0.0, 10.0, 20.0}));
      {
         int first = 1;
         for (int i_pr = 0; i_pr < ret_positive_n; ++i_pr) {
            if (first) printf("%13.6f", arr_call_0[i_pr]);
            else printf("    %13.6f", arr_call_0[i_pr]);
            first = 0;
         }
         printf("    \n");
      }
      free(arr_call_0);
   }
   return 0;
}
