/* Generated by xf2c.py from xalloc_minmax.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"

int main(void) {
   double *prices = NULL, *rets = NULL;
   int n_prices_1 = 0, n_prices_2 = 0, n_rets_1 = 0, n_rets_2 = 0;
   if (prices) free(prices);
   prices = (double*) malloc(sizeof(double) * 6);
   if (!prices && 6 > 0) return 1;
   n_prices_1 = 3;
   n_prices_2 = 2;
   if (rets) free(rets);
   rets = (double*) malloc(sizeof(double) * 4);
   if (!rets && 4 > 0) return 1;
   n_rets_1 = 2;
   n_rets_2 = 2;
   prices[0] = 100.0;
   prices[1] = 110.0;
   prices[2] = 99.0;
   prices[n_prices_1] = 50.0;
   prices[n_prices_1 + 1] = 55.0;
   prices[n_prices_1 + 2] = 60.0;
   if (rets) free(rets);
   rets = (double*) malloc(sizeof(double) * ((((1 / 1 + 1)) * (((n_prices_2 - 1) / 1 + 1)))));
   if (!rets && ((((1 / 1 + 1)) * (((n_prices_2 - 1) / 1 + 1)))) > 0) return 1;
   n_rets_1 = (1 / 1 + 1);
   n_rets_2 = ((n_prices_2 - 1) / 1 + 1);
   for (int i2_fill = 0; i2_fill < ((n_prices_2 - 1) / 1 + 1); ++i2_fill) {
      for (int i1_fill = 0; i1_fill < (1 / 1 + 1); ++i1_fill) {
         rets[i1_fill + ((1 / 1 + 1)) * i2_fill] = prices[i1_fill + 1 + n_prices_1 * i2_fill] / prices[i1_fill + n_prices_1 * i2_fill] - 1.0e0;
      }
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "min, max returns:");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", minval_1d_double((n_rets_1 * n_rets_2), rets));
      first = 0;
      printf("%s%13.6f", first ? "" : " ", maxval_1d_double((n_rets_1 * n_rets_2), rets));
      first = 0;
      printf("\n");
   }
   free(prices);
   free(rets);
   return 0;
}
