/* Generated by xf2c.py from xalloc_string.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"

int main(void) {
   char *s = NULL;
   assign_str_alloc(&s, "abc");
   {
      int first = 1;
      printf("%s%d", first ? "" : " ", ((int) strlen(s)));
      first = 0;
      printf("\n");
   }
   assign_str_alloc(&s, "defgh");
   {
      int first = 1;
      printf("%s%d", first ? "" : " ", ((int) strlen(s)));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", ((s != NULL)) ? "T" : "F");
      first = 0;
      printf("\n");
   }
   if (s) free(s);
   s = NULL;
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", ((s != NULL)) ? "T" : "F");
      first = 0;
      printf("\n");
   }
   return 0;
}
