/* Generated by xf2c.py from xall.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   int ivec[2] = {10, 20};
   int jvec[3] = {20, 30, 40};
   {
      int first = 1;
      for (int i = 0; i < 2; ++i) {
         int all_1 = 1;
         for (int red_i_1 = 0; red_i_1 < 3; ++red_i_1) if (!(jvec[red_i_1] != ivec[i])) all_1 = 0;
         printf("%s%s", first ? "" : " ", all_1 ? "T" : "F");
         first = 0;
      }
      printf("\n");
   }
   {
      int first = 1;
      for (int i = 0; i < 2; ++i) {
         int any_1 = 0;
         for (int red_i_1 = 0; red_i_1 < 3; ++red_i_1) if (jvec[red_i_1] != ivec[i]) any_1 = 1;
         printf("%s%s", first ? "" : " ", any_1 ? "T" : "F");
         first = 0;
      }
      printf("\n");
   }
   return 0;
}
