/* Generated by xf2c.py from xalloc_multi.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   int *a = NULL, *b = NULL;
   int n_a = 0, n_b = 0;
   if (a) free(a);
   a = (int*) malloc(sizeof(int) * 2);
   if (!a && 2 > 0) return 1;
   n_a = 2;
   if (b) free(b);
   b = (int*) malloc(sizeof(int) * 3);
   if (!b && 3 > 0) return 1;
   n_b = 3;
   for (int i_fill = 0; i_fill < n_a; ++i_fill) {
      a[i_fill] = 1;
   }
   for (int i_fill = 0; i_fill < n_b; ++i_fill) {
      b[i_fill] = 2;
   }
   {
      int first = 1;
      printf("%s%d", first ? "" : " ", a[0]);
      first = 0;
      printf("%s%d", first ? "" : " ", b[0]);
      first = 0;
      printf("\n");
   }
   if (a) free(a);
   a = NULL;
   n_a = 0;
   if (b) free(b);
   b = NULL;
   n_b = 0;
   free(a);
   free(b);
   return 0;
}
