/* Generated by xf2c.py from xalloc_2d.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   float *x = NULL, *y = NULL;
   int n_x_1 = 0, n_x_2 = 0, n_y_1 = 0, n_y_2 = 0;
   if (x) free(x);
   x = (float*) malloc(sizeof(float) * 6);
   if (!x && 6 > 0) return 1;
   n_x_1 = 2;
   n_x_2 = 3;
   for (int i_fill = 0; i_fill < 6; ++i_fill) x[i_fill] = 4.5;
   {
      int first = 1;
      for (int i_pr = 0; i_pr < n_x_1 * n_x_2; ++i_pr) {
         if (first) printf("%13.6f", x[i_pr]);
         else printf("    %13.6f", x[i_pr]);
         first = 0;
      }
      printf("    \n");
   }
   if (y) free(y);
   y = (float*) malloc(sizeof(float) * n_x_1 * n_x_2);
   if (!y && (n_x_1 * n_x_2) > 0) return 1;
   n_y_1 = n_x_1;
   n_y_2 = n_x_2;
   for (int i_fill = 0; i_fill < n_x_1 * n_x_2; ++i_fill) {
      y[i_fill] = 10 * x[i_fill];
   }
   {
      int first = 1;
      for (int i_pr = 0; i_pr < n_y_1 * n_y_2; ++i_pr) {
         if (first) printf("%13.6f", y[i_pr]);
         else printf("    %13.6f", y[i_pr]);
         first = 0;
      }
      printf("    \n");
   }
   {
      int first = 1;
      printf("%s%d", first ? "" : " ", n_x_1);
      first = 0;
      printf("%s%d", first ? "" : " ", n_x_2);
      first = 0;
      printf("%s%d", first ? "" : " ", n_y_1);
      first = 0;
      printf("%s%d", first ? "" : " ", n_y_2);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%d", first ? "" : " ", 2);
      first = 0;
      printf("%s%d", first ? "" : " ", 2);
      first = 0;
      printf("\n");
   }
   free(x);
   free(y);
   return 0;
}
