/* Generated by xf2c.py from xalloc.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   float *x = NULL, *y = NULL, *z = NULL;
   int n_x = 0, n_y = 0, n_z = 0;
   if (x) free(x);
   x = (float*) malloc(sizeof(float) * 2);
   if (!x && 2 > 0) return 1;
   n_x = 2;
   x[0] = 10.0;
   x[1] = 20.0;
   {
      int first = 1;
      for (int i_pr = 0; i_pr < n_x; ++i_pr) {
         if (first) printf("%13.6f", x[i_pr]);
         else printf("    %13.6f", x[i_pr]);
         first = 0;
      }
      printf("    \n");
   }
   if (x) free(x);
   x = NULL;
   n_x = 0;
   if (x) free(x);
   x = (float*) malloc(sizeof(float) * 4);
   if (!x && 4 > 0) return 1;
   n_x = 4;
   for (int i_fill = 0; i_fill < 4; ++i_fill) x[i_fill] = 100.0;
   {
      int first = 1;
      for (int i_pr = 0; i_pr < n_x; ++i_pr) {
         if (first) printf("%13.6f", x[i_pr]);
         else printf("    %13.6f", x[i_pr]);
         first = 0;
      }
      printf("    \n");
   }
   if (y) free(y);
   y = (float*) malloc(sizeof(float) * n_x);
   if (!y && n_x > 0) return 1;
   n_y = n_x;
   for (int i_fill = 0; i_fill < n_y; ++i_fill) {
      y[i_fill] = -(1.0);
   }
   {
      int first = 1;
      for (int i_pr = 0; i_pr < n_y; ++i_pr) {
         if (first) printf("%13.6f", y[i_pr]);
         else printf("    %13.6f", y[i_pr]);
         first = 0;
      }
      printf("    \n");
   }
   if (z) free(z);
   z = (float*) malloc(sizeof(float) * n_y);
   if (!z && n_y > 0) return 1;
   n_z = n_y;
   for (int p_fill = 0; p_fill < n_y; ++p_fill) {
      z[p_fill] = 10 * y[p_fill];
   }
   {
      int first = 1;
      for (int i_pr = 0; i_pr < n_z; ++i_pr) {
         if (first) printf("%13.6f", z[i_pr]);
         else printf("    %13.6f", z[i_pr]);
         first = 0;
      }
      printf("    \n");
   }
   free(x);
   free(y);
   free(z);
   return 0;
}
