/* Generated by xf2c.py from xarray_element.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   enum { n = 3 };
   float x[3] = {10.0, 20.0, 30.0};
   int i;
   for (int p_fill = 0; p_fill < n; ++p_fill) {
      x[p_fill] = 10 * x[p_fill];
   }
   i = 1;
   while (i <= 3) {
      {
         int first = 1;
         printf("%s%d", first ? "" : " ", i);
         first = 0;
         printf("%s%13.6f", first ? "" : " ", x[i - 1]);
         first = 0;
         printf("\n");
      }
      i += 1;
   }
   {
      int first = 1;
      for (int i_pr = 0; i_pr < 3; ++i_pr) {
         if (first) printf("%13.6f", x[i_pr]);
         else printf("    %13.6f", x[i_pr]);
         first = 0;
      }
      printf("    \n");
   }
   return 0;
}
