/* Generated by xf2c.py from xarray_bounds.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

void sub(const int n, const float *x);
void sub1(const int n, const float *x);

void sub(const int n, const float *x) {
   /* n: extent of x (dimension 1) */
   int i = 1;
   while (i <= n) {
      {
         int first = 1;
         printf("%s%d", first ? "" : " ", i);
         first = 0;
         printf("%s%13.6f", first ? "" : " ", x[i - 1]);
         first = 0;
         printf("\n");
      }
      i += 1;
   }
}

void sub1(const int n, const float *x) {
   /* n: extent of x (dimension 1) */
   int i = 0;
   while (i <= n - 1) {
      {
         int first = 1;
         printf("%s%d", first ? "" : " ", i);
         first = 0;
         printf("%s%13.6f", first ? "" : " ", x[i]);
         first = 0;
         printf("\n");
      }
      i += 1;
   }
}

int main(void) {
   float *x = NULL;
   int i;
   x = (float*) malloc(sizeof(float) * 7);
   if (!x) return 1;
   i = -2;
   while (i <= 4) {
      x[i + 2] = 10.0 * i;
      {
         int first = 1;
         printf("%s%d", first ? "" : " ", i);
         first = 0;
         printf("%s%13.6f", first ? "" : " ", x[i + 2]);
         first = 0;
         printf("\n");
      }
      i += 1;
   }
   printf("\n");
   sub(7, x);
   printf("\n");
   sub1(7, x);
   free(x);
   return 0;
}
