/* Generated by xf2c.py from xarray_section.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   float x[3] = {10.0, 20.0, 30.0};
   float *y = NULL;
   y = (float*) malloc(sizeof(float) * 6);
   if (!y) return 1;
   for (int p_fill = 0; p_fill < 3; ++p_fill) {
      y[2 * p_fill] = x[p_fill];
   }
   for (int p_fill = 0; p_fill < 3; ++p_fill) {
      y[1 + 2 * p_fill] = 10 * x[p_fill];
   }
   {
      int first = 1;
      for (int i2 = 1; i2 <= 3; i2 += 1) {
         printf("%s%g", first ? "" : " ", y[2 * (i2 - 1)]);
         first = 0;
      }
      printf("\n");
   }
   {
      int first = 1;
      for (int i2 = 1; i2 <= 3; i2 += 1) {
         printf("%s%g", first ? "" : " ", y[1 + 2 * (i2 - 1)]);
         first = 0;
      }
      printf("\n");
   }
   free(y);
   return 0;
}
