/* Generated by xf2c.py from xarray_1d.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"

int main(void) {
   rng_seed(42);
   {
      int first_pr = 1;
      printf("%s%13.6f", first_pr ? "" : " ", runif());
      first_pr = 0;
      double *arr_call_1 = (double*) malloc(sizeof(double) * 3);
      if (!arr_call_1 && 3 > 0) return 1;
      fill_runif_1d(3, arr_call_1);
      for (int i_pr = 0; i_pr < 3; ++i_pr) {
         printf("%s%g", first_pr ? "" : " ", arr_call_1[i_pr]);
         first_pr = 0;
      }
      free(arr_call_1);
      printf("%s%13.6f", first_pr ? "" : " ", runif());
      first_pr = 0;
      printf("\n");
   }
   return 0;
}
