/* Generated by xf2c.py from xarray_arg.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

float sumsq(const int n, const float *x);

float sumsq(const int n, const float *x) {
   /* n: extent of x (dimension 1) */
   float y;
   {
      float red = 0.0f;
      for (int i_fill = 0; i_fill < n; ++i_fill) red += (x[i_fill] * x[i_fill]);
      y = red;
   }
   return y;
}

int main(void) {
   float x[2] = {10.0, 20.0};
   float y[2] = {30.0, 40.0};
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", ({ int n_arg_0 = 2; float *tmp_arg_0 = (float*) malloc(sizeof(float) * n_arg_0); if(!tmp_arg_0 && n_arg_0 > 0) exit(1); for(int i_arg_0 = 0; i_arg_0 < n_arg_0; ++i_arg_0) tmp_arg_0[i_arg_0] = x[i_arg_0] - y[i_arg_0]; float xf2c_ret = sumsq(n_arg_0, tmp_arg_0); free(tmp_arg_0); xf2c_ret; }));
      first = 0;
      printf("\n");
   }
   printf("%s%13.6f    \n", "", ({ int n_arg_0 = 2; float *tmp_arg_0 = (float*) malloc(sizeof(float) * n_arg_0); if(!tmp_arg_0 && n_arg_0 > 0) exit(1); for(int i_arg_0 = 0; i_arg_0 < n_arg_0; ++i_arg_0) tmp_arg_0[i_arg_0] = x[i_arg_0] - ((i_arg_0 == 0 ? (30.0) : (40.0))); float xf2c_ret = sumsq(n_arg_0, tmp_arg_0); free(tmp_arg_0); xf2c_ret; }));
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", ({ int n_arg_0 = 2; float *tmp_arg_0 = (float*) malloc(sizeof(float) * n_arg_0); if(!tmp_arg_0 && n_arg_0 > 0) exit(1); for(int i_arg_0 = 0; i_arg_0 < n_arg_0; ++i_arg_0) tmp_arg_0[i_arg_0] = x[i_arg_0] - 30.0; float xf2c_ret = sumsq(n_arg_0, tmp_arg_0); free(tmp_arg_0); xf2c_ret; }));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", ({ int n_arg_0 = 2; float *tmp_arg_0 = (float*) malloc(sizeof(float) * n_arg_0); if(!tmp_arg_0 && n_arg_0 > 0) exit(1); for(int i_arg_0 = 0; i_arg_0 < n_arg_0; ++i_arg_0) tmp_arg_0[i_arg_0] = x[i_arg_0] - 30; float xf2c_ret = sumsq(n_arg_0, tmp_arg_0); free(tmp_arg_0); xf2c_ret; }));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", ({ int n_arg_0 = 2; float *tmp_arg_0 = (float*) malloc(sizeof(float) * n_arg_0); if(!tmp_arg_0 && n_arg_0 > 0) exit(1); for(int i_arg_0 = 0; i_arg_0 < n_arg_0; ++i_arg_0) tmp_arg_0[i_arg_0] = ((i_arg_0 == 0 ? (10.0) : (20.0))) - ((i_arg_0 == 0 ? (30.0) : (40.0))); float xf2c_ret = sumsq(n_arg_0, tmp_arg_0); free(tmp_arg_0); xf2c_ret; }));
      first = 0;
      printf("\n");
   }
   return 0;
}
