/* Generated by xf2c.py from xassoc.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   float x;
   float y[3] = {100.0, 200.0, 300.0};
   x = 10.0;
   {
      float assoc_x2 = 2 * x;
      x = 3 * assoc_x2;
      {
         int first = 1;
         printf("%s%13.6f", first ? "" : " ", assoc_x2);
         first = 0;
         printf("%s%13.6f", first ? "" : " ", x);
         first = 0;
         printf("%s%13.6f", first ? "" : " ", x);
         first = 0;
         for (int i_pr = 0; i_pr < ((1 / 1 + 1)); ++i_pr) {
            printf("%s%13.6f", first ? "" : " ", y[i_pr + 1]);
            first = 0;
         }
         printf("\n");
      }
      if (1 > 0) {
         for (int i_fill = 2, p_fill = 0; p_fill < (((1 / 1 + 1))); i_fill += 1, ++p_fill) {
            y[i_fill - 1] = 10 * y[p_fill + 1];
         }
      } else {
         for (int i_fill = 2, p_fill = 0; p_fill < (((1 / 1 + 1))); i_fill += 1, ++p_fill) {
            y[i_fill - 1] = 10 * y[p_fill + 1];
         }
      }
      {
         int first = 1;
         for (int i_pr = 0; i_pr < 3; ++i_pr) {
            if (first) printf("%13.6f", y[i_pr]);
            else printf("    %13.6f", y[i_pr]);
            first = 0;
         }
         printf("    \n");
      }
   }
   return 0;
}
