/* Generated by xf2c.py from xbackspace.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"

int main(void) {
   enum { iu = 10 };
   int ios, cust, cust_next;
   float amt, amt_next, total;
   if (open_unit(10, trim_s("sales.txt"), "write", "replace") != 0) return 1;
   if (write_int_float_record(10, 3, 6, 1, 101, 10.0) != 0) return 1;
   if (write_int_float_record(10, 3, 6, 1, 101, 25.0) != 0) return 1;
   if (write_int_float_record(10, 3, 6, 1, 101, 5.0) != 0) return 1;
   if (write_int_float_record(10, 3, 6, 1, 205, 12.5) != 0) return 1;
   if (write_int_float_record(10, 3, 6, 1, 205, 7.5) != 0) return 1;
   if (write_int_float_record(10, 3, 6, 1, 310, 20.0) != 0) return 1;
   close_unit(10);
   if (open_unit(10, trim_s("sales.txt"), "read", "old") != 0) return 1;
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "customer totals");
      first = 0;
      printf("\n");
   }
   while (1) {
      ios = read_int_float_record(10, &cust, &amt);
      if (ios != 0) {
         goto xf2c_loop_1_break;
      }
      total = amt;
      while (1) {
         ios = read_int_float_record(10, &cust_next, &amt_next);
         if (ios != 0) {
            goto xf2c_loop_2_break;
         }
         if (cust_next != cust) {
            if (backspace_unit(10) != 0) return 1;
            goto xf2c_loop_2_break;
         }
         total += amt_next;
      }
      xf2c_loop_2_break: ;
      printf("%5d", cust);
      printf("%8.1f", total);
      printf("\n");
      if (ios != 0) {
         goto xf2c_loop_1_break;
      }
   }
   xf2c_loop_1_break: ;
   close_unit(10);
   return 0;
}
