/* Generated by xf2c.py from xblas_part.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"

const double zero = 0.0, one = 1.0;

double dnrm2(const int n, const int n_x, const double *x, const int incx); /* euclidean norm of the n-vector stored in x() with storage increment incx. */
void dswap(const int n, const int n_x, double *x, const int incx, const int n_y, double *y, const int incy); /* interchanges two vectors. */
int idamax(const int n, const int n_x, const double *x, const int incx); /* finds the index of element having max. absolute value. */
void dgemv(const char * trans, const int m, const int n, const double alpha, const int n_a_1, const int n_a_2, const double *a, const int lda, const int n_x, const double *x, const int incx, const double beta, const int n_y, double *y, const int incy); /* elf90 translation by alan miller   31-aug-1997 */
void test_dnrm2(int * nfail);
void test_dswap_unit(int * nfail);
void test_dswap_stride(int * nfail);
void test_idamax_unit(int * nfail);
void test_idamax_stride(int * nfail);
void test_dgemv_n(int * nfail);
void test_dgemv_t(int * nfail);
void check_real(const char * name, const double got, const double expect, const double tol, int *nfail);
void check_real_vec(const char * name, const int n_got, const double *got, const int n_expect, const double *expect, const double tol, int *nfail);
void check_int(const char * name, const int got, const int expect, int *nfail);

double dnrm2(const int n, const int n_x, const double *x, const int incx) {
   /* euclidean norm of the n-vector stored in x() with storage increment incx. */
   /* n_x: extent of x (dimension 1) */
   double fn_val, cuthi, cutlo, hitest, sum, xmax;
   int i, ix, next;
   if (n <= 0 || incx <= 0) {
      fn_val = 0.0;
      return fn_val;
   }
   cutlo = (sqrt(DBL_MIN / DBL_EPSILON));
   cuthi = sqrt(DBL_MAX);
   next = 1;
   sum = 0.0;
   i = 1;
   ix = 1;
   xf2c_stmt_20: ;
   switch (next) {
      case 1:
      {
         if ((fabs(x[i - 1])) > cutlo) {
            goto xf2c_stmt_85;
         }
         next = 2;
         xmax = 0.0;
         goto xf2c_stmt_20;
         break;
      }
      case 2:
      {
         if (x[i - 1] == (0.0)) {
            goto xf2c_stmt_200;
         }
         if ((fabs(x[i - 1])) > cutlo) {
            goto xf2c_stmt_85;
         }
         next = 3;
         goto xf2c_stmt_105;
         break;
      }
      case 3:
      {
         if ((fabs(x[i - 1])) > cutlo) {
            sum = sum * xmax * xmax;
            goto xf2c_stmt_85;
         }
         break;
      }
      case 4:
      {
         goto xf2c_stmt_110;
         break;
      }
   }
   xf2c_stmt_110: ;
   if ((fabs(x[i - 1])) <= xmax) goto xf2c_stmt_115;
   sum = (1.0) + sum * ((xmax / x[i - 1]) * (xmax / x[i - 1]));
   xmax = fabs(x[i - 1]);
   goto xf2c_stmt_200;
   xf2c_stmt_85: ;
   hitest = cuthi / ((double) n);
   while (ix <= n) {
      if ((fabs(x[i - 1])) >= hitest) {
         goto xf2c_stmt_100;
      }
      sum += (x[i - 1] * x[i - 1]);
      i += incx;
      ix += 1;
   }
   fn_val = sqrt(sum);
   return fn_val;
   xf2c_stmt_100: ;
   ix = ix;
   next = 4;
   sum = (sum / x[i - 1]) / x[i - 1];
   xf2c_stmt_105: ;
   xmax = fabs(x[i - 1]);
   xf2c_stmt_115: ;
   sum += ((x[i - 1]/xmax) * (x[i - 1]/xmax));
   xf2c_stmt_200: ;
   ix += 1;
   i += incx;
   if (ix <= n) {
      goto xf2c_stmt_20;
   }
   fn_val = xmax * sqrt(sum);
   return fn_val;
   return fn_val;
}

void dswap(const int n, const int n_x, double *x, const int incx, const int n_y, double *y, const int incy) {
   /* interchanges two vectors. */
   /* n_x: extent of x (dimension 1) */
   /* n_y: extent of y (dimension 1) */
   double temp[n];
   if (n <= 0) {
      return;
   }
   if (incx == 1 && incy == 1) {
      for (int p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); ++p_fill) {
         temp[p_fill] = x[p_fill];
      }
      if (1 > 0) {
         for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
            x[i_fill - 1] = y[p_fill];
         }
      } else {
         for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
            x[i_fill - 1] = y[p_fill];
         }
      }
      if (1 > 0) {
         for (int i_fill = 1, p_fill = 0; p_fill < n; i_fill += 1, ++p_fill) {
            y[i_fill - 1] = temp[p_fill];
         }
      } else {
         for (int i_fill = 1, p_fill = 0; p_fill < n; i_fill += 1, ++p_fill) {
            y[i_fill - 1] = temp[p_fill];
         }
      }
      return;
   }
   for (int p_fill = 0; p_fill < ((((incx > 0) ? ((n * incx - 1) / incx + 1) : ((1 - n * incx) / (-incx) + 1)))); ++p_fill) {
      temp[p_fill] = x[1 + p_fill * incx - 1];
   }
   if (incx > 0) {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((incy > 0) ? ((n * incy - 1) / incy + 1) : ((1 - n * incy) / (-incy) + 1)))); i_fill += incx, ++p_fill) {
         x[i_fill - 1] = y[1 + p_fill * incy - 1];
      }
   } else {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((incy > 0) ? ((n * incy - 1) / incy + 1) : ((1 - n * incy) / (-incy) + 1)))); i_fill += incx, ++p_fill) {
         x[i_fill - 1] = y[1 + p_fill * incy - 1];
      }
   }
   if (incy > 0) {
      for (int i_fill = 1, p_fill = 0; p_fill < n; i_fill += incy, ++p_fill) {
         y[i_fill - 1] = temp[p_fill];
      }
   } else {
      for (int i_fill = 1, p_fill = 0; p_fill < n; i_fill += incy, ++p_fill) {
         y[i_fill - 1] = temp[p_fill];
      }
   }
   return;
}

int idamax(const int n, const int n_x, const double *x, const int incx) {
   /* finds the index of element having max. absolute value. */
   /* n_x: extent of x (dimension 1) */
   int fn_val, imax[1];
   fn_val = 0;
   if (n < 1 || incx <= 0) {
      return fn_val;
   }
   fn_val = 1;
   if (n == 1) {
      return fn_val;
   }
   if (incx == 1) {
      {
         int loc = 0, i_pr = 0;
         double best = fabs(x[i_pr]);
         for (i_pr = 1; i_pr < (((n - 1) / 1 + 1)); ++i_pr) {
            if ((fabs(x[i_pr])) > best || (0 && ((fabs(x[i_pr])) == best))) { best = (fabs(x[i_pr])); loc = i_pr; }
         }
      imax[0] = loc + 1;
      }
   }
   else {
      {
         int loc = 0, i_pr = 0;
         double best = fabs(x[1 + i_pr * incx - 1]);
         for (i_pr = 1; i_pr < (((incx > 0) ? ((n * incx - 1) / incx + 1) : ((1 - n * incx) / (-incx) + 1))); ++i_pr) {
            if ((fabs(x[1 + i_pr * incx - 1])) > best || (0 && ((fabs(x[1 + i_pr * incx - 1])) == best))) { best = (fabs(x[1 + i_pr * incx - 1])); loc = i_pr; }
         }
      imax[0] = loc + 1;
      }
   }
   fn_val = imax[0];
   return fn_val;
   return fn_val;
}

void dgemv(const char * trans, const int m, const int n, const double alpha, const int n_a_1, const int n_a_2, const double *a, const int lda, const int n_x, const double *x, const int incx, const double beta, const int n_y, double *y, const int incy) {
   /* elf90 translation by alan miller   31-aug-1997 */
   /* n_a_1: extent of a (dimension 1) */
   /* n_a_2: extent of a (dimension 2) */
   /* n_x: extent of x (dimension 1) */
   /* n_y: extent of y (dimension 1) */
   double temp;
   int i, info, ix, iy, j, jx, jy, kx, ky, lenx, leny;
   info = 0;
   if (strcmp(trans, "n") != 0 && strcmp(trans, "n") != 0 && strcmp(trans, "t") != 0 && strcmp(trans, "t") != 0 && strcmp(trans, "c") != 0 && strcmp(trans, "c") != 0) {
      info = 1;
   }
   else if (m < 0) {
      info = 2;
   }
   else if (n < 0) {
      info = 3;
   }
   else if (lda < fmax(1, m)) {
      info = 6;
   }
   else if (incx == 0) {
      info = 8;
   }
   else if (incy == 0) {
      info = 11;
   }
   if (info != 0) {
      printf("%s", " error number: ");
      printf("%4d", info);
      printf("%s", " in blas2 routine dgemv");
      printf("\n");
      return;
   }
   if (m == 0 || n == 0 || (alpha == (0.0) && beta == (1.0))) {
      return;
   }
   if (strcmp(trans, "n") == 0 || strcmp(trans, "n") == 0) {
      lenx = n;
      leny = m;
   }
   else {
      lenx = m;
      leny = n;
   }
   if (incx > 0) {
      kx = 1;
   }
   else {
      kx = 1 - (lenx - 1) * incx;
   }
   if (incy > 0) {
      ky = 1;
   }
   else {
      ky = 1 - (leny - 1) * incy;
   }
   if (beta != (1.0)) {
      if (incy == 1) {
         if (beta == (0.0)) {
            if (1 > 0) {
               for (int i_fill = 1, p_fill = 0; i_fill <= leny; i_fill += 1, ++p_fill) {
                  y[i_fill - 1] = 0.0;
               }
            } else {
               for (int i_fill = 1, p_fill = 0; i_fill >= leny; i_fill += 1, ++p_fill) {
                  y[i_fill - 1] = 0.0;
               }
            }
         }
         else {
            if (1 > 0) {
               for (int i_fill = 1, p_fill = 0; p_fill < ((((leny - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
                  y[i_fill - 1] = beta * y[p_fill];
               }
            } else {
               for (int i_fill = 1, p_fill = 0; p_fill < ((((leny - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
                  y[i_fill - 1] = beta * y[p_fill];
               }
            }
         }
      }
      else {
         iy = ky;
         if (beta == (0.0)) {
            i = 0;
            while (i < leny) {
               y[iy - 1] = 0.0;
               iy += incy;
               i += 1;
            }
         }
         else {
            i = 0;
            while (i < leny) {
               y[iy - 1] = beta * y[iy - 1];
               iy += incy;
               i += 1;
            }
         }
      }
   }
   if (alpha == (0.0)) {
      return;
   }
   if (strcmp(trans, "n") == 0 || strcmp(trans, "n") == 0) {
      jx = kx;
      if (incy == 1) {
         j = 0;
         while (j < n) {
            if (x[jx - 1] != (0.0)) {
               temp = alpha * x[jx - 1];
               if (1 > 0) {
                  for (int i_fill = 1, p_fill = 0; p_fill < ((((m - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
                     y[i_fill - 1] = y[p_fill] + temp * a[p_fill + n_a_1 * j];
                  }
               } else {
                  for (int i_fill = 1, p_fill = 0; p_fill < ((((m - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
                     y[i_fill - 1] = y[p_fill] + temp * a[p_fill + n_a_1 * j];
                  }
               }
            }
            jx += incx;
            j += 1;
         }
      }
      else {
         j = 0;
         while (j < n) {
            if (x[jx - 1] != (0.0)) {
               temp = alpha * x[jx - 1];
               iy = ky;
               i = 0;
               while (i < m) {
                  y[iy - 1] += temp*a[i + n_a_1 * j];
                  iy += incy;
                  i += 1;
               }
            }
            jx += incx;
            j += 1;
         }
      }
   }
   else {
      jy = ky;
      if (incx == 1) {
         j = 0;
         while (j < n) {
            temp = ({ double red = 0.0; for (int i_red = 0; i_red < ((((m - 1) / 1 + 1))); ++i_red) red += (a[i_red + n_a_1 * j]) * (x[i_red]); red; });
            y[jy - 1] += alpha*temp;
            jy += incy;
            j += 1;
         }
      }
      else {
         j = 0;
         while (j < n) {
            temp = 0.0;
            ix = kx;
            i = 0;
            while (i < m) {
               temp += a[i + n_a_1 * j]*x[ix - 1];
               ix += incx;
               i += 1;
            }
            y[jy - 1] += alpha*temp;
            jy += incy;
            j += 1;
         }
      }
   }
   return;
}

void test_dnrm2(int * nfail) {
   double x[3], got, expect;
   x[0] = 3.0;
   x[1] = 4.0;
   x[2] = 12.0;
   got = dnrm2(3, 3, x, 1);
   expect = 13.0;
   check_real("dnrm2 unit stride", got, expect, 1.0e-12, nfail);
}

void test_dswap_unit(int * nfail) {
   double x[3], y[3];
   x[0] = 1.0;
   x[1] = 2.0;
   x[2] = 3.0;
   y[0] = 10.0;
   y[1] = 20.0;
   y[2] = 30.0;
   dswap(3, 3, x, 1, 3, y, 1);
   check_real_vec("dswap unit stride x", 3, x, 3, ((double[]){10.0, 20.0, 30.0}), 1.0e-12, nfail);
   check_real_vec("dswap unit stride y", 3, y, 3, ((double[]){1.0, 2.0, 3.0}), 1.0e-12, nfail);
}

void test_dswap_stride(int * nfail) {
   double x[6], y[6];
   x[0] = 1.0;
   x[1] = -(1.0);
   x[2] = 2.0;
   x[3] = -(2.0);
   x[4] = 3.0;
   x[5] = -(3.0);
   y[0] = 10.0;
   y[1] = -(10.0);
   y[2] = 20.0;
   y[3] = -(20.0);
   y[4] = 30.0;
   y[5] = -(30.0);
   dswap(3, 6, x, 2, 6, y, 2);
   check_real_vec("dswap stride x", 6, x, 6, ((double[]){10.0, -1.0, 20.0, -2.0, 30.0, -3.0}), 1.0e-12, nfail);
   check_real_vec("dswap stride y", 6, y, 6, ((double[]){1.0, -10.0, 2.0, -20.0, 3.0, -30.0}), 1.0e-12, nfail);
}

void test_idamax_unit(int * nfail) {
   double x[5];
   int got;
   x[0] = 1.0;
   x[1] = -(7.0);
   x[2] = 3.0;
   x[3] = 6.0;
   x[4] = -(2.0);
   got = idamax(5, 5, x, 1);
   check_int("idamax unit stride", got, 2, nfail);
}

void test_idamax_stride(int * nfail) {
   double x[6];
   int got;
   x[0] = 1.0;
   x[1] = 99.0;
   x[2] = -(5.0);
   x[3] = 88.0;
   x[4] = 4.0;
   x[5] = 77.0;
   got = idamax(3, 6, x, 2);
   check_int("idamax stride", got, 2, nfail);
}

void test_dgemv_n(int * nfail) {
   double a[6], x[3], y[2], expect[2];
   a[0] = 1.0;
   a[1] = 4.0;
   a[2] = 2.0;
   a[3] = 5.0;
   a[4] = 3.0;
   a[5] = 6.0;
   x[0] = 1.0;
   x[1] = 2.0;
   x[2] = 3.0;
   y[0] = 10.0;
   y[1] = 20.0;
   expect[0] = 24.0;
   expect[1] = 52.0;
   dgemv("n", 2, 3, 1.0, 2, 3, a, 2, 3, x, 1, 1.0, 2, y, 1);
   check_real_vec("dgemv n", 2, y, 2, expect, 1.0e-12, nfail);
}

void test_dgemv_t(int * nfail) {
   double a[6], x[2], y[3], expect[3];
   a[0] = 1.0;
   a[1] = 4.0;
   a[2] = 2.0;
   a[3] = 5.0;
   a[4] = 3.0;
   a[5] = 6.0;
   x[0] = 3.0;
   x[1] = 7.0;
   y[0] = 1.0;
   y[1] = 1.0;
   y[2] = 1.0;
   expect[0] = 32.0;
   expect[1] = 42.0;
   expect[2] = 52.0;
   dgemv("t", 2, 3, 1.0, 2, 3, a, 2, 2, x, 1, 1.0, 3, y, 1);
   check_real_vec("dgemv t", 3, y, 3, expect, 1.0e-12, nfail);
}

void check_real(const char * name, const double got, const double expect, const double tol, int *nfail) {
   if ((fabs(got - expect)) <= tol) {
      printf("%s", "pass: ");
      printf("%s", trim_s(name));
      printf("\n");
      if (1) {
         printf("%s", "  got    = ");
         printf("%24.16e", got);
         printf("\n");
         printf("%s", "  expect = ");
         printf("%24.16e", expect);
         printf("\n");
      }
   }
   else {
      printf("%s", "fail: ");
      printf("%s", trim_s(name));
      printf("\n");
      printf("%s", "  got    = ");
      printf("%24.16e", got);
      printf("\n");
      printf("%s", "  expect = ");
      printf("%24.16e", expect);
      printf("\n");
      (*nfail) = (*nfail) + 1;
   }
}

void check_real_vec(const char * name, const int n_got, const double *got, const int n_expect, const double *expect, const double tol, int *nfail) {
   /* n_got: extent of got (dimension 1) */
   /* n_expect: extent of expect (dimension 1) */
   int i;
   if (n_got != n_expect) {
      printf("%s", "fail: ");
      printf("%s", trim_s(name));
      printf("\n");
      printf("%s", "  size mismatch");
      printf("\n");
      (*nfail) = (*nfail) + 1;
      return;
   }
   if (({ int red = 1; for (int i_red = 0; i_red < n_got; ++i_red) if (!((fabs(got[i_red] - expect[i_red])) <= tol)) { red = 0; break; } red; })) {
      printf("%s", "pass: ");
      printf("%s", trim_s(name));
      printf("\n");
      if (1) {
         i = 1;
         while (i <= n_got) {
            printf("%s", "  i=");
            printf("%d", i);
            printf("%s", " got=");
            printf("%24.16e", got[i - 1]);
            printf("%s", " expect=");
            printf("%24.16e", expect[i - 1]);
            printf("\n");
            i += 1;
         }
      }
   }
   else {
      printf("%s", "fail: ");
      printf("%s", trim_s(name));
      printf("\n");
      i = 1;
      while (i <= n_got) {
         printf("%s", "  i=");
         printf("%d", i);
         printf("%s", " got=");
         printf("%24.16e", got[i - 1]);
         printf("%s", " expect=");
         printf("%24.16e", expect[i - 1]);
         printf("\n");
         i += 1;
      }
      (*nfail) = (*nfail) + 1;
   }
}

void check_int(const char * name, const int got, const int expect, int *nfail) {
   if (got == expect) {
      printf("%s", "pass: ");
      printf("%s", trim_s(name));
      printf("\n");
      if (1) {
         printf("%s", "  got    = ");
         printf("%d", got);
         printf("\n");
         printf("%s", "  expect = ");
         printf("%d", expect);
         printf("\n");
      }
   }
   else {
      printf("%s", "fail: ");
      printf("%s", trim_s(name));
      printf("\n");
      printf("%s", "  got    = ");
      printf("%d", got);
      printf("\n");
      printf("%s", "  expect = ");
      printf("%d", expect);
      printf("\n");
      (*nfail) = (*nfail) + 1;
   }
}

int main(void) {
   int nfail = 0;
   test_dnrm2(&nfail);
   test_dswap_unit(&nfail);
   test_dswap_stride(&nfail);
   test_idamax_unit(&nfail);
   test_idamax_stride(&nfail);
   test_dgemv_n(&nfail);
   test_dgemv_t(&nfail);
   printf("%s", "");
   printf("\n");
   if (nfail == 0) {
      printf("%s", "all tests passed");
      printf("\n");
   }
   else {
      printf("%s", "number of failed tests: ");
      printf("%d", nfail);
      printf("\n");
      fprintf(stderr, "%s\n", "test failure");
      return 1;
   }
   return 0;
}
