/* Generated by xf2c.py from xbroadcast.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   {
      int ctor_0[] = {10, 20, 30};
      for (int i_pr = 0; i_pr < 3; ++i_pr) {
         printf("%12d", 3 + ctor_0[i_pr]);
      }
      printf("\n");
   }
   {
      int ctor_0[] = {10, 20, 30};
      for (int i_pr = 0; i_pr < 3; ++i_pr) {
         printf("%12d", 3 - ctor_0[i_pr]);
      }
      printf("\n");
   }
   {
      int ctor_0[] = {10, 20, 30};
      for (int i_pr = 0; i_pr < 3; ++i_pr) {
         printf("%12d", 3 * ctor_0[i_pr]);
      }
      printf("\n");
   }
   {
      int ctor_0[] = {10, 20, 30};
      for (int i_pr = 0; i_pr < 3; ++i_pr) {
         printf("%12d", ctor_0[i_pr] / 3);
      }
      printf("\n");
   }
   return 0;
}
