/* Generated by xf2c.py from xchar_sections.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"

void split(const char * line, const int n, char **fields);

void split(const char * line, const int n, char **fields) {
   /* n: extent of fields (dimension 1) */
   int i, i0, k, lt;
   for (int i_fill = 0; i_fill < n; ++i_fill) {
      assign_str_alloc(&fields[i_fill], "");
   }
   lt = len_trim_s(line);
   i0 = 1;
   k = 1;
   i = 1;
   while (i <= lt) {
      if (strcmp(substr_s(line, i, i), ",") == 0) {
         if (k <= n) {
            assign_str_alloc(&fields[k - 1], adjustl_s(substr_s(line, i0, i - 1)));
         }
         k += 1;
         i0 = i + 1;
      }
      i += 1;
   }
   if (k <= n) {
      assign_str_alloc(&fields[k - 1], adjustl_s(substr_s(line, i0, lt)));
   }
}

int main(void) {
   char **fields = NULL, **names = NULL;
   int n_fields = 0, n_names = 0;
   if (fields) free_str_array(fields, n_fields);
   fields = (char**) malloc(sizeof(char*) * 3);
   if (!fields && 3 > 0) return 1;
   for (int i_fill = 0; i_fill < 3; ++i_fill) fields[i_fill] = NULL;
   n_fields = 3;
   for (int i_fill = 0; i_fill < 3; ++i_fill) assign_str_alloc(&fields[i_fill], "");
   split("d,a,b", n_fields, fields);
   if (names) free_str_array(names, n_names);
   names = (char**) malloc(sizeof(char*) * 2);
   if (!names && 2 > 0) return 1;
   for (int i_fill = 0; i_fill < 2; ++i_fill) names[i_fill] = NULL;
   n_names = 2;
   for (int i_fill = 0; i_fill < 2; ++i_fill) assign_str_alloc(&names[i_fill], "");
   {
      int n_tmp = 0;
      if (1 > 0) {
         for (int i_fill = 2; i_fill <= n_fields; i_fill += 1) ++n_tmp;
      } else {
         for (int i_fill = 2; i_fill >= n_fields; i_fill += 1) ++n_tmp;
      }
      if (names) free_str_array(names, n_names);
      names = (char**) malloc(sizeof(char*) * n_tmp);
      if (!names && n_tmp > 0) return 1;
      for (int p_fill = 0; p_fill < n_tmp; ++p_fill) names[p_fill] = NULL;
      n_names = n_tmp;
      for (int p_fill = 0; p_fill < n_tmp; ++p_fill) {
         assign_str_alloc(&names[p_fill], fields[p_fill + 1]);
      }
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", trim_s(names[0]));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", trim_s(names[1]));
      first = 0;
      printf("\n");
   }
   free_str_array(fields, n_fields);
   free_str_array(names, n_names);
   return 0;
}
