/* Generated by xf2c.py from xcolslice_tmp.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

double mean(const int n, const double *x);
double sd(const int n, const double *x);

double mean(const int n, const double *x) {
   /* n: extent of x (dimension 1) */
   double mu;
   {
      double red = 0.0;
      for (int i_fill = 0; i_fill < n; ++i_fill) red += x[i_fill];
      mu = red / ((float) n);
   }
   return mu;
}

double sd(const int n, const double *x) {
   /* n: extent of x (dimension 1) */
   double sig, mu;
   if (n <= 1) {
      sig = 0.0;
   }
   else {
      mu = mean(n, x);
      {
         double red = 0.0;
         for (int i_fill = 0; i_fill < n; ++i_fill) red += ((x[i_fill] - mu) * (x[i_fill] - mu));
         sig = (sqrtf(red / ((float) (n - 1))));
      }
   }
   return sig;
}

int main(void) {
   double *a = NULL, *mu = NULL, *sig = NULL;
   int j;
   a = (double*) malloc(sizeof(double) * 6);
   if (!a) return 1;
   mu = (double*) malloc(sizeof(double) * 2);
   if (!mu) return 1;
   sig = (double*) malloc(sizeof(double) * 2);
   if (!sig) return 1;
   a[0] = 1.0;
   a[1] = 2.0;
   a[2] = 5.0;
   a[3] = 3.0;
   a[4] = 4.0;
   a[5] = 9.0;
   j = 0;
   while (j < 2) {
      mu[j] = mean(3, &a[3 * j]);
      sig[j] = sd(3, &a[3 * j]);
      j += 1;
   }
   {
      int first = 1;
      for (int i_pr = 0; i_pr < 2; ++i_pr) {
         if (first) printf("%13.6f", mu[i_pr]);
         else printf("    %13.6f", mu[i_pr]);
         first = 0;
      }
      printf("    \n");
   }
   {
      int first = 1;
      for (int i_pr = 0; i_pr < 2; ++i_pr) {
         if (first) printf("%13.6f", sig[i_pr]);
         else printf("    %13.6f", sig[i_pr]);
         first = 0;
      }
      printf("    \n");
   }
   free(a);
   free(mu);
   free(sig);
   return 0;
}
