/* Generated by xf2c.py from xcomplex.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   float complex z;
   z = ((float complex) (3.0 + 4.0 * I));
   {
      int first = 1;
      printf("%s(%g,%g)", first ? "" : " ", (crealf(z)), (cimagf(z)));
      first = 0;
      printf("\n");
   }
   z = ((float complex) (3.0 + 4.0 * I));
   {
      int first = 1;
      printf("%s(%g,%g)", first ? "" : " ", (crealf(z)), (cimagf(z)));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s(%g,%g)", first ? "" : " ", (crealf(conjf(z))), (cimagf(conjf(z))));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", (cabsf(z)));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s(%g,%g)", first ? "" : " ", (crealf(z * z)), (cimagf(z * z)));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", (crealf(z)));
      first = 0;
      printf("%s%13.6f", first ? "" : " ", (cimagf(z)));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", (crealf(z)));
      first = 0;
      printf("%s%13.6f", first ? "" : " ", (cimagf(z)));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s(%g,%g)", first ? "" : " ", (crealf((csqrtf(((float complex) (-(1.0) + 0.0 * I)))))), (cimagf((csqrtf(((float complex) (-(1.0) + 0.0 * I)))))));
      first = 0;
      printf("\n");
   }
   return 0;
}
