/* Generated by xf2c.py from xcommon_demo_nocommon.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

float x, y, avg;
int n;

void compute_avg();

int main(void) {
   x = 10.0;
   y = 20.0;
   n = 2;
   compute_avg();
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", avg);
      first = 0;
      printf("\n");
   }
   return 0;
}

void compute_avg() {
   avg = (x + y) / n;
}
