/* Generated by xf2c.py from xdata_repeat.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   int i;
   int b[10] = {1, 1, 1, 2, 2, 2, 2, 9, 9, 9};
   printf("%s\n", "array b:");
   {
      for (int i_pr = 0; i_pr < 10; ++i_pr) {
         printf("%12d", b[i_pr]);
      }
      printf("\n");
   }
   return 0;
}
