/* Generated by xf2c.py from xdate.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

typedef struct {
   int year, month;
} date;

date make_date(const int year, const int month);
int month_index(const date d);
date index_to_date(const int idx);
int date_eq(const date d1, const date d2);
int date_ne(const date d1, const date d2);
int date_lt(const date d1, const date d2);
int date_le(const date d1, const date d2);
int date_gt(const date d1, const date d2);
int date_ge(const date d1, const date d2);
date date_plus_int(const date d, const int n);
date int_plus_date(const int n, const date d);
date date_minus_int(const date d, const int n);
int date_minus_date(const date d1, const date d2);

date make_date(const int year, const int month) {
   date d;
   if (month < 1 || month > 12) {
      fprintf(stderr, "%s\n", "make_date: month must be between 1 and 12");
      exit(1);
   }
   d.year = year;
   d.month = month;
   return d;
}

int month_index(const date d) {
   int idx = 12 * d.year + d.month - 1;
   return idx;
}

date index_to_date(const int idx) {
   date d;
   d.year = idx / 12;
   d.month = ((idx % 12)) + 1;
   if (d.month <= 0) {
      d.month = d.month + 12;
      d.year = d.year - 1;
   }
   return d;
}

int date_eq(const date d1, const date d2) {
   int result = d1.year == d2.year && d1.month == d2.month;
   return result;
}

int date_ne(const date d1, const date d2) {
   int result = ! (date_eq(d1, d2));
   return result;
}

int date_lt(const date d1, const date d2) {
   int result = month_index(d1) < month_index(d2);
   return result;
}

int date_le(const date d1, const date d2) {
   int result = month_index(d1) <= month_index(d2);
   return result;
}

int date_gt(const date d1, const date d2) {
   int result = month_index(d1) > month_index(d2);
   return result;
}

int date_ge(const date d1, const date d2) {
   int result = month_index(d1) >= month_index(d2);
   return result;
}

date date_plus_int(const date d, const int n) {
   date ans;
   ans = index_to_date(month_index(d) + n);
   return ans;
}

date int_plus_date(const int n, const date d) {
   date ans;
   ans = date_plus_int(d, n);
   return ans;
}

date date_minus_int(const date d, const int n) {
   date ans;
   ans = index_to_date(month_index(d) - n);
   return ans;
}

int date_minus_date(const date d1, const date d2) {
   int nmonths = month_index(d1) - month_index(d2);
   return nmonths;
}

int main(void) {
   date d1 = {0};
   date d2 = {0};
   date d3 = {0};
   date d4 = {0};
   date d5 = {0};
   d1 = make_date(2024, 11);
   d2 = make_date(2025, 2);
   d3 = make_date(2024, 11);
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "d1 = ");
      first = 0;
      printf("%s%d", first ? "" : " ", d1.year);
      first = 0;
      printf("%s%d", first ? "" : " ", d1.month);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "d2 = ");
      first = 0;
      printf("%s%d", first ? "" : " ", d2.year);
      first = 0;
      printf("%s%d", first ? "" : " ", d2.month);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "d3 = ");
      first = 0;
      printf("%s%d", first ? "" : " ", d3.year);
      first = 0;
      printf("%s%d", first ? "" : " ", d3.month);
      first = 0;
      printf("\n");
   }
   printf("\n");
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "comparison operators");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "d1 == d3: ");
      first = 0;
      printf("%s%s", first ? "" : " ", (date_eq(d1, d3)) ? "T" : "F");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "d1 /= d2: ");
      first = 0;
      printf("%s%s", first ? "" : " ", (date_ne(d1, d2)) ? "T" : "F");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "d1 <  d2: ");
      first = 0;
      printf("%s%s", first ? "" : " ", (date_lt(d1, d2)) ? "T" : "F");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "d1 <= d3: ");
      first = 0;
      printf("%s%s", first ? "" : " ", (date_le(d1, d3)) ? "T" : "F");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "d2 >  d1: ");
      first = 0;
      printf("%s%s", first ? "" : " ", (date_gt(d2, d1)) ? "T" : "F");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "d2 >= d3: ");
      first = 0;
      printf("%s%s", first ? "" : " ", (date_ge(d2, d3)) ? "T" : "F");
      first = 0;
      printf("\n");
   }
   printf("\n");
   d4 = date_plus_int(d1, 5);
   d5 = date_minus_int(d2, 7);
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "date plus/minus integer operators");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "d1 + 5 months = ");
      first = 0;
      printf("%s%d", first ? "" : " ", d4.year);
      first = 0;
      printf("%s%d", first ? "" : " ", d4.month);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "d2 - 7 months = ");
      first = 0;
      printf("%s%d", first ? "" : " ", d5.year);
      first = 0;
      printf("%s%d", first ? "" : " ", d5.month);
      first = 0;
      printf("\n");
   }
   d5 = int_plus_date(3, d1);
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "3 + d1        = ");
      first = 0;
      printf("%s%d", first ? "" : " ", d5.year);
      first = 0;
      printf("%s%d", first ? "" : " ", d5.month);
      first = 0;
      printf("\n");
   }
   printf("\n");
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "date minus date operator");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "d2 - d1 in months = ");
      first = 0;
      printf("%s%d", first ? "" : " ", date_minus_date(d2, d1));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "d1 - d2 in months = ");
      first = 0;
      printf("%s%d", first ? "" : " ", date_minus_date(d1, d2));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "d3 - d1 in months = ");
      first = 0;
      printf("%s%d", first ? "" : " ", date_minus_date(d3, d1));
      first = 0;
      printf("\n");
   }
   return 0;
}
