/* Generated by xf2c.py from xdata_array.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   int i;
   int a[5] = {10, 20, 30, 40, 50};
   printf("%s\n", "array a:");
   i = 1;
   while (i <= 5) {
      {
         int first = 1;
         printf("%s%s", first ? "" : " ", "a(");
         first = 0;
         printf("%s%d", first ? "" : " ", i);
         first = 0;
         printf("%s%s", first ? "" : " ", ") = ");
         first = 0;
         printf("%s%d", first ? "" : " ", a[i - 1]);
         first = 0;
         printf("\n");
      }
      i += 1;
   }
   return 0;
}
