/* Generated by xf2c.py from xdata_scalar.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"

int main(void) {
   int n = 5;
   float x = 2.5, y = 7.25;
   char name[13] = "fortran     ";
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "n    = ");
      first = 0;
      printf("%s%d", first ? "" : " ", n);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "x    = ");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", x);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "y    = ");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", y);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "name = [");
      first = 0;
      printf("%s%s", first ? "" : "", trim_s(name));
      first = 0;
      printf("%s%s", first ? "" : "", "]");
      first = 0;
      printf("\n");
   }
   return 0;
}
