/* Generated by xf2c.py from xdata_save.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

void show_count();

int main(void) {
   show_count();
   show_count();
   show_count();
   return 0;
}

void show_count() {
   static int count = 0;
   count += 1;
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "count = ");
      first = 0;
      printf("%s%d", first ? "" : " ", count);
      first = 0;
      printf("\n");
   }
}
