/* Generated by xf2c.py from xdata_matrix.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   int i;
   int a[6] = {1, 2, 3, 4, 5, 6};
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "matrix a(2,3):");
      first = 0;
      printf("\n");
   }
   i = 0;
   while (i < 2) {
      {
         for (int j = 0; j < 3; ++j) {
            printf("%4d", a[i + 2 * j]);
         }
         printf("\n");
      }
      i += 1;
   }
   printf("\n");
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "note: data fills arrays in column-major order");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "so the columns are:");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "column 1:");
      first = 0;
      for (int i_pr = 0; i_pr < 2; ++i_pr) {
         printf("%s%d", first ? "" : " ", a[i_pr]);
         first = 0;
      }
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "column 2:");
      first = 0;
      for (int i_pr = 0; i_pr < 2; ++i_pr) {
         printf("%s%d", first ? "" : " ", a[i_pr + 2]);
         first = 0;
      }
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "column 3:");
      first = 0;
      for (int i_pr = 0; i_pr < 2; ++i_pr) {
         printf("%s%d", first ? "" : " ", a[i_pr + 4]);
         first = 0;
      }
      printf("\n");
   }
   return 0;
}
