/* Generated by xf2c.py from xdf_alloc.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"

typedef struct {
   char **row_names, **col_names;
   int n_row_names, n_col_names, n_x_1, n_x_2;
   float *x;
} df;

int main(void) {
   typedef struct {
      char **row_names, **col_names;
      int n_row_names, n_col_names, n_x_1, n_x_2;
      float *x;
   } df;
   char **row_names = NULL, **col_names = NULL;
   int n_row_names = 0, n_col_names = 0, n_x_1 = 0, n_x_2 = 0, n_a = 0;
   float *x = NULL;
   df *a = NULL;
   if (a) free(a);
   a = (df*) calloc(2, sizeof(df));
   if (!a && 2 > 0) return 1;
   n_a = 2;
   if (a[0].x) free(a[0].x);
   a[0].x = (float*) malloc(sizeof(float) * 6);
   if (!a[0].x && 6 > 0) return 1;
   a[0].n_x_1 = 3;
   a[0].n_x_2 = 2;
   for (int i_fill = 0; i_fill < 6; ++i_fill) a[0].x[i_fill] = 2.3;
   if (a[0].row_names) free(a[0].row_names);
   a[0].row_names = (char**) malloc(sizeof(char*) * 3);
   if (!a[0].row_names && 3 > 0) return 1;
   a[0].n_row_names = 3;
   a[0].row_names[0] = strdup("a");
   a[0].row_names[1] = strdup("b");
   a[0].row_names[2] = strdup("c");
   if (a[0].col_names) free(a[0].col_names);
   a[0].col_names = (char**) malloc(sizeof(char*) * 2);
   if (!a[0].col_names && 2 > 0) return 1;
   a[0].n_col_names = 2;
   a[0].col_names[0] = strdup("x1");
   a[0].col_names[1] = strdup("x2");
   {
      int first = 1;
      for (int i_pr = 0; i_pr < a[0].n_x_1 * a[0].n_x_2; ++i_pr) {
         if (first) printf("%13.6f", a[0].x[i_pr]);
         else printf("    %13.6f", a[0].x[i_pr]);
         first = 0;
      }
      printf("    \n");
   }
   {
      int first = 1;
      for (int i_pr = 0; i_pr < a[0].n_row_names; ++i_pr) {
         printf("%s%s", first ? "" : " ", a[0].row_names[i_pr]);
         first = 0;
      }
      printf("\n");
   }
   {
      int first = 1;
      for (int i_pr = 0; i_pr < a[0].n_col_names; ++i_pr) {
         printf("%s%s", first ? "" : " ", a[0].col_names[i_pr]);
         first = 0;
      }
      printf("\n");
   }
   free_str_array(row_names, n_row_names);
   free_str_array(col_names, n_col_names);
   free(x);
   free(a);
   return 0;
}
