/* Generated by xf2c.py from xdim_attr_colon.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

void fill(const int n, int *irngt);

void fill(const int n, int *irngt) {
   /* n: extent of irngt (dimension 1) */
   for (int i_fill = 0; i_fill < n; ++i_fill) {
      irngt[i_fill] = 7;
   }
}

int main(void) {
   int *x = NULL;
   x = (int*) malloc(sizeof(int) * 3);
   if (!x) return 1;
   x[0] = 1;
   x[1] = 2;
   x[2] = 3;
   fill(3, x);
   {
      for (int i_pr = 0; i_pr < 3; ++i_pr) {
         printf("%12d", x[i_pr]);
      }
      printf("\n");
   }
   free(x);
   return 0;
}
