/* Generated by xf2c.py from xdp.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

double mult(const int n, const double x);

double mult(const int n, const double x) {
   double x2 = ((double) n) * x;
   return x2;
}

int main(void) {
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", mult(3, 5.0));
      first = 0;
      printf("\n");
   }
   return 0;
}
