/* Generated by xf2c.py from xdt.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

typedef struct {
   float x, y;
} cc;

int main(void) {
   typedef struct {
      float x, y;
   } cc;
   float x, y;
   cc z = (cc){10.0, 20.0};
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", z.x);
      first = 0;
      printf("%s%13.6f", first ? "" : " ", z.y);
      first = 0;
      printf("\n");
   }
   z.x = 3.0;
   z.y = 4.0;
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", z.x);
      first = 0;
      printf("%s%13.6f", first ? "" : " ", z.y);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", z.x);
      first = 0;
      printf("%s%13.6f", first ? "" : " ", z.y);
      first = 0;
      printf("\n");
   }
   return 0;
}
