/* Generated by xf2c.py from xdt_array.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

typedef struct {
   float x[2];
} t;
typedef struct {
   t z;
} u;

int main(void) {
   typedef struct {
      float x[2];
   } t;
   typedef struct {
      t z;
   } u;
   float *x = NULL;
   t z = {0};
   u uu = {0};
   x = (float*) malloc(sizeof(float) * 2);
   if (!x) return 1;
   uu.z.x[0] = 100.0;
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", uu.z.x[0]);
      first = 0;
      printf("\n");
   }
   free(x);
   return 0;
}
