/* Generated by xf2c.py from xdt_alloc.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

typedef struct {
   float *x;
   int n_x;
} df;

int main(void) {
   typedef struct {
      float *x;
      int n_x;
   } df;
   float *x = NULL;
   int n_x = 0;
   df a = {0};
   if (a.x) free(a.x);
   a.x = (float*) malloc(sizeof(float) * 2);
   if (!a.x && 2 > 0) return 1;
   a.n_x = 2;
   a.x[0] = 10.0;
   a.x[1] = 20.0;
   {
      int first = 1;
      for (int i_pr = 0; i_pr < a.n_x; ++i_pr) {
         if (first) printf("%13.6f", a.x[i_pr]);
         else printf("    %13.6f", a.x[i_pr]);
         first = 0;
      }
      printf("    \n");
   }
   free(x);
   return 0;
}
