/* Generated by xf2c.py from xdynamic_fmt_write.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   int name_width;
   char fmt[101] = "";
   name_width = 5;
   printf("%*s  %14s  %14s\n", name_width, "asset", "mean_return", "std_return");
   printf("%*s  %14.8f  %14.8f\n", name_width, "SPY", 0.00044098e0, 0.01192712e0);
   return 0;
}
