/* Generated by xf2c.py from xempty.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

float tail_real(const int n, const float *xx); /* return the last element of xx(:) */

float tail_real(const int n, const float *xx) {
   /* return the last element of xx(:) */
   /* n: extent of xx (dimension 1) */
   float yy;
   if (n > 0) {
      yy = xx[n - 1];
   }
   else {
      yy = -(1.0);
   }
   return yy;
}

int main(void) {
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", tail_real(0, ((float[]){})));
      first = 0;
      printf("\n");
   }
   return 0;
}
