/* Generated by xf2c.py from xerror_stop_concat.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"

int main(void) {
   enum { filename_len = 20 };
   char filename[filename_len + 1] = "";
   assign_str(filename, filename_len, "data.csv");
   fprintf(stderr, "%s\n", concat_s2("cannot open ", trim_s(filename)));
   return 1;
}
