/* Generated by xf2c.py from xerror_stop.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   fprintf(stderr, "%s\n", "dimension mismatch");
   return 1;
}
