/* Generated by xf2c.py from xexit.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   int i, j;
   j = 1;
   while (j <= 3) {
      i = 1;
      while (i <= 6) {
         if (((i % 2)) == 0) {
            goto xf2c_loop_2_break;
         }
         {
            int first = 1;
            printf("%s%d", first ? "" : " ", i*j);
            first = 0;
            printf("%s%d", first ? "" : " ", (i * j * i * j));
            first = 0;
            printf("\n");
         }
         i += 1;
      }
      xf2c_loop_2_break: ;
      j += 1;
   }
   return 0;
}
