/* Generated by xf2c.py from xextent_n.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int idamax(const int n, const int n_x, const float *x);

int idamax(const int n, const int n_x, const float *x) {
   /* n_x: extent of x (dimension 1) */
   int result;
   if (n < 1) {
      return result;
   }
   result = 1;
   return result;
}
