/* Generated by xf2c.py from xfixed_as_f90_1.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "hi");
      first = 0;
      printf("\n");
   }
   return 0;
}
