/* Generated by xf2c.py from xfmt_rowslice_tmp.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"

int main(void) {
   char names[2][9];
   double *corr = NULL;
   int i;
   corr = (double*) malloc(sizeof(double) * 4);
   if (!corr) return 1;
   assign_str(names[0], 8, "SPY");
   assign_str(names[1], 8, "EFA");
   corr[0] = 1.0;
   corr[2] = 0.8912;
   corr[1] = 0.8912;
   corr[3] = 1.0;
   printf("\n");
   printf("%s", "correlation matrix of returns");
   printf("\n");
   printf("%8s", "");
   {
      for (int j = 0; j < 2; ++j) {
         printf("%8s", trim_s(names[j]));
      }
      printf("\n");
   }
   i = 0;
   while (i < 2) {
      printf("%8s", trim_s(names[i]));
      for (int j_fmt = 0; j_fmt < 2; ++j_fmt) {
         printf("%8.4f", corr[i + 2 * j_fmt]);
      }
      printf("\n");
      i += 1;
   }
   free(corr);
   return 0;
}
