/* Generated by xf2c.py from xfmt_prefix_arr.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   float *x = NULL, *g = NULL;
   x = (float*) malloc(sizeof(float) * 2);
   if (!x) return 1;
   g = (float*) malloc(sizeof(float) * 2);
   if (!g) return 1;
   x[0] = 1.0;
   x[1] = 2.0;
   g[0] = 3.0;
   g[1] = 4.0;
   printf("%s", " Final X: ");
   for (int idx_arr = 0; idx_arr < 2; ) {
      if (idx_arr < 2) printf("%12.8f", x[idx_arr]);
      ++idx_arr;
   }
   printf("\n");
   printf("%s", " Gradients: ");
   for (int idx_arr = 0; idx_arr < 2; ) {
      if (idx_arr < 2) printf("%13.5g", g[idx_arr]);
      ++idx_arr;
   }
   printf("\n");
   free(x);
   free(g);
   return 0;
}
