/* Generated by xf2c.py from xforall_more.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   enum { n = 5 };
   int i, j;
   int *a = NULL, *b = NULL, *c = NULL, *d = NULL, *m = NULL, *t = NULL;
   a = (int*) malloc(sizeof(int) * 5);
   if (!a) return 1;
   b = (int*) malloc(sizeof(int) * 5);
   if (!b) return 1;
   c = (int*) malloc(sizeof(int) * 5);
   if (!c) return 1;
   d = (int*) malloc(sizeof(int) * 5);
   if (!d) return 1;
   m = (int*) malloc(sizeof(int) * 9);
   if (!m) return 1;
   t = (int*) malloc(sizeof(int) * 9);
   if (!t) return 1;
   i = 1;
   while (i <= 5) {
      a[i - 1] = i * i;
      i += 1;
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "example 1: a(i) = i*i");
      first = 0;
      printf("\n");
   }
   {
      int first_pr = 1;
      printf("%s%s", first_pr ? "" : " ", "a =");
      first_pr = 0;
      for (int i_pr = 0; i_pr < 5; ++i_pr) {
         printf("%s%d", first_pr ? "" : " ", a[i_pr]);
         first_pr = 0;
      }
      printf("\n");
   }
   printf("\n");
   i = 0;
   while (i < 5) {
      b[i] = 10 * a[i] + 1;
      i += 1;
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "example 2: b(i) = 10*a(i) + 1");
      first = 0;
      printf("\n");
   }
   {
      int first_pr = 1;
      printf("%s%s", first_pr ? "" : " ", "b =");
      first_pr = 0;
      for (int i_pr = 0; i_pr < 5; ++i_pr) {
         printf("%s%d", first_pr ? "" : " ", b[i_pr]);
         first_pr = 0;
      }
      printf("\n");
   }
   printf("\n");
   for (int i_fill = 0; i_fill < 5; ++i_fill) {
      c[i_fill] = 0;
   }
   i = 1;
   while (i <= 5) {
      if (((i % 2)) == 0) {
         c[i - 1] = -i;
      }
      i += 1;
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "example 3: masked forall, only even i updated");
      first = 0;
      printf("\n");
   }
   {
      int first_pr = 1;
      printf("%s%s", first_pr ? "" : " ", "c =");
      first_pr = 0;
      for (int i_pr = 0; i_pr < 5; ++i_pr) {
         printf("%s%d", first_pr ? "" : " ", c[i_pr]);
         first_pr = 0;
      }
      printf("\n");
   }
   printf("\n");
   i = 1;
   while (i <= 5) {
      d[i - 1] = i;
      a[i - 1] = i + 100;
      i += 1;
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "example 4: forall construct with multiple assignments");
      first = 0;
      printf("\n");
   }
   {
      int first_pr = 1;
      printf("%s%s", first_pr ? "" : " ", "d =");
      first_pr = 0;
      for (int i_pr = 0; i_pr < 5; ++i_pr) {
         printf("%s%d", first_pr ? "" : " ", d[i_pr]);
         first_pr = 0;
      }
      printf("\n");
   }
   {
      int first_pr = 1;
      printf("%s%s", first_pr ? "" : " ", "a =");
      first_pr = 0;
      for (int i_pr = 0; i_pr < 5; ++i_pr) {
         printf("%s%d", first_pr ? "" : " ", a[i_pr]);
         first_pr = 0;
      }
      printf("\n");
   }
   printf("\n");
   i = 1;
   while (i <= 3) {
      j = 1;
      while (j <= 3) {
         m[i - 1 + 3 * (j - 1)] = 10 * i + j;
         j += 1;
      }
      i += 1;
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "example 5: matrix m(i,j) = 10*i + j");
      first = 0;
      printf("\n");
   }
   i = 0;
   while (i < 3) {
      {
         int idx_sec = 0;
         if (idx_sec < 3) printf("%5d", m[i + 3 * idx_sec]);
         idx_sec += 1;
         if (idx_sec < 3) printf("%5d", m[i + 3 * idx_sec]);
         idx_sec += 1;
         if (idx_sec < 3) printf("%5d", m[i + 3 * idx_sec]);
         idx_sec += 1;
      }
      printf("\n");
      i += 1;
   }
   printf("\n");
   i = 0;
   while (i < 3) {
      j = 0;
      while (j < 3) {
         t[i + 3 * j] = m[j + 3 * i];
         j += 1;
      }
      i += 1;
   }
   printf("%s\n", "example 6: transpose of m");
   i = 0;
   while (i < 3) {
      {
         int idx_sec = 0;
         if (idx_sec < 3) printf("%5d", t[i + 3 * idx_sec]);
         idx_sec += 1;
         if (idx_sec < 3) printf("%5d", t[i + 3 * idx_sec]);
         idx_sec += 1;
         if (idx_sec < 3) printf("%5d", t[i + 3 * idx_sec]);
         idx_sec += 1;
      }
      printf("\n");
      i += 1;
   }
   printf("\n");
   for (int i_fill = 0; i_fill < 9; ++i_fill) {
      m[i_fill] = 0;
   }
   i = 1;
   while (i <= 3) {
      j = 1;
      while (j <= 3) {
         if (i <= j) {
            m[i - 1 + 3 * (j - 1)] = i + j;
         }
         j += 1;
      }
      i += 1;
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "example 7: fill upper triangle only");
      first = 0;
      printf("\n");
   }
   i = 0;
   while (i < 3) {
      {
         int idx_sec = 0;
         if (idx_sec < 3) printf("%5d", m[i + 3 * idx_sec]);
         idx_sec += 1;
         if (idx_sec < 3) printf("%5d", m[i + 3 * idx_sec]);
         idx_sec += 1;
         if (idx_sec < 3) printf("%5d", m[i + 3 * idx_sec]);
         idx_sec += 1;
      }
      printf("\n");
      i += 1;
   }
   free(a);
   free(b);
   free(c);
   free(d);
   free(m);
   free(t);
   return 0;
}
