/* Generated by xf2c.py from xforall.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   int i, j;
   enum { n1 = 3 };
   enum { n2 = 4 };
   float *x = NULL;
   x = (float*) malloc(sizeof(float) * 12);
   if (!x) return 1;
   i = 1;
   while (i <= 3) {
      j = 1;
      while (j <= 4) {
         x[i - 1 + 3 * (j - 1)] = ((float) (i - j));
         j += 1;
      }
      i += 1;
   }
   i = 0;
   while (i < 3) {
      {
         int first = 1;
         for (int i2 = 1; i2 <= 4; i2 += 1) {
            printf("%s%g", first ? "" : " ", x[i + 3 * (i2 - 1)]);
            first = 0;
         }
         printf("\n");
      }
      i += 1;
   }
   i = 1;
   while (i <= 3) {
      j = 1;
      while (j <= 4) {
         x[i - 1 + 3 * (j - 1)] = ((float) (i + j));
         j += 1;
      }
      i += 1;
   }
   i = 0;
   while (i < 3) {
      {
         int first = 1;
         for (int i2 = 1; i2 <= 4; i2 += 1) {
            printf("%s%g", first ? "" : " ", x[i + 3 * (i2 - 1)]);
            first = 0;
         }
         printf("\n");
      }
      i += 1;
   }
   free(x);
   return 0;
}
