/* Generated by xf2c.py from xfunc.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   const double x = 1.0;
   {
      int first = 1;
      printf("%s%.17g", first ? "" : " ", (fabs(1.0)));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", acos(1.0));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", acosh(1.0));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", asin(1.0));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", asinh(1.0));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", atan(1.0));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", atanh(0.5));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", cos(1.0));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", cosh(1.0));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", exp(1.0));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", (log10(1.0)));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", sin(1.0));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", sinh(1.0));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", (sqrt(1.0)));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", tan(1.0));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", tanh(1.0));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", j0(1.0));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", j1(1.0));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", y0(1.0));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", y1(1.0));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", tgamma(1.0));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", lgamma(1.0));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", cos(((1.0) * (acos(-(1.0))) / 180.0)));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", sin(((1.0) * (acos(-(1.0))) / 180.0)));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", tan(((1.0) * (acos(-(1.0))) / 180.0)));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", ((acos(1.0)) * 180.0 / (acos(-(1.0)))));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", ((asin(1.0)) * 180.0 / (acos(-(1.0)))));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%.17g", first ? "" : " ", (((1.0) == 0) ? DBL_MIN : fabs(nextafter((1.0), ((1.0) >= 0 ? HUGE_VAL : -HUGE_VAL)) - (1.0))));
      first = 0;
      printf("\n");
   }
   return 0;
}
