/* Generated by xf2c.py from xgoto_spellings.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   int i = 1;
   goto xf2c_stmt_100;
   i = 2;
   xf2c_stmt_100: ;
   {
      int first = 1;
      printf("%s%d", first ? "" : " ", i);
      first = 0;
      printf("\n");
   }
   goto xf2c_stmt_200;
   i = 3;
   xf2c_stmt_200: ;
   {
      int first = 1;
      printf("%s%d", first ? "" : " ", i);
      first = 0;
      printf("\n");
   }
   return 0;
}
