/* Generated by xf2c.py from xgoto.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"

void write_sample_input(const char * filename);
void process_file(const char * input_file, const char * output_file);

void write_sample_input(const char * filename) {
   int unit = alloc_unit();
   if (open_unit(unit, trim_s(filename), "write", "replace") != 0) return;
   if (write_first_int_unit(unit, 5) != 0) return;
   if (write_first_float_unit(unit, 1.0) != 0) return;
   if (write_first_float_unit(unit, 2.0) != 0) return;
   if (write_first_float_unit(unit, 3.0) != 0) return;
   if (write_first_float_unit(unit, 4.0) != 0) return;
   if (write_first_float_unit(unit, 5.0) != 0) return;
   close_unit(unit);
}

void process_file(const char * input_file, const char * output_file) {
   int unit_in, unit_out, ios, n, i, ierr, n_x = 0, n_y = 0, in_open, out_open;
   float *x = NULL, *y = NULL;
   ierr = 0;
   in_open = 0;
   out_open = 0;
   unit_in = alloc_unit();
   ios = open_unit(unit_in, trim_s(input_file), "read", "old");
   if (ios != 0) {
      printf("%s", "error: could not open input file");
      printf("\n");
      ierr = 1;
      goto xf2c_stmt_900;
   }
   in_open = 1;
   unit_out = alloc_unit();
   ios = open_unit(unit_out, trim_s(output_file), "write", "replace");
   if (ios != 0) {
      printf("%s", "error: could not open output file");
      printf("\n");
      ierr = 1;
      goto xf2c_stmt_900;
   }
   out_open = 1;
   ios = read_first_int_unit(unit_in, &n);
   if (ios != 0 || n <= 0) {
      printf("%s", "error: invalid array size in input file");
      printf("\n");
      ierr = 1;
      goto xf2c_stmt_900;
   }
   if (x) free(x);
   x = (float*) malloc(sizeof(float) * n);
   if (!x && n > 0) return;
   n_x = n;
   /* unsupported: allocate(x(n), stat=ios) */
   if (ios != 0) {
      printf("%s", "error: allocation failed for x");
      printf("\n");
      ierr = 1;
      goto xf2c_stmt_900;
   }
   if (y) free(y);
   y = (float*) malloc(sizeof(float) * n);
   if (!y && n > 0) return;
   n_y = n;
   /* unsupported: allocate(y(n), stat=ios) */
   if (ios != 0) {
      printf("%s", "error: allocation failed for y");
      printf("\n");
      ierr = 1;
      goto xf2c_stmt_900;
   }
   i = 1;
   while (i <= n) {
      ios = read_first_float_unit(unit_in, &(x[i - 1]));
      if (ios != 0) {
         printf("%s", "error: failed reading value ");
         printf("%d", i);
         printf("\n");
         ierr = 1;
         goto xf2c_stmt_900;
      }
      i += 1;
   }
   if (y) free(y);
   y = (float*) malloc(sizeof(float) * n_x);
   if (!y && n_x > 0) return;
   n_y = n_x;
   for (int p_fill = 0; p_fill < n_x; ++p_fill) {
      y[p_fill] = x[p_fill] * x[p_fill];
   }
   write_a(unit_out, " i        x         x^2");
   i = 1;
   while (i <= n) {
      /* unsupported: write(unit_out, "(i3,2f10.3)") i, x(i), y(i) */
      i += 1;
   }
   printf("%s", "wrote output to squares.txt");
   printf("\n");
   xf2c_stmt_900: ;
   if ((y != NULL)) {
      if (y) free(y);
      y = NULL;
      n_y = 0;
   }
   if ((x != NULL)) {
      if (x) free(x);
      x = NULL;
      n_x = 0;
   }
   if (out_open) {
      close_unit(unit_out);
   }
   if (in_open) {
      close_unit(unit_in);
   }
   if (ierr != 0) {
      fprintf(stderr, "%s\n", "processing failed");
      exit(1);
   }
}

int main(void) {
   write_sample_input("numbers.txt");
   process_file("numbers.txt", "squares.txt");
   return 0;
}
