/* Generated by xf2c.py from xif.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   int print_debug = 1, nrow = 3, ncol = 5;
   if (print_debug) {
      {
         int first = 1;
         printf("%s%s", first ? "" : " ", "nrow, ncol=");
         first = 0;
         printf("%s%d", first ? "" : " ", nrow);
         first = 0;
         printf("%s%d", first ? "" : " ", ncol);
         first = 0;
         printf("\n");
      }
   }
   return 0;
}
