/* Generated by xf2c.py from xif_error_stop.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   int ios = 1;
   if (ios != 0) {
      fprintf(stderr, "%s\n", "cannot open input file");
      return 1;
   }
   return 0;
}
