/* Generated by xf2c.py from xif_print_fmt.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   const double x = 2.5;
   if ((2.5) != 1.0e0) {
      printf("%s", "x=");
      printf("%.1f", (2.5));
      printf("\n");
   }
   return 0;
}
