/* Generated by xf2c.py from ximpure_elemental.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

static void fill_rand_2d_float(const int n1, const int n2, float *x) {
   for (int i = 0; i < n1 * n2; ++i) x[i] = (float)rand() / (float)RAND_MAX;
}

void sub(const float x);
void add(const float x, const float y);

void sub(const float x) {
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", x);
      first = 0;
      printf("%s%13.6f", first ? "" : " ", (sqrtf(x)));
      first = 0;
      printf("\n");
   }
}

void add(const float x, const float y) {
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", x);
      first = 0;
      printf("%s%s", first ? "" : " ", " + ");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", y);
      first = 0;
      printf("%s%s", first ? "" : " ", " = ");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", x + y);
      first = 0;
      printf("\n");
   }
}

int main(void) {
   srand(1);
   float *x = NULL, *y = NULL;
   x = (float*) malloc(sizeof(float) * 12);
   if (!x) return 1;
   y = (float*) malloc(sizeof(float) * 12);
   if (!y) return 1;
   {
   float elem_arr_0[] = {0.0, 1.0, 2.0, 4.0};
   for (int i_el = 0; i_el < 4; ++i_el) {
      sub(elem_arr_0[i_el]);
   }
   }
   {
   float elem_arr_1[] = {50.0, 60.0};
   for (int i_el = 0; i_el < 2; ++i_el) {
      add(10.0, elem_arr_1[i_el]);
   }
   }
   {
   float elem_arr_0[] = {10.0, 20.0};
   float elem_arr_1[] = {50.0, 60.0};
   for (int i_el = 0; i_el < 2; ++i_el) {
      add(elem_arr_0[i_el], elem_arr_1[i_el]);
   }
   }
   fill_rand_2d_float(3, 4, x);
   fill_rand_2d_float(3, 4, y);
   {
   for (int i_el = 0; i_el < 12; ++i_el) {
      add(x[i_el], y[i_el]);
   }
   }
   free(x);
   free(y);
   return 0;
}
