/* Generated by xf2c.py from xinquire.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"

int main(void) {
   const char *fname = "demo_inquire.txt";
   int u, ios, ex, op;
   char name[257] = "", access[21] = "", form[21] = "", action[21] = "";
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "before file exists:");
      first = 0;
      printf("\n");
   }
   inquire_file_info(trim_s(fname), &ex, &op, name, 256);
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "  exist  =");
      first = 0;
      printf("%s%s", first ? "" : " ", ex ? "T" : "F");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "  opened =");
      first = 0;
      printf("%s%s", first ? "" : " ", op ? "T" : "F");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "  name   = [");
      first = 0;
      printf("%s%s", first ? "" : "", trim_s(name));
      first = 0;
      printf("%s%s", first ? "" : "", "]");
      first = 0;
      printf("\n");
   }
   u = alloc_unit();
   ios = open_unit(u, trim_s(fname), "readwrite", "replace");
   if (ios != 0) {
      fprintf(stderr, "%s\n", "open failed");
      return 1;
   }
   write_a(u, "hello");
   printf("\n");
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "after file exists and is open:");
      first = 0;
      printf("\n");
   }
   inquire_file_info(trim_s(fname), &ex, &op, name, 256);
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "  exist  =");
      first = 0;
      printf("%s%s", first ? "" : " ", ex ? "T" : "F");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "  opened =");
      first = 0;
      printf("%s%s", first ? "" : " ", op ? "T" : "F");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "  name   = [");
      first = 0;
      printf("%s%s", first ? "" : "", trim_s(name));
      first = 0;
      printf("%s%s", first ? "" : "", "]");
      first = 0;
      printf("\n");
   }
   printf("\n");
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "inquire on open unit:");
      first = 0;
      printf("\n");
   }
   inquire_unit_info(u, &op, name, 256, access, 20, form, 20, action, 20);
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "  opened =");
      first = 0;
      printf("%s%s", first ? "" : " ", op ? "T" : "F");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "  name   = [");
      first = 0;
      printf("%s%s", first ? "" : "", trim_s(name));
      first = 0;
      printf("%s%s", first ? "" : "", "]");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "  access = [");
      first = 0;
      printf("%s%s", first ? "" : "", trim_s(access));
      first = 0;
      printf("%s%s", first ? "" : "", "]");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "  form   = [");
      first = 0;
      printf("%s%s", first ? "" : "", trim_s(form));
      first = 0;
      printf("%s%s", first ? "" : "", "]");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "  action = [");
      first = 0;
      printf("%s%s", first ? "" : "", trim_s(action));
      first = 0;
      printf("%s%s", first ? "" : "", "]");
      first = 0;
      printf("\n");
   }
   close_unit(u);
   return 0;
}
