/* Generated by xf2c.py from xinterface.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"

float twice_real_scalar(const float x);
float *twice_real_vec(const int n, const float *x);
char * twice_char_scalar(const char * x);
char * *twice_char_vec(const int n, char **x);

float twice_real_scalar(const float x) {
   float x2 = 2 * x;
   return x2;
}

float *twice_real_vec(const int n, const float *x) {
   /* n: extent of x (dimension 1) */
   float *x2 = (float*) malloc(sizeof(float) * n);
   if (!x2) return NULL;
   for (int p_fill = 0; p_fill < n; ++p_fill) {
      x2[p_fill] = 2 * x[p_fill];
   }
   return x2;
}

char * twice_char_scalar(const char * x) {
   char * x2 = concat_s2(x, x);
   return x2;
}

char * *twice_char_vec(const int n, char **x) {
   /* n: extent of x (dimension 1) */
   char * *x2 = (char **) malloc(sizeof(char *) * n);
   if (!x2) return NULL;
   for (int i_fill = 0; i_fill < n; ++i_fill) x2[i_fill] = NULL;
   for (int p_fill = 0; p_fill < n; ++p_fill) {
      x2[p_fill] = concat_s2(x[p_fill], x[p_fill]);
   }
   return x2;
}

int main(void) {
   {
      int first_pr = 1;
      printf("%s%13.6f", first_pr ? "" : " ", twice_real_scalar(3.2));
      first_pr = 0;
      float *arr_call_1 = twice_real_vec(2, ((float[]){10.0, 20.0}));
      for (int i_pr = 0; i_pr < 2; ++i_pr) {
         printf("%s%g", first_pr ? "" : " ", arr_call_1[i_pr]);
         first_pr = 0;
      }
      free(arr_call_1);
      printf("%s%s", first_pr ? "" : " ", twice_char_scalar("abc"));
      first_pr = 0;
      printf("\n");
   }
   {
      char * *arr_call_0 = twice_char_vec(2, ((char *[]){"ab", "cd"}));
      for (int i_pr = 0; i_pr < 2; ++i_pr) printf("%s", arr_call_0[i_pr]);
      printf("\n");
      if (arr_call_0) free_str_array(arr_call_0, 2);
   }
   return 0;
}
