/* Generated by xf2c.py from xinternal_read_csv.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"


int main(void) {
   enum { line_len = 64 };
   char line[line_len + 1] = "";
   char **fields = NULL;
   int n_fields = 0, ios;
   double x, y;
   if (fields) free_str_array(fields, n_fields);
   fields = (char**) malloc(sizeof(char*) * 3);
   if (!fields && 3 > 0) return 1;
   for (int i_fill = 0; i_fill < 3; ++i_fill) fields[i_fill] = NULL;
   n_fields = 3;
   for (int i_fill = 0; i_fill < 3; ++i_fill) assign_str_alloc(&fields[i_fill], "");
   assign_str(line, line_len, "2003-04-14,61.378151,18.64402");
   {
   char *arg_str_0 = copy_str_s(trim_s(line));
      split_csv_line(arg_str_0, n_fields, fields);
   if (arg_str_0) free(arg_str_0);
   }
   ios = read_first_double_s(fields[1], &x);
   ios = read_first_double_s(fields[2], &y);
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", x);
      first = 0;
      printf("%s%13.6f", first ? "" : " ", y);
      first = 0;
      printf("\n");
   }
   free_str_array(fields, n_fields);
   return 0;
}
