/* Generated by xf2c.py from xinternal_sub.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

void foo(const float x);
void sub(const float x);

void foo(const float x) {
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "x =");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", x);
      first = 0;
      printf("\n");
   }
}

void sub(const float x) {
   foo(x);
}

int main(void) {
   sub(2.3);
   return 0;
}
