/* Generated by xf2c.py from xinteger_division.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   {
      int ctor_0[] = {3, 4, 5, 6};
      for (int i_pr = 0; i_pr < 4; ++i_pr) {
         printf("%12d", ctor_0[i_pr]/2);
      }
      printf("\n");
   }
   return 0;
}
