/* Generated by xf2c.py from xinterface_dummy.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

void outer(const int n, const int n_x, float *x, void (*fcn)(const int n, const int n_x, float *x));

void outer(const int n, const int n_x, float *x, void (*fcn)(const int n, const int n_x, float *x)) {
   /* n_x: extent of x (dimension 1) */
   /* unsupported: interface */
   /* unsupported: subroutine fcn(n, x) */
   /* unsupported: end subroutine fcn */
   /* unsupported: end interface */
   fcn(n, n_x, x);
}
