/* Generated by xf2c.py from xiostat.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"

int main(void) {
   int i, ierr;
   enum { text_len = 10 };
   char text[text_len + 1] = "";
   assign_str(text, text_len, "345");
   ierr = read_first_int_s(text, &i);
   if (ierr != 0) {
      {
         int first = 1;
         printf("%s%s", first ? "" : " ", "ierr =");
         first = 0;
         printf("%s%d", first ? "" : " ", ierr);
         first = 0;
         printf("\n");
      }
   }
   else {
      {
         int first = 1;
         printf("%s%s", first ? "" : " ", "i =");
         first = 0;
         printf("%s%d", first ? "" : " ", i);
         first = 0;
         printf("\n");
      }
   }
   return 0;
}
