/* Generated by xf2c.py from xjf.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   {
      for (int j = 5; j <= 8; ++j) {
         for (int i = 2; i <= 4; ++i) {
            printf("%d", i);
            printf("%s", " ");
            printf("%d", j);
            printf("%s", " ");
            printf("%d", i + j);
            printf("%s", " ");
         }
      }
      printf("\n");
   }
   return 0;
}
