/* Generated by xf2c.py from xloc.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"

int main(void) {
   enum { n1 = 3 };
   enum { n2 = 5 };
   double *x = NULL;
   double xmean, xsd;
   int i;
   int *imat = NULL;
   x = (double*) malloc(sizeof(double) * 15);
   if (!x) return 1;
   imat = (int*) malloc(sizeof(int) * 15);
   if (!imat) return 1;
   rng_seed(42);
   i = 0;
   while (i < 5) {
      fill_runif_1d(3, &x[3 * i]);
      i += 1;
   }
   for (int i_fill = 0; i_fill < 15; ++i_fill) {
      imat[i_fill] = ((int) lround(5 * x[i_fill]));
   }
   i = 0;
   while (i < 3) {
      for (int j_fmt = 0; j_fmt < 5; ++j_fmt) {
         printf("%4d", imat[i + 3 * j_fmt]);
      }
      printf("\n");
      i += 1;
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "minloc(imat):");
      first = 0;
      int loc = 0, best = imat[0];
      for (int i_pr = 1; i_pr < 15; ++i_pr) {
         if (imat[i_pr] < best || (0 && (imat[i_pr] == best))) { best = imat[i_pr]; loc = i_pr; }
      }
      printf("%s%d", first ? "" : " ", ((loc % 3) + 1));
      first = 0;
      printf("%s%d", first ? "" : " ", ((loc / 3) + 1));
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "maxloc(imat):");
      first = 0;
      int loc = 0, best = imat[0];
      for (int i_pr = 1; i_pr < 15; ++i_pr) {
         if (imat[i_pr] > best || (0 && (imat[i_pr] == best))) { best = imat[i_pr]; loc = i_pr; }
      }
      printf("%s%d", first ? "" : " ", ((loc % 3) + 1));
      first = 0;
      printf("%s%d", first ? "" : " ", ((loc / 3) + 1));
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "minloc(imat, dim=1):");
      first = 0;
      for (int j_pr = 0; j_pr < 5; ++j_pr) {
         int locv = 0, best = imat[3 * j_pr];
         for (int i_pr = 1; i_pr < 3; ++i_pr) {
            if (imat[i_pr + 3 * j_pr] < best || (0 && (imat[i_pr + 3 * j_pr] == best))) { best = imat[i_pr + 3 * j_pr]; locv = i_pr; }
         }
         locv += 1;
         printf("%s%d", first ? "" : " ", locv);
         first = 0;
      }
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "minloc(imat, dim=2):");
      first = 0;
      for (int i_pr = 0; i_pr < 3; ++i_pr) {
         int locv = 0, best = imat[i_pr];
         for (int j_pr = 1; j_pr < 5; ++j_pr) {
            if (imat[i_pr + 3 * j_pr] < best || (0 && (imat[i_pr + 3 * j_pr] == best))) { best = imat[i_pr + 3 * j_pr]; locv = j_pr; }
         }
         locv += 1;
         printf("%s%d", first ? "" : " ", locv);
         first = 0;
      }
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "maxloc(imat, dim=1):");
      first = 0;
      for (int j_pr = 0; j_pr < 5; ++j_pr) {
         int locv = 0, best = imat[3 * j_pr];
         for (int i_pr = 1; i_pr < 3; ++i_pr) {
            if (imat[i_pr + 3 * j_pr] > best || (0 && (imat[i_pr + 3 * j_pr] == best))) { best = imat[i_pr + 3 * j_pr]; locv = i_pr; }
         }
         locv += 1;
         printf("%s%d", first ? "" : " ", locv);
         first = 0;
      }
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "maxloc(imat, dim=2):");
      first = 0;
      for (int i_pr = 0; i_pr < 3; ++i_pr) {
         int locv = 0, best = imat[i_pr];
         for (int j_pr = 1; j_pr < 5; ++j_pr) {
            if (imat[i_pr + 3 * j_pr] > best || (0 && (imat[i_pr + 3 * j_pr] == best))) { best = imat[i_pr + 3 * j_pr]; locv = j_pr; }
         }
         locv += 1;
         printf("%s%d", first ? "" : " ", locv);
         first = 0;
      }
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "findloc(imat, 3):");
      first = 0;
      int loc = 0, found = 0;
      if (0) {
         for (int i_pr = 15 - 1; i_pr >= 0; --i_pr) {
            if (imat[i_pr] == 3) { loc = i_pr; found = 1; break; }
         }
      } else {
         for (int i_pr = 0; i_pr < 15; ++i_pr) {
            if (imat[i_pr] == 3) { loc = i_pr; found = 1; break; }
         }
      }
      printf("%s%d", first ? "" : " ", (found ? ((loc % 3) + 1) : 0));
      first = 0;
      printf("%s%d", first ? "" : " ", (found ? ((loc / 3) + 1) : 0));
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "findloc(imat, -1):");
      first = 0;
      int loc = 0, found = 0;
      if (0) {
         for (int i_pr = 15 - 1; i_pr >= 0; --i_pr) {
            if (imat[i_pr] == -1) { loc = i_pr; found = 1; break; }
         }
      } else {
         for (int i_pr = 0; i_pr < 15; ++i_pr) {
            if (imat[i_pr] == -1) { loc = i_pr; found = 1; break; }
         }
      }
      printf("%s%d", first ? "" : " ", (found ? ((loc % 3) + 1) : 0));
      first = 0;
      printf("%s%d", first ? "" : " ", (found ? ((loc / 3) + 1) : 0));
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "findloc(imat, 3, dim=1):");
      first = 0;
      for (int j_pr = 0; j_pr < 5; ++j_pr) {
         int locv = 0, found = 0;
         if (0) {
            for (int i_pr = 3 - 1; i_pr >= 0; --i_pr) {
               if (imat[i_pr + 3 * j_pr] == 3) { locv = i_pr + 1; found = 1; break; }
            }
         } else {
            for (int i_pr = 0; i_pr < 3; ++i_pr) {
               if (imat[i_pr + 3 * j_pr] == 3) { locv = i_pr + 1; found = 1; break; }
            }
         }
         printf("%s%d", first ? "" : " ", locv);
         first = 0;
      }
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "findloc(imat, 3, dim=2):");
      first = 0;
      for (int i_pr = 0; i_pr < 3; ++i_pr) {
         int locv = 0, found = 0;
         if (0) {
            for (int j_pr = 5 - 1; j_pr >= 0; --j_pr) {
               if (imat[i_pr + 3 * j_pr] == 3) { locv = j_pr + 1; found = 1; break; }
            }
         } else {
            for (int j_pr = 0; j_pr < 5; ++j_pr) {
               if (imat[i_pr + 3 * j_pr] == 3) { locv = j_pr + 1; found = 1; break; }
            }
         }
         printf("%s%d", first ? "" : " ", locv);
         first = 0;
      }
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "minloc(imat, back=.true.):");
      first = 0;
      int loc = 0, best = imat[0];
      for (int i_pr = 1; i_pr < 15; ++i_pr) {
         if (imat[i_pr] < best || (1 && (imat[i_pr] == best))) { best = imat[i_pr]; loc = i_pr; }
      }
      printf("%s%d", first ? "" : " ", ((loc % 3) + 1));
      first = 0;
      printf("%s%d", first ? "" : " ", ((loc / 3) + 1));
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "maxloc(imat, back=.true.):");
      first = 0;
      int loc = 0, best = imat[0];
      for (int i_pr = 1; i_pr < 15; ++i_pr) {
         if (imat[i_pr] > best || (1 && (imat[i_pr] == best))) { best = imat[i_pr]; loc = i_pr; }
      }
      printf("%s%d", first ? "" : " ", ((loc % 3) + 1));
      first = 0;
      printf("%s%d", first ? "" : " ", ((loc / 3) + 1));
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "minloc(imat, dim=1, back=.true.):");
      first = 0;
      for (int j_pr = 0; j_pr < 5; ++j_pr) {
         int locv = 0, best = imat[3 * j_pr];
         for (int i_pr = 1; i_pr < 3; ++i_pr) {
            if (imat[i_pr + 3 * j_pr] < best || (1 && (imat[i_pr + 3 * j_pr] == best))) { best = imat[i_pr + 3 * j_pr]; locv = i_pr; }
         }
         locv += 1;
         printf("%s%d", first ? "" : " ", locv);
         first = 0;
      }
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "minloc(imat, dim=2, back=.true.):");
      first = 0;
      for (int i_pr = 0; i_pr < 3; ++i_pr) {
         int locv = 0, best = imat[i_pr];
         for (int j_pr = 1; j_pr < 5; ++j_pr) {
            if (imat[i_pr + 3 * j_pr] < best || (1 && (imat[i_pr + 3 * j_pr] == best))) { best = imat[i_pr + 3 * j_pr]; locv = j_pr; }
         }
         locv += 1;
         printf("%s%d", first ? "" : " ", locv);
         first = 0;
      }
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "maxloc(imat, dim=1, back=.true.):");
      first = 0;
      for (int j_pr = 0; j_pr < 5; ++j_pr) {
         int locv = 0, best = imat[3 * j_pr];
         for (int i_pr = 1; i_pr < 3; ++i_pr) {
            if (imat[i_pr + 3 * j_pr] > best || (1 && (imat[i_pr + 3 * j_pr] == best))) { best = imat[i_pr + 3 * j_pr]; locv = i_pr; }
         }
         locv += 1;
         printf("%s%d", first ? "" : " ", locv);
         first = 0;
      }
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "maxloc(imat, dim=2, back=.true.):");
      first = 0;
      for (int i_pr = 0; i_pr < 3; ++i_pr) {
         int locv = 0, best = imat[i_pr];
         for (int j_pr = 1; j_pr < 5; ++j_pr) {
            if (imat[i_pr + 3 * j_pr] > best || (1 && (imat[i_pr + 3 * j_pr] == best))) { best = imat[i_pr + 3 * j_pr]; locv = j_pr; }
         }
         locv += 1;
         printf("%s%d", first ? "" : " ", locv);
         first = 0;
      }
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "findloc(imat, 3, back=.true.):");
      first = 0;
      int loc = 0, found = 0;
      if (1) {
         for (int i_pr = 15 - 1; i_pr >= 0; --i_pr) {
            if (imat[i_pr] == 3) { loc = i_pr; found = 1; break; }
         }
      } else {
         for (int i_pr = 0; i_pr < 15; ++i_pr) {
            if (imat[i_pr] == 3) { loc = i_pr; found = 1; break; }
         }
      }
      printf("%s%d", first ? "" : " ", (found ? ((loc % 3) + 1) : 0));
      first = 0;
      printf("%s%d", first ? "" : " ", (found ? ((loc / 3) + 1) : 0));
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "findloc(imat, -1, back=.true.):");
      first = 0;
      int loc = 0, found = 0;
      if (1) {
         for (int i_pr = 15 - 1; i_pr >= 0; --i_pr) {
            if (imat[i_pr] == -1) { loc = i_pr; found = 1; break; }
         }
      } else {
         for (int i_pr = 0; i_pr < 15; ++i_pr) {
            if (imat[i_pr] == -1) { loc = i_pr; found = 1; break; }
         }
      }
      printf("%s%d", first ? "" : " ", (found ? ((loc % 3) + 1) : 0));
      first = 0;
      printf("%s%d", first ? "" : " ", (found ? ((loc / 3) + 1) : 0));
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "findloc(imat, 3, dim=1, back=.true.):");
      first = 0;
      for (int j_pr = 0; j_pr < 5; ++j_pr) {
         int locv = 0, found = 0;
         if (1) {
            for (int i_pr = 3 - 1; i_pr >= 0; --i_pr) {
               if (imat[i_pr + 3 * j_pr] == 3) { locv = i_pr + 1; found = 1; break; }
            }
         } else {
            for (int i_pr = 0; i_pr < 3; ++i_pr) {
               if (imat[i_pr + 3 * j_pr] == 3) { locv = i_pr + 1; found = 1; break; }
            }
         }
         printf("%s%d", first ? "" : " ", locv);
         first = 0;
      }
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "findloc(imat, 3, dim=2, back=.true.):");
      first = 0;
      for (int i_pr = 0; i_pr < 3; ++i_pr) {
         int locv = 0, found = 0;
         if (1) {
            for (int j_pr = 5 - 1; j_pr >= 0; --j_pr) {
               if (imat[i_pr + 3 * j_pr] == 3) { locv = j_pr + 1; found = 1; break; }
            }
         } else {
            for (int j_pr = 0; j_pr < 5; ++j_pr) {
               if (imat[i_pr + 3 * j_pr] == 3) { locv = j_pr + 1; found = 1; break; }
            }
         }
         printf("%s%d", first ? "" : " ", locv);
         first = 0;
      }
      printf("\n");
   }
   free(x);
   free(imat);
   return 0;
}
