/* Generated by xf2c.py from xlogical.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"

int main(void) {
   enum { n = 3 };
   int *x = NULL;
   float y[3] = {10.0, 20.0, 30.0};
   x = (int*) malloc(sizeof(int) * 3);
   if (!x) return 1;
   x[0] = 1;
   x[1] = 0;
   x[2] = 1;
   {
      int first = 1;
      for (int i_pr = 0; i_pr < 3; ++i_pr) {
         printf("%s%s", first ? "" : " ", (x[i_pr]) ? "T" : "F");
         first = 0;
      }
      printf("\n");
   }
   {
      int first = 1;
      for (int i_pr = 0; i_pr < 3; ++i_pr) {
         if (x[i_pr]) {
            printf("%s%g", first ? "" : " ", y[i_pr]);
            first = 0;
         }
      }
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", sum_1d_float(3, y));
      first = 0;
      printf("\n");
   }
   {
      float sum = 0;
      for (int i_pr = 0; i_pr < 3; ++i_pr) {
         if (x[i_pr]) sum += y[i_pr];
      }
      printf("%g\n", sum);
   }
   {
      float sum = 0;
      for (int i_pr = 0; i_pr < 3; ++i_pr) {
         if (x[i_pr]) sum += (y[i_pr] * y[i_pr]);
      }
      printf("%g\n", sum);
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", (1 == 1) ? "T" : "F");
      first = 0;
      printf("%s%s", first ? "" : " ", (1 == 0) ? "T" : "F");
      first = 0;
      printf("\n");
   }
   free(x);
   return 0;
}
