/* Generated by xf2c.py from xmaxloc.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   float x[3] = {10.0, 30.0, 20.0};
   int *i = NULL;
   i = (int*) malloc(sizeof(int));
   if (!i) return 1;
   {
      int loc = 0, i_pr = 0;
      float best = x[i_pr];
      for (i_pr = 1; i_pr < 3; ++i_pr) {
         if (x[i_pr] > best || (0 && (x[i_pr] == best))) { best = x[i_pr]; loc = i_pr; }
      }
   i[0] = loc + 1;
   }
   {
      for (int i_pr = 0; i_pr < 1; ++i_pr) {
         printf("%12d", i[i_pr]);
      }
      printf("\n");
   }
   {
      int loc = 0, i_pr = 0;
      float best = x[i_pr];
      for (i_pr = 1; i_pr < 3; ++i_pr) {
         if (x[i_pr] > best || (0 && (x[i_pr] == best))) { best = x[i_pr]; loc = i_pr; }
      }
   i[0] = loc + 1;
   }
   {
      for (int i_pr = 0; i_pr < 1; ++i_pr) {
         printf("%12d", i[i_pr]);
      }
      printf("\n");
   }
   free(i);
   return 0;
}
