/* Generated by xf2c.py from xmerge.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   int v[3] = {4, 9, 16};
   int w[3] = {100, 200, 300};
   {
      for (int i_pr = 0; i_pr < 3; ++i_pr) {
         printf("%12d", ((v[i_pr] > 5) ? 10 : 20));
      }
      printf("\n");
   }
   {
      for (int i_pr = 0; i_pr < 3; ++i_pr) {
         printf("%12d", ((v[i_pr] > 5) ? 10 : (w[i_pr])));
      }
      printf("\n");
   }
   {
      for (int i_pr = 0; i_pr < 3; ++i_pr) {
         printf("%12d", 10);
      }
      printf("\n");
   }
   {
      for (int i_pr = 0; i_pr < 3; ++i_pr) {
         printf("%12d", w[i_pr]);
      }
      printf("\n");
   }
   {
      for (int i_pr = 0; i_pr < 3; ++i_pr) {
         printf("%12d", ((v[i_pr] > 5) ? (w[i_pr]) : (10 * w[i_pr])));
      }
      printf("\n");
   }
   return 0;
}
