/* Generated by xf2c.py from xmodule_param.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

const float two = 2.0;

float twice(const float x);

float twice(const float x) {
   float result = 2.0 * x;
   return result;
}

int main(void) {
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", twice(3.2));
      first = 0;
      printf("\n");
   }
   return 0;
}
