/* Generated by xf2c.py from xmodulo.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   int a, p;
   a = -7;
   p = 3;
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "a =");
      first = 0;
      printf("%s%d", first ? "" : " ", a);
      first = 0;
      printf("%s%s", first ? "" : " ", " p =");
      first = 0;
      printf("%s%d", first ? "" : " ", p);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "mod(a,p)    =");
      first = 0;
      printf("%s%d", first ? "" : " ", ((a % p)));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "modulo(a,p) =");
      first = 0;
      printf("%s%d", first ? "" : " ", (((((a % p))) != 0 && (((((a % p))) < 0) != (p < 0))) ? ((((a % p))) + p) : (((a % p)))));
      first = 0;
      printf("\n");
   }
   a = 7;
   p = -3;
   printf("\n");
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "a =");
      first = 0;
      printf("%s%d", first ? "" : " ", a);
      first = 0;
      printf("%s%s", first ? "" : " ", " p =");
      first = 0;
      printf("%s%d", first ? "" : " ", p);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "mod(a,p)    =");
      first = 0;
      printf("%s%d", first ? "" : " ", ((a % p)));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "modulo(a,p) =");
      first = 0;
      printf("%s%d", first ? "" : " ", (((((a % p))) != 0 && (((((a % p))) < 0) != (p < 0))) ? ((((a % p))) + p) : (((a % p)))));
      first = 0;
      printf("\n");
   }
   return 0;
}
