/* Generated by xf2c.py from xmove_alloc.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

static int argext_append_value_x = 0;

void append_value(int **x__arg, const int val);

void append_value(int **x__arg, const int val) {
   #define x (*x__arg)
   int n_x = argext_append_value_x;
   int *temp = NULL;
   int n_temp = 0, n;
   if ((x != NULL)) {
      n = n_x;
      if (temp) free(temp);
      temp = (int*) malloc(sizeof(int) * (n + 1));
      if (!temp && (n + 1) > 0) return;
      n_temp = n + 1;
      if (1 > 0) {
         for (int i_fill = 1, p_fill = 0; p_fill < n_x; i_fill += 1, ++p_fill) {
            temp[i_fill - 1] = x[p_fill];
         }
      } else {
         for (int i_fill = 1, p_fill = 0; p_fill < n_x; i_fill += 1, ++p_fill) {
            temp[i_fill - 1] = x[p_fill];
         }
      }
   }
   else {
      n = 0;
      if (temp) free(temp);
      temp = (int*) malloc(sizeof(int));
      if (!temp && 1 > 0) return;
      n_temp = 1;
   }
   temp[n] = val;
   if (x) free(x);
   x = temp;
   n_x = n_temp;
   temp = NULL;
   n_temp = 0;
   argext_append_value_x = n_x;
   #undef x
}

int main(void) {
   int *a = NULL, *b = NULL;
   int n_a = 0, n_b = 0, i;
   if (a) free(a);
   a = (int*) malloc(sizeof(int) * 5);
   if (!a && 5 > 0) return 1;
   n_a = 5;
   i = 1;
   while (i <= n_a) {
      a[i - 1] = 10 * i;
      i += 1;
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "initial state");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "allocated(a) =");
      first = 0;
      printf("%s%s", first ? "" : " ", ((a != NULL)) ? "T" : "F");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "allocated(b) =");
      first = 0;
      printf("%s%s", first ? "" : " ", ((b != NULL)) ? "T" : "F");
      first = 0;
      printf("\n");
   }
   {
      int first_pr = 1;
      printf("%s%s", first_pr ? "" : " ", "a =");
      first_pr = 0;
      for (int i_pr = 0; i_pr < n_a; ++i_pr) {
         printf("%s%d", first_pr ? "" : " ", a[i_pr]);
         first_pr = 0;
      }
      printf("\n");
   }
   printf("\n");
   if (b) free(b);
   b = a;
   n_b = n_a;
   a = NULL;
   n_a = 0;
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "after call move_alloc(a, b)");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "allocated(a) =");
      first = 0;
      printf("%s%s", first ? "" : " ", ((a != NULL)) ? "T" : "F");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "allocated(b) =");
      first = 0;
      printf("%s%s", first ? "" : " ", ((b != NULL)) ? "T" : "F");
      first = 0;
      printf("\n");
   }
   {
      int first_pr = 1;
      printf("%s%s", first_pr ? "" : " ", "b =");
      first_pr = 0;
      for (int i_pr = 0; i_pr < n_b; ++i_pr) {
         printf("%s%d", first_pr ? "" : " ", b[i_pr]);
         first_pr = 0;
      }
      printf("\n");
   }
   printf("\n");
   if (a) free(a);
   a = (int*) malloc(sizeof(int) * 3);
   if (!a && 3 > 0) return 1;
   n_a = 3;
   if (a) free(a);
   a = (int*) malloc(sizeof(int) * 3);
   if (!a && 3 > 0) return 1;
   n_a = 3;
   a[0] = 1;
   a[1] = 2;
   a[2] = 3;
   printf("%s\n", "reallocate a");
   {
      int first_pr = 1;
      printf("%s%s", first_pr ? "" : " ", "a =");
      first_pr = 0;
      for (int i_pr = 0; i_pr < n_a; ++i_pr) {
         printf("%s%d", first_pr ? "" : " ", a[i_pr]);
         first_pr = 0;
      }
      printf("\n");
   }
   printf("\n");
   {
   argext_append_value_x = n_a;
      append_value(&a, 99);
   n_a = argext_append_value_x;
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "after append_value(a, 99)");
      first = 0;
      printf("\n");
   }
   {
      int first_pr = 1;
      printf("%s%s", first_pr ? "" : " ", "a =");
      first_pr = 0;
      for (int i_pr = 0; i_pr < n_a; ++i_pr) {
         printf("%s%d", first_pr ? "" : " ", a[i_pr]);
         first_pr = 0;
      }
      printf("\n");
   }
   free(a);
   free(b);
   return 0;
}
