/* Generated by xf2c.py from xmt.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

const long long nn = 312;
const long long mm = 156;
const long long seed_def = 5489;
const long long matrix_a = -5403634167711393303;
const long long um = -2147483648;
const long long lm = 2147483647;
const double pi253_1 = 1.0/(pow(2.0, 53) - 1.0);
const double pi253 = 1.0/(pow(2.0, 53));
const double pi252 = 1.0/(pow(2.0, 52));

typedef struct {
   long long mt[312];
   int mti;
} mt19937;

void init_genrand64_i4(mt19937 *me, const int seed); /* ! Initializes `me%mt(nn)` with a seed */
void init_genrand64(mt19937 *me, const long long seed); /* ! Initializes `me%mt(nn)` with a seed */
void init_by_array64(mt19937 *me, const int n, const long long *init_key); /* ! Initializes by an array with array-length */
long long genrand64_int64(mt19937 * me); /* ! Generates a random number on [-2^63, 2^63-1]-interval */
double genrand64_real1(mt19937 * me); /* ! Generates a random number on [0,1]-real-interval */
double genrand64_real2(mt19937 * me); /* ! Generates a random number on [0,1)-real-interval */
double genrand64_real3(mt19937 * me); /* ! Generates a random number on (0,1)-real-interval */

void init_genrand64_i4(mt19937 *me, const int seed) {
   /* ! Initializes `me%mt(nn)` with a seed */
   init_genrand64(me, ((int) seed));
}

void init_genrand64(mt19937 *me, const long long seed) {
   /* ! Initializes `me%mt(nn)` with a seed */
   int i;
   me->mt[0] = seed;
   i = 1;
   while (i <= 311) {
      me->mt[i] = 6364136223846793005 * (((me->mt[i - 1]) ^ (((long long) ((unsigned long long) (me->mt[i - 1]) >> 62))))) + i;
      i += 1;
   }
   me->mti = 312;
}

void init_by_array64(mt19937 *me, const int n, const long long *init_key) {
   /* ! Initializes by an array with array-length */
   /* n: extent of init_key (dimension 1) */
   const long long c1 = 3935559000370003845;
   const long long c2 = 2862933555777941757;
   long long i, j, k, kk, key_length;
   init_genrand64(me, 19650218);
   key_length = n;
   i = 1;
   j = 0;
   k = fmax(312, key_length);
   kk = 0;
   while (kk < k) {
      me->mt[i] = (((me->mt[i]) ^ (3935559000370003845 * (((me->mt[i - 1]) ^ (((long long) ((unsigned long long) (me->mt[i - 1]) >> 62)))))))) + init_key[j] + j;
      i += 1;
      j += 1;
      if (i >= 312) {
         me->mt[0] = me->mt[311];
         i = 1;
      }
      if (j >= key_length) {
         j = 0;
      }
      kk += 1;
   }
   kk = 0;
   while (kk < 311) {
      me->mt[i] = (((me->mt[i]) ^ (2862933555777941757 * (((me->mt[i - 1]) ^ (((long long) ((unsigned long long) (me->mt[i - 1]) >> 62)))))))) - i;
      i += 1;
      if (i >= 312) {
         me->mt[0] = me->mt[311];
         i = 1;
      }
      kk += 1;
   }
   /* MSB is 1; assuring non-zero initial array */
   me->mt[0] = ((long long) ((unsigned long long) 1 << 63));
}

long long genrand64_int64(mt19937 * me) {
   /* ! Generates a random number on [-2^63, 2^63-1]-interval */
   long long result;
   const long long mag01[2] = {0, -5403634167711393303};
   long long x;
   int i;
   /* generate nn words at one time */
   if (me->mti >= 312) {
      if (me->mti == 312 + 1) {
         init_genrand64(me, 5489);
      }
      i = 1;
      while (i <= 156) {
         x = ((((((me->mt[i - 1]) & -2147483648))) | ((((me->mt[i]) & 2147483647)))));
         me->mt[i - 1] = ((((((me->mt[i + 155]) ^ (((long long) ((unsigned long long) x >> 1)))))) ^ (mag01[(((x & 1)) - 0)])));
         i += 1;
      }
      i = 157;
      while (i <= 311) {
         x = ((((((me->mt[i - 1]) & -2147483648))) | ((((me->mt[i]) & 2147483647)))));
         me->mt[i - 1] = ((((((me->mt[i - 157]) ^ (((long long) ((unsigned long long) x >> 1)))))) ^ (mag01[(((x & 1)) - 0)])));
         i += 1;
      }
      x = ((((((me->mt[311]) & -2147483648))) | ((((me->mt[0]) & 2147483647)))));
      me->mt[311] = ((((((me->mt[155]) ^ (((long long) ((unsigned long long) x >> 1)))))) ^ (mag01[(((x & 1)) - 0)])));
      me->mti = 0;
   }
   me->mti = me->mti + 1;
   x = me->mt[(me->mti - 1)];
   x = (((x) ^ ((((((long long) ((unsigned long long) x >> 29))) & 6148914691236517205)))));
   x = (((x) ^ ((((((long long) ((unsigned long long) x << 17))) & 8202884508482404352)))));
   x = (((x) ^ ((((((long long) ((unsigned long long) x << 37))) & -2270628950310912)))));
   x = (((x) ^ (((long long) ((unsigned long long) x >> 43)))));
   result = x;
   return result;
}

double genrand64_real1(mt19937 * me) {
   /* ! Generates a random number on [0,1]-real-interval */
   double result = ((double) (((long long) ((unsigned long long) (genrand64_int64(me)) >> 11)))) * (1.0/(pow(2.0, 53) - 1.0));
   return result;
}

double genrand64_real2(mt19937 * me) {
   /* ! Generates a random number on [0,1)-real-interval */
   double result = ((double) (((long long) ((unsigned long long) (genrand64_int64(me)) >> 11)))) * (1.0/(pow(2.0, 53)));
   return result;
}

double genrand64_real3(mt19937 * me) {
   /* ! Generates a random number on (0,1)-real-interval */
   double result = ((double) (((long long) ((unsigned long long) (genrand64_int64(me)) >> 12))));
   result = (result + 0.5) * (1.0/(pow(2.0, 52)));
   return result;
}

int main(void) {
   mt19937 rng = {0};
   /* unsupported: use, intrinsic :: iso_fortran_env, only: int64 */
   init_genrand64(&rng, 42);
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", genrand64_real2(&rng));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", genrand64_real2(&rng));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", genrand64_real2(&rng));
      first = 0;
      printf("\n");
   }
   return 0;
}
