/* Generated by xf2c.py from xmt_runif.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"

static int ret_runif_1d_n = 0;


int main(void) {
   double *x = NULL, *y = NULL;
   int n_x = 0;
   y = (double*) malloc(sizeof(double) * 3);
   if (!y) return 1;
   rng_seed(42);
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", runif());
      first = 0;
      printf("\n");
   }
   if (x) free(x);
   x = (double*) malloc(sizeof(double) * 3);
   if (!x && 3 > 0) return 1;
   n_x = 3;
   fill_runif_1d(3, x);
   {
      int first = 1;
      for (int i_pr = 0; i_pr < n_x; ++i_pr) {
         if (first) printf("%13.6f", x[i_pr]);
         else printf("    %13.6f", x[i_pr]);
         first = 0;
      }
      printf("    \n");
   }
   fill_runif_1d(3, y);
   {
      int first = 1;
      for (int i_pr = 0; i_pr < 3; ++i_pr) {
         if (first) printf("%13.6f", y[i_pr]);
         else printf("    %13.6f", y[i_pr]);
         first = 0;
      }
      printf("    \n");
   }
   free(x);
   free(y);
   return 0;
}
