/* Generated by xf2c.py from xnint.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   const float x[6] = {-0.7, -0.5, -0.3, 0.1, 0.5, 0.7};
   for (int i_pr = 0; i_pr < 6; ++i_pr) {
      printf("%d%s", ((int) lround(x[i_pr])), (i_pr + 1 < 6) ? " " : "\n");
   }
   for (int i_pr = 0; i_pr < 6; ++i_pr) {
      printf("%g%s", (roundf(x[i_pr])), (i_pr + 1 < 6) ? " " : "\n");
   }
   for (int i_pr = 0; i_pr < 6; ++i_pr) {
      printf("%g%s", (truncf(x[i_pr])), (i_pr + 1 < 6) ? " " : "\n");
   }
   for (int i_pr = 0; i_pr < 6; ++i_pr) {
      printf("%d%s", ((int) (ceilf(x[i_pr]))), (i_pr + 1 < 6) ? " " : "\n");
   }
   for (int i_pr = 0; i_pr < 6; ++i_pr) {
      printf("%d%s", ((int) (floorf(x[i_pr]))), (i_pr + 1 < 6) ? " " : "\n");
   }
   return 0;
}
