/* Generated by xf2c.py from xnumeric.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   float xsp;
   double xdp;
   int i_small;
   long long i_big;
   xsp = 1.0;
   xdp = 1.0;
   i_small = 123;
   i_big = 123;
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "selected kind values");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "sp =");
      first = 0;
      printf("%s%d", first ? "" : " ", 4);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "dp =");
      first = 0;
      printf("%s%d", first ? "" : " ", 8);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "i4 =");
      first = 0;
      printf("%s%d", first ? "" : " ", 4);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "i8 =");
      first = 0;
      printf("%s%d", first ? "" : " ", 8);
      first = 0;
      printf("\n");
   }
   printf("\n");
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "real inquiry functions for single precision");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "digits(xsp)      =");
      first = 0;
      printf("%s%d", first ? "" : " ", FLT_MANT_DIG);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "epsilon(xsp)     =");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", FLT_EPSILON);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "huge(xsp)        =");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", FLT_MAX);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "tiny(xsp)        =");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", FLT_MIN);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "maxexponent(xsp) =");
      first = 0;
      printf("%s%d", first ? "" : " ", FLT_MAX_EXP);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "minexponent(xsp) =");
      first = 0;
      printf("%s%d", first ? "" : " ", FLT_MIN_EXP);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "precision(xsp)   =");
      first = 0;
      printf("%s%d", first ? "" : " ", FLT_DIG);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "radix(xsp)       =");
      first = 0;
      printf("%s%d", first ? "" : " ", FLT_RADIX);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "range(xsp)       =");
      first = 0;
      printf("%s%d", first ? "" : " ", 37);
      first = 0;
      printf("\n");
   }
   printf("\n");
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "real inquiry functions for double precision");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "digits(xdp)      =");
      first = 0;
      printf("%s%d", first ? "" : " ", DBL_MANT_DIG);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "epsilon(xdp)     =");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", DBL_EPSILON);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "huge(xdp)        =");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", DBL_MAX);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "tiny(xdp)        =");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", DBL_MIN);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "maxexponent(xdp) =");
      first = 0;
      printf("%s%d", first ? "" : " ", DBL_MAX_EXP);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "minexponent(xdp) =");
      first = 0;
      printf("%s%d", first ? "" : " ", DBL_MIN_EXP);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "precision(xdp)   =");
      first = 0;
      printf("%s%d", first ? "" : " ", DBL_DIG);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "radix(xdp)       =");
      first = 0;
      printf("%s%d", first ? "" : " ", FLT_RADIX);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "range(xdp)       =");
      first = 0;
      printf("%s%d", first ? "" : " ", 307);
      first = 0;
      printf("\n");
   }
   printf("\n");
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "integer inquiry functions");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "bit_size(i_small) =");
      first = 0;
      printf("%s%d", first ? "" : " ", ((int) (sizeof(i_small) * CHAR_BIT)));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "huge(i_small)     =");
      first = 0;
      printf("%s%d", first ? "" : " ", INT_MAX);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "range(i_small)    =");
      first = 0;
      printf("%s%d", first ? "" : " ", 9);
      first = 0;
      printf("\n");
   }
   printf("\n");
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "bit_size(i_big)   =");
      first = 0;
      printf("%s%d", first ? "" : " ", ((int) (sizeof(i_big) * CHAR_BIT)));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "huge(i_big)       =");
      first = 0;
      printf("%s%lld", first ? "" : " ", LLONG_MAX);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "range(i_big)      =");
      first = 0;
      printf("%s%d", first ? "" : " ", 18);
      first = 0;
      printf("\n");
   }
   printf("\n");
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "nearest examples");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "xsp                =");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", xsp);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "nearest(xsp, 1.0)  =");
      first = 0;
      printf("%s%.9g", first ? "" : " ", (nextafterf(xsp, ((1.0) >= 0 ? HUGE_VALF : -HUGE_VALF))));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "nearest(xsp,-1.0)  =");
      first = 0;
      printf("%s%.9g", first ? "" : " ", (nextafterf(xsp, ((-(1.0)) >= 0 ? HUGE_VALF : -HUGE_VALF))));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "spacing(xsp)       =");
      first = 0;
      printf("%s%.9g", first ? "" : " ", ((xsp == 0) ? FLT_MIN : fabsf(nextafterf(xsp, (xsp >= 0 ? HUGE_VALF : -HUGE_VALF)) - xsp)));
      first = 0;
      printf("\n");
   }
   printf("\n");
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "xdp                =");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", xdp);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "nearest(xdp, 1.0)  =");
      first = 0;
      printf("%s%.17g", first ? "" : " ", (nextafter(xdp, ((1.0) >= 0 ? HUGE_VAL : -HUGE_VAL))));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "nearest(xdp,-1.0)  =");
      first = 0;
      printf("%s%.17g", first ? "" : " ", (nextafter(xdp, ((-(1.0)) >= 0 ? HUGE_VAL : -HUGE_VAL))));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "spacing(xdp)       =");
      first = 0;
      printf("%s%.17g", first ? "" : " ", ((xdp == 0) ? DBL_MIN : fabs(nextafter(xdp, (xdp >= 0 ? HUGE_VAL : -HUGE_VAL)) - xdp)));
      first = 0;
      printf("\n");
   }
   printf("\n");
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "exponent/set_exponent/fraction examples");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "xdp =");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", xdp);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "exponent(10.0_dp)         =");
      first = 0;
      printf("%s%d", first ? "" : " ", (((10.0) == 0) ? 0 : (ilogb(10.0) + 1)));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "fraction(10.0_dp)         =");
      first = 0;
      printf("%s%.17g", first ? "" : " ", (((10.0) == 0) ? (10.0) : (scalbn(10.0, -(ilogb(10.0) + 1)))));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "set_exponent(0.75_dp, 10) =");
      first = 0;
      printf("%s%.17g", first ? "" : " ", (((0.75) == 0) ? (0.75) : (scalbn(((((0.75) == 0) ? (0.75) : (scalbn(0.75, -(ilogb(0.75) + 1))))), 10))));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "scale(1.0_dp, 5)          =");
      first = 0;
      printf("%s%.17g", first ? "" : " ", (scalbn(1.0, 5)));
      first = 0;
      printf("\n");
   }
   printf("\n");
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "selected_real_kind failure codes");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "selected_real_kind(1000,1000) =");
      first = 0;
      printf("%s%d", first ? "" : " ", -1);
      first = 0;
      printf("\n");
   }
   printf("\n");
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "selected_int_kind failure code");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "selected_int_kind(100) =");
      first = 0;
      printf("%s%d", first ? "" : " ", -1);
      first = 0;
      printf("\n");
   }
   return 0;
}
