/* Generated by xf2c.py from xoperator.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"

int in_integer(const int u, const int n, const int *v); /* return any(u == v) for integer arguments */
int in_real64(const double u, const int n, const double *v); /* return any(u == v) for real(kind=real64) arguments */
int in_character(const char * u, const int n, char **v); /* return any(u == v) for character arguments */
int in_logical(const int u, const int n, const int *v); /* return any(u.eqv.v) for logical arguments */

int in_integer(const int u, const int n, const int *v) {
   /* return any(u == v) for integer arguments */
   /* n: extent of v (dimension 1) */
   int result = any_eq_1d_int(n, u, v);
   return result;
}

int in_real64(const double u, const int n, const double *v) {
   /* return any(u == v) for real(kind=real64) arguments */
   /* n: extent of v (dimension 1) */
   int result = any_eq_1d_double(n, u, v);
   return result;
}

int in_character(const char * u, const int n, char **v) {
   /* return any(u == v) for character arguments */
   /* n: extent of v (dimension 1) */
   int result = any_eq_1d_string(n, u, v);
   return result;
}

int in_logical(const int u, const int n, const int *v) {
   /* return any(u.eqv.v) for logical arguments */
   /* n: extent of v (dimension 1) */
   int result = any_eq_1d_int(n, u, v);
   return result;
}

int main(void) {
   int ivals[5] = {1, 3, 5, 7, 9};
   double rvals[4] = {1.0, 2.5, 4.0, 8.0};
   char names[3][6] = {"alice", "bob  ", "carol"};
   int flags[4] = {1, 0, 0, 1};
   printf("%s%s\n", "", (in_integer(5, 5, ivals)) ? "T" : "F");
   printf("%s%s\n", "", (in_integer(6, 5, ivals)) ? "T" : "F");
   printf("%s%s\n", "", (in_real64(2.5, 4, rvals)) ? "T" : "F");
   printf("%s%s\n", "", (in_real64(3.0, 4, rvals)) ? "T" : "F");
   printf("%s%s\n", "", (any_eq_1d_charbuf(3, 5, "bob", &names[0][0])) ? "T" : "F");
   printf("%s%s\n", "", (any_eq_1d_charbuf(3, 5, "dave", &names[0][0])) ? "T" : "F");
   printf("%s%s\n", "", (in_logical(1, 4, flags)) ? "T" : "F");
   printf("%s%s\n", "", (in_logical(0, 4, flags)) ? "T" : "F");
   return 0;
}
