/* Generated by xf2c.py from xpdt.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"


void show_sp(const int this_k, const int this_n, const float *this_x, const char * name);
void show_dp(const int this_k, const int this_n, const double *this_x, const char * name);

void show_sp(const int this_k, const int this_n, const float *this_x, const char * name) {
   printf("\n");
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", trim_s(name));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "  kind parameter k   =");
      first = 0;
      printf("%s%d", first ? "" : " ", this_k);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "  length parameter n =");
      first = 0;
      printf("%s%d", first ? "" : " ", this_n);
      first = 0;
      printf("\n");
   }
   {
      int first_pr = 1;
      printf("%s%s", first_pr ? "" : " ", "  values             =");
      first_pr = 0;
      for (int i_pr = 0; i_pr < this_n; ++i_pr) {
         printf("%s%g", first_pr ? "" : " ", this_x[i_pr]);
         first_pr = 0;
      }
      printf("\n");
   }
}

void show_dp(const int this_k, const int this_n, const double *this_x, const char * name) {
   printf("\n");
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", trim_s(name));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "  kind parameter k   =");
      first = 0;
      printf("%s%d", first ? "" : " ", this_k);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "  length parameter n =");
      first = 0;
      printf("%s%d", first ? "" : " ", this_n);
      first = 0;
      printf("\n");
   }
   {
      int first_pr = 1;
      printf("%s%s", first_pr ? "" : " ", "  values             =");
      first_pr = 0;
      for (int i_pr = 0; i_pr < this_n; ++i_pr) {
         printf("%s%g", first_pr ? "" : " ", this_x[i_pr]);
         first_pr = 0;
      }
      printf("\n");
   }
}

int main(void) {
   int a_k = 4, a_n = 3, b_k = 8, b_n = 5, c_k = 8, c_n = 0, n_c_x = 0, i;
   float *a_x = NULL;
   double *b_x = NULL, *c_x = NULL;
   a_x = (float*) malloc(sizeof(float) * 3);
   if (!a_x) return 1;
   b_x = (double*) malloc(sizeof(double) * 5);
   if (!b_x) return 1;
   i = 1;
   while (i <= a_n) {
      a_x[i - 1] = ((double) i);
      i += 1;
   }
   i = 1;
   while (i <= b_n) {
      b_x[i - 1] = 10.0e0 * ((double) i);
      i += 1;
   }
   c_k = 8;
   c_n = 4;
   if (c_x) free(c_x);
   c_x = (double*) malloc(sizeof(double) * c_n);
   if (!c_x && c_n > 0) return 1;
   n_c_x = c_n;
   i = 1;
   while (i <= c_n) {
      c_x[i - 1] = 100.0e0 + ((double) i);
      i += 1;
   }
   show_sp(a_k, a_n, a_x, "a: single precision, length 3");
   show_dp(b_k, b_n, b_x, "b: double precision, length 5");
   show_dp(c_k, c_n, c_x, "c: double precision, deferred length allocated as 4");
   printf("\n");
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "sum(a%x) =");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", sum_1d_float(3, a_x));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "sum(b%x) =");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", sum_1d_double(5, b_x));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "sum(c%x) =");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", sum_1d_double(n_c_x, c_x));
      first = 0;
      printf("\n");
   }
   free(a_x);
   free(b_x);
   free(c_x);
   return 0;
}
