/* Generated by xf2c.py from xpdt_matrix.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"

static float sum_2d_float(const int n1, const int n2, const float *x) {
   float s = 0.0f;
   for (int i = 0; i < n1 * n2; ++i) s += x[i];
   return s;
}

void show(const int this_nrow, const int this_ncol, const float *this_x, const char * name);
void fill_seq(const int this_nrow, const int this_ncol, float *this_x, const float start, const float step);
void transpose_fill(const int src_nrow, const int src_ncol, const float *src_x, float *dst_x);

void show(const int this_nrow, const int this_ncol, const float *this_x, const char * name) {
   int i, j, n_row = 0;
   float *row = NULL;
   printf("\n");
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", trim_s(name));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "  nrow =");
      first = 0;
      printf("%s%d", first ? "" : " ", this_nrow);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "  ncol =");
      first = 0;
      printf("%s%d", first ? "" : " ", this_ncol);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "  values:");
      first = 0;
      printf("\n");
   }
   if (row) free(row);
   row = (float*) malloc(sizeof(float) * this_ncol);
   if (!row && this_ncol > 0) return;
   n_row = this_ncol;
   i = 0;
   while (i < this_nrow) {
      j = 0;
      while (j < this_ncol) {
         row[j] = this_x[i + this_nrow * j];
         j += 1;
      }
      {
         int first = 1;
         for (int i_pr = 0; i_pr < n_row; ++i_pr) {
            if (first) printf("%13.6f", row[i_pr]);
            else printf("    %13.6f", row[i_pr]);
            first = 0;
         }
         printf("    \n");
      }
      i += 1;
   }
   /* unsupported: deallocate(row_x) */
}

void fill_seq(const int this_nrow, const int this_ncol, float *this_x, const float start, const float step) {
   int i, j;
   float val = start;
   i = 0;
   while (i < this_nrow) {
      j = 0;
      while (j < this_ncol) {
         this_x[i + this_nrow * j] = val;
         val += step;
         j += 1;
      }
      i += 1;
   }
}

void transpose_fill(const int src_nrow, const int src_ncol, const float *src_x, float *dst_x) {
   int i, j;
   i = 0;
   while (i < src_ncol) {
      j = 0;
      while (j < src_nrow) {
         dst_x[i + src_ncol * j] = src_x[j + src_nrow * i];
         j += 1;
      }
      i += 1;
   }
}

int main(void) {
   int a_nrow = 2, a_ncol = 3, at_nrow = 3, at_ncol = 2, b_nrow = 0, b_ncol = 0, n_b_x_1 = 0, n_b_x_2 = 0;
   int bt_nrow = 0, bt_ncol = 0, n_bt_x_1 = 0, n_bt_x_2 = 0;
   float *a_x = NULL, *at_x = NULL, *b_x = NULL, *bt_x = NULL, *raw = NULL;
   a_x = (float*) malloc(sizeof(float) * 6);
   if (!a_x) return 1;
   at_x = (float*) malloc(sizeof(float) * 6);
   if (!at_x) return 1;
   raw = (float*) malloc(sizeof(float) * 4);
   if (!raw) return 1;
   fill_seq(a_nrow, a_ncol, a_x, 1.0, 1.0);
   show(a_nrow, a_ncol, a_x, "a: fixed 2 x 3 matrix");
   at_nrow = a_ncol;
   at_ncol = a_nrow;
   transpose_fill(a_nrow, a_ncol, a_x, at_x);
   show(at_nrow, at_ncol, at_x, "transpose of a");
   b_nrow = 3;
   b_ncol = 4;
   if (b_x) free(b_x);
   b_x = (float*) malloc(sizeof(float) * b_nrow * b_ncol);
   if (!b_x && (b_nrow * b_ncol) > 0) return 1;
   n_b_x_1 = b_nrow;
   n_b_x_2 = b_ncol;
   fill_seq(b_nrow, b_ncol, b_x, 10.0, 0.5);
   show(b_nrow, b_ncol, b_x, "b: deferred-size allocatable matrix");
   bt_nrow = b_ncol;
   bt_ncol = b_nrow;
   if (bt_x) free(bt_x);
   bt_x = (float*) malloc(sizeof(float) * bt_nrow * bt_ncol);
   if (!bt_x && (bt_nrow * bt_ncol) > 0) return 1;
   n_bt_x_1 = bt_nrow;
   n_bt_x_2 = bt_ncol;
   transpose_fill(b_nrow, b_ncol, b_x, bt_x);
   show(bt_nrow, bt_ncol, bt_x, "transpose of b");
   if (0 < 4) raw[0] = 1.0;
   if (1 < 4) raw[1] = 3.0;
   if (2 < 4) raw[2] = 2.0;
   if (3 < 4) raw[3] = 4.0;
   for (int i_fill = 4; i_fill < 4; ++i_fill) {
      raw[i_fill] = raw[i_fill % 4];
   }
   if (b_x) free(b_x);
   b_x = NULL;
   n_b_x_1 = 0;
   n_b_x_2 = 0;
   b_nrow = 2;
   b_ncol = 2;
   if (b_x) free(b_x);
   b_x = (float*) malloc(sizeof(float) * b_nrow * b_ncol);
   if (!b_x && (b_nrow * b_ncol) > 0) return 1;
   n_b_x_1 = b_nrow;
   n_b_x_2 = b_ncol;
   if (b_x) free(b_x);
   b_x = (float*) malloc(sizeof(float) * 4);
   if (!b_x && 4 > 0) return 1;
   n_b_x_1 = 2;
   n_b_x_2 = 2;
   for (int i_fill = 0; i_fill < 4; ++i_fill) {
      b_x[i_fill] = raw[i_fill];
   }
   show(b_nrow, b_ncol, b_x, "b reassigned from make_matrix(raw)");
   printf("\n");
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "sum(a%x)  =");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", sum_2d_float(2, 3, a_x));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "sum(at%x) =");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", sum_2d_float(3, 2, at_x));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "sum(b%x)  =");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", sum_2d_float(n_b_x_1, n_b_x_2, b_x));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "sum(bt%x) =");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", sum_2d_float(n_bt_x_1, n_bt_x_2, bt_x));
      first = 0;
      printf("\n");
   }
   free(a_x);
   free(at_x);
   free(b_x);
   free(bt_x);
   free(raw);
   return 0;
}
