/* Generated by xf2c.py from xpdt_string.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"

void show(const int this_n, const char * this_text, const char * name);

void show(const int this_n, const char * this_text, const char * name) {
   printf("\n");
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", trim_s(name));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "  n    =");
      first = 0;
      printf("%s%d", first ? "" : " ", this_n);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "  text = [");
      first = 0;
      printf("%s%s", first ? "" : "", this_text);
      first = 0;
      printf("%s%s", first ? "" : "", "]");
      first = 0;
      printf("\n");
   }
}

int main(void) {
   int a_n = 5, b_n = 0, c_n = 0, a_upper_n = 5, b_upper_n = 0, c_upper_n = 0, i_upper;
   enum { a_text_len = 5, a_upper_text_len = 5, ch_upper_len = 1 };
   char a_text[a_text_len + 1] = "", a_upper_text[a_upper_text_len + 1] = "", ch_upper[ch_upper_len + 1] = "";
   char *b_text = NULL, *c_text = NULL, *msg = NULL, *b_upper_text = NULL, *c_upper_text = NULL;
   assign_str(a_text, a_text_len, "hello");
   assign_str_alloc(&msg, "parameterized derived types");
   b_n = ((int) strlen(msg));
   assign_str_alloc(&b_text, "");
   assign_str_alloc(&b_text, msg);
   c_n = 11;
   assign_str_alloc(&c_text, "fortran pdt");
   show(a_n, a_text, "a: fixed length box");
   show(b_n, b_text, "b: deferred length box allocated at runtime");
   show(c_n, c_text, "c: box returned by make_box");
   a_upper_n = a_n;
   assign_str(a_upper_text, a_upper_text_len, a_text);
   i_upper = 1;
   while (i_upper <= a_upper_n) {
      assign_str(ch_upper, ch_upper_len, substr_s(a_upper_text, i_upper, i_upper));
      if (iachar_s(ch_upper) >= iachar_s("a") && iachar_s(ch_upper) <= iachar_s("z")) {
         assign_substr(a_upper_text, a_upper_text_len, i_upper, i_upper, achar_s(iachar_s(ch_upper) - iachar_s("a") + iachar_s("A")));
      }
      i_upper += 1;
   }
   b_upper_n = b_n;
   assign_str_alloc(&b_upper_text, b_text);
   i_upper = 1;
   while (i_upper <= b_upper_n) {
      assign_str(ch_upper, ch_upper_len, substr_s(b_upper_text, i_upper, i_upper));
      if (iachar_s(ch_upper) >= iachar_s("a") && iachar_s(ch_upper) <= iachar_s("z")) {
         assign_substr(b_upper_text, ((int) strlen(b_upper_text)), i_upper, i_upper, achar_s(iachar_s(ch_upper) - iachar_s("a") + iachar_s("A")));
      }
      i_upper += 1;
   }
   c_upper_n = c_n;
   assign_str_alloc(&c_upper_text, c_text);
   i_upper = 1;
   while (i_upper <= c_upper_n) {
      assign_str(ch_upper, ch_upper_len, substr_s(c_upper_text, i_upper, i_upper));
      if (iachar_s(ch_upper) >= iachar_s("a") && iachar_s(ch_upper) <= iachar_s("z")) {
         assign_substr(c_upper_text, ((int) strlen(c_upper_text)), i_upper, i_upper, achar_s(iachar_s(ch_upper) - iachar_s("a") + iachar_s("A")));
      }
      i_upper += 1;
   }
   show(a_upper_n, a_upper_text, "uppercase copy of a");
   show(b_upper_n, b_upper_text, "uppercase copy of b");
   show(c_upper_n, c_upper_text, "uppercase copy of c");
   return 0;
}
