/* Generated by xf2c.py from xpointer.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   float x;
   float *y = NULL, *xp = NULL, *yp = NULL, *z = NULL;
   int n_yp = 0, n_z = 0;
   y = (float*) malloc(sizeof(float) * 4);
   if (!y) return 1;
   xp = &x;
   x = 2.3;
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", (*xp));
      first = 0;
      printf("\n");
   }
   (*xp) = 10*(*xp);
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", (*xp));
      first = 0;
      printf("%s%13.6f", first ? "" : " ", x);
      first = 0;
      printf("\n");
   }
   y[0] = 10.0;
   y[1] = 20.0;
   y[2] = 30.0;
   y[3] = 40.0;
   yp = &y[1];
   n_yp = ((1 / 1 + 1));
   for (int p_fill = 0; p_fill < n_yp; ++p_fill) {
      yp[p_fill] = 10 * yp[p_fill];
   }
   {
      int first_pr = 1;
      for (int i_pr = 0; i_pr < n_yp; ++i_pr) {
         printf("%s%g", first_pr ? "" : " ", yp[i_pr]);
         first_pr = 0;
      }
      for (int i_pr = 0; i_pr < 4; ++i_pr) {
         printf("%s%g", first_pr ? "" : " ", y[i_pr]);
         first_pr = 0;
      }
      printf("\n");
   }
   if (z) free(z);
   z = (float*) malloc(sizeof(float) * 3);
   if (!z && 3 > 0) return 1;
   n_z = 3;
   z[0] = 5.0;
   z[1] = 10.0;
   z[2] = 15.0;
   {
      int first = 1;
      for (int i_pr = 0; i_pr < n_z; ++i_pr) {
         if (first) printf("%13.6f", z[i_pr]);
         else printf("    %13.6f", z[i_pr]);
         first = 0;
      }
      printf("    \n");
   }
   if (z) free(z);
   z = NULL;
   n_z = 0;
   free(y);
   return 0;
}
