/* Generated by xf2c.py from xprint.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   printf("%d", 10);
   printf("%s", " ");
   printf("%s", "ab");
   printf("\n");
   printf("%d", 20);
   printf("%s", " ");
   printf("%s", "ab");
   printf("\n");
   printf("%d", 30);
   printf("%s", " ");
   printf("%s", "ab");
   printf("\n");
   return 0;
}
