/* Generated by xf2c.py from xprint_star.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   printf("%s", "hello");
   printf("\n");
   printf("\n");
   printf("%s", "world");
   printf("\n");
   return 0;
}
