/* Generated by xf2c.py from xprint_fmt_kw_tmp.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

void mean_sd(const int n, const double *x, double *mean, double *sd, const int *calc_mean);

void mean_sd(const int n, const double *x, double *mean, double *sd, const int *calc_mean) {
   /* n: extent of x (dimension 1) */
   int calc_mean_;
   if ((calc_mean != NULL)) {
      calc_mean_ = (*calc_mean);
   }
   else {
      calc_mean_ = 1;
   }
   if (calc_mean_) {
      {
         int first = 1;
         printf("%s%s", first ? "" : " ", "calculating mean");
         first = 0;
         printf("\n");
      }
      {
         double red = 0.0;
         for (int i_fill = 0; i_fill < n; ++i_fill) red += x[i_fill];
         (*mean) = red/fmaxf(1,n);
      }
   }
   if (n > 1) {
      {
         double red = 0.0;
         for (int i_fill = 0; i_fill < n; ++i_fill) red += (((x[i_fill]-(*mean))) * ((x[i_fill]-(*mean))));
         (*sd) = (sqrtf(red/(n - 1)));
      }
   }
   else {
      (*sd) = -(1.0);
   }
}

int main(void) {
   double *x = NULL;
   double mean, sd;
   const char *fmt_o = "(/,a)";
   const char *fmt_stats = "('mean, sd = ',2f10.6)";
   x = (double*) malloc(sizeof(double) * 4);
   if (!x) return 1;
   x[0] = 1.0;
   x[1] = 2.0;
   x[2] = 3.0;
   x[3] = 5.0;
   printf("\n");
   printf("%s", "call mean_sd(x, mean, sd, calc_mean = .true.)");
   printf("\n");
   mean_sd(4, x, &mean, &sd, &((int){1}));
   printf("%s", "mean, sd = ");
   printf("%10.6f", mean);
   printf("%10.6f", sd);
   printf("\n");
   printf("\n");
   printf("%s", "call mean_sd(x, mean, sd, calc_mean = .false.)");
   printf("\n");
   mean_sd(4, x, &mean, &sd, &((int){0}));
   printf("%s", "mean, sd = ");
   printf("%10.6f", mean);
   printf("%10.6f", sd);
   printf("\n");
   free(x);
   return 0;
}
