/* Generated by xf2c.py from xprimes_upto_p.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

static int ret_primes_upto_n = 0;

int *primes_upto(const int n);

int *primes_upto(const int n) {
   int *primes_upto_result = NULL, *is_prime = NULL, *p = NULL;
   int n_primes_upto_result = 0, cnt, i, k, limit, n_is_prime = 0, n_p = 0;
   if (n < 2) {
      if ((p != NULL)) {
         if (p) free(p);
         p = NULL;
         n_p = 0;
      }
      if (p) free(p);
      p = (int*) malloc(sizeof(int) * 0);
      if (!p && 0 > 0) return NULL;
      n_p = 0;
      if (primes_upto_result) free(primes_upto_result);
      primes_upto_result = (int*) malloc(sizeof(int) * n_p);
      if (!primes_upto_result && n_p > 0) return NULL;
      n_primes_upto_result = n_p;
      for (int p_fill = 0; p_fill < n_p; ++p_fill) {
         primes_upto_result[p_fill] = p[p_fill];
      }
      return primes_upto_result;
   }
   if ((is_prime != NULL)) {
      if (is_prime) free(is_prime);
      is_prime = NULL;
      n_is_prime = 0;
   }
   if (is_prime) free(is_prime);
   is_prime = (int*) malloc(sizeof(int) * n);
   if (!is_prime && n > 0) return NULL;
   n_is_prime = n;
   for (int i_fill = 0; i_fill < n_is_prime; ++i_fill) {
      is_prime[i_fill] = 1;
   }
   is_prime[0] = 0;
   limit = ((int) ((sqrt(((double) n)))));
   i = 2;
   while (i <= limit) {
      if (is_prime[i - 1]) {
         k = i * i;
         while (k <= n) {
            is_prime[k - 1] = 0;
            k += i;
         }
      }
      i += 1;
   }
   cnt = 0;
   i = 2;
   while (i <= n) {
      if (is_prime[i - 1]) {
         cnt += 1;
      }
      i += 1;
   }
   if ((p != NULL)) {
      if (p) free(p);
      p = NULL;
      n_p = 0;
   }
   if (p) free(p);
   p = (int*) malloc(sizeof(int) * cnt);
   if (!p && cnt > 0) return NULL;
   n_p = cnt;
   cnt = 0;
   i = 2;
   while (i <= n) {
      if (is_prime[i - 1]) {
         cnt += 1;
         p[cnt - 1] = i;
      }
      i += 1;
   }
   if (primes_upto_result) free(primes_upto_result);
   primes_upto_result = (int*) malloc(sizeof(int) * n_p);
   if (!primes_upto_result && n_p > 0) return NULL;
   n_primes_upto_result = n_p;
   for (int p_fill = 0; p_fill < n_p; ++p_fill) {
      primes_upto_result[p_fill] = p[p_fill];
   }
   ret_primes_upto_n = n_primes_upto_result;
   return primes_upto_result;
}

int main(void) {
   int n, n_p = 0;
   int *p = NULL;
   /* unsupported: use, intrinsic :: iso_fortran_env, only: real64 */
   n = 1000000;
   int *tmp_primes_upto = primes_upto(n);
   if (p) free(p);
   p = (int*) malloc(sizeof(int) * ret_primes_upto_n);
   if (!p && ret_primes_upto_n > 0) return 1;
   n_p = ret_primes_upto_n;
   for (int i_copy = 0; i_copy < ret_primes_upto_n; ++i_copy) {
      p[i_copy] = tmp_primes_upto[i_copy];
   }
   free(tmp_primes_upto);
   {
      int first = 1;
      printf("%s%d", first ? "" : " ", n_p);
      first = 0;
      printf("%s%s", first ? "" : " ", "primes up to ");
      first = 0;
      printf("%s%d", first ? "" : " ", n);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "last prime:");
      first = 0;
      printf("%s%d", first ? "" : " ", p[n_p - 1]);
      first = 0;
      printf("\n");
   }
   free(p);
   return 0;
}
