/* Generated by xf2c.py from xprint_blank.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "before");
      first = 0;
      printf("\n");
   }
   printf("\n");
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "after");
      first = 0;
      printf("\n");
   }
   return 0;
}
