/* Generated by xf2c.py from xratio_sections.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   enum { n1 = 4 };
   enum { n2 = 2 };
   float *x = NULL, *xr = NULL;
   x = (float*) malloc(sizeof(float) * 8);
   if (!x) return 1;
   xr = (float*) malloc(sizeof(float) * 6);
   if (!xr) return 1;
   x[0] = 1.0;
   x[1] = 2.0;
   x[2] = 4.0;
   x[3] = 8.0;
   x[4] = 3.0;
   x[5] = 6.0;
   x[6] = 12.0;
   x[7] = 24.0;
   for (int i2_fill = 0; i2_fill < 2; ++i2_fill) {
      for (int i1_fill = 0; i1_fill < 3; ++i1_fill) {
         xr[i1_fill + 3 * i2_fill] = x[i1_fill + 1 + 4 * i2_fill] / x[i1_fill + 4 * i2_fill] - 1.0;
      }
   }
   {
      int first = 1;
      for (int i2 = 1; i2 <= 2; i2 += 1) {
         printf("%s%g", first ? "" : " ", x[4 * (i2 - 1)]);
         first = 0;
      }
      printf("\n");
   }
   {
      int first = 1;
      for (int i2 = 1; i2 <= 2; i2 += 1) {
         printf("%s%g", first ? "" : " ", x[1 + 4 * (i2 - 1)]);
         first = 0;
      }
      printf("\n");
   }
   {
      int first = 1;
      for (int i2 = 1; i2 <= 2; i2 += 1) {
         printf("%s%g", first ? "" : " ", xr[3 * (i2 - 1)]);
         first = 0;
      }
      printf("\n");
   }
   {
      int first = 1;
      for (int i_pr = 0; i_pr < ((1 / 1 + 1)); ++i_pr) {
         if (first) printf("%13.6f", x[1 + 4 * i_pr]/x[4 * i_pr] - 1.0 - xr[3 * i_pr]);
         else printf("    %13.6f", x[1 + 4 * i_pr]/x[4 * i_pr] - 1.0 - xr[3 * i_pr]);
         first = 0;
      }
      printf("    \n");
   }
   free(x);
   free(xr);
   return 0;
}
