/* Generated by xf2c.py from xrational_approx_rng_jac.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"


void seed_rng(const int seed);
void local_random_number(double * x);
void set_seed(const int seed);
double normal_rand();
void fill_true_values(const int n, const double *x, double *y, const double k);
void scale_x(const int n, const double *x, double *z);
void rational32(const int n, const double *z, const double *theta, double *yhat, double *den);
void rational_residuals(const int n_z, const double *z, const int n_y, const double *y, const double *theta, const double den_floor, const double penalty_weight, double *r);
void rational_jacobian(const int n_z, const double *z, const int n_y, const double *y, const double *theta, const double den_floor, const double penalty_weight, const double *r, double *jac);

void seed_rng(const int seed) {
   rng_seed(((long long) seed));
}

void local_random_number(double * x) {
   (*x) = ((double) (runif()));
}

void set_seed(const int seed) {
   seed_rng(seed);
}

double normal_rand() {
   double result, u1, u2, pi;
   pi = acos(-(1.0));
   local_random_number(&u1);
   local_random_number(&u2);
   if (u1 < 1.0e-12) {
      u1 = 1e-12;
   }
   result = sqrt(-(2.0) * log(u1)) * cos(2.0 * pi * u2);
   return result;
}

void fill_true_values(const int n, const double *x, double *y, const double k) {
   /* n: extent of x (dimension 1) */
   int i = 1;
   while (i <= n) {
      y[i - 1] = sin(k * x[i - 1]);
      i += 1;
   }
}

void scale_x(const int n, const double *x, double *z) {
   /* n: extent of x (dimension 1) */
   double xmin, xmax;
   xmin = minval_1d_double(n, x);
   xmax = maxval_1d_double(n, x);
   for (int p_fill = 0; p_fill < n; ++p_fill) {
      z[p_fill] = 2.0*(x[p_fill] - xmin)/(xmax - xmin) - 1.0;
   }
}

void rational32(const int n, const double *z, const double *theta, double *yhat, double *den) {
   /* n: extent of z (dimension 1) */
   double num[n], den_safe[n];
   for (int p_fill = 0; p_fill < n; ++p_fill) {
      num[p_fill] = theta[0] + theta[1] * z[p_fill] + theta[2] * z[p_fill] * z[p_fill] + theta[3] * z[p_fill] * z[p_fill] * z[p_fill];
   }
   for (int p_fill = 0; p_fill < n; ++p_fill) {
      den[p_fill] = 1.0 + theta[4] * z[p_fill] + theta[5] * z[p_fill] * z[p_fill];
   }
   for (int p_fill = 0; p_fill < n; ++p_fill) {
      den_safe[p_fill] = (((den[p_fill]) >= 0) ? ((((fmax(fabs(den[p_fill]), 1e-12)) < 0) ? -(fmax(fabs(den[p_fill]), 1e-12)) : (fmax(fabs(den[p_fill]), 1e-12)))) : -((((fmax(fabs(den[p_fill]), 1e-12)) < 0) ? -(fmax(fabs(den[p_fill]), 1e-12)) : (fmax(fabs(den[p_fill]), 1e-12)))));
   }
   for (int p_fill = 0; p_fill < n; ++p_fill) {
      yhat[p_fill] = num[p_fill]/den_safe[p_fill];
   }
}

void rational_residuals(const int n_z, const double *z, const int n_y, const double *y, const double *theta, const double den_floor, const double penalty_weight, double *r) {
   /* n_z: extent of z (dimension 1) */
   /* n_y: extent of y (dimension 1) */
   int i;
   double den[n_z], yhat[n_z];
   rational32(n_z, z, theta, yhat, den);
   if (1 > 0) {
      for (int i_fill = 1, p_fill = 0; p_fill < n_y; i_fill += 1, ++p_fill) {
         r[i_fill - 1] = y[p_fill] - yhat[p_fill];
      }
   } else {
      for (int i_fill = 1, p_fill = 0; p_fill < n_y; i_fill += 1, ++p_fill) {
         r[i_fill - 1] = y[p_fill] - yhat[p_fill];
      }
   }
   i = 0;
   while (i < n_z) {
      r[n_z + i] = penalty_weight * fmax(0.0, den_floor - fabs(den[i]));
      i += 1;
   }
}

void rational_jacobian(const int n_z, const double *z, const int n_y, const double *y, const double *theta, const double den_floor, const double penalty_weight, const double *r, double *jac) {
   /* n_z: extent of z (dimension 1) */
   /* n_y: extent of y (dimension 1) */
   int j;
   double h, r1[2 * n_z], theta1[6];
   j = 0;
   while (j < 6) {
      for (int p_fill = 0; p_fill < 6; ++p_fill) {
         theta1[p_fill] = theta[p_fill];
      }
      h = 1e-06 * (1.0 + fabs(theta[j]));
      theta1[j] += h;
      rational_residuals(n_z, z, n_y, y, theta1, den_floor, penalty_weight, r1);
      for (int p_fill = 0; p_fill < 2 * n_z; ++p_fill) {
         jac[p_fill + 2 * n_z * j] = (r1[p_fill] - r[p_fill])/h;
      }
      j += 1;
   }
}

int main(void) {
   enum { n = 300 };
   enum { seed = 123 };
   const double x_min = -4.0, x_max = 4.0, noise_sd = 0.15, k = 2.0, den_floor = 0.15, penalty_weight = 10.0;
   int i;
   double *a = NULL, *g = NULL, *jac = NULL, *r = NULL, *theta = NULL, *x = NULL, *y = NULL, *y_true = NULL;
   double *z = NULL;
   double obj;
   a = (double*) malloc(sizeof(double) * 36);
   if (!a) return 1;
   g = (double*) malloc(sizeof(double) * 6);
   if (!g) return 1;
   jac = (double*) malloc(sizeof(double) * 3600);
   if (!jac) return 1;
   r = (double*) malloc(sizeof(double) * 600);
   if (!r) return 1;
   theta = (double*) malloc(sizeof(double) * 6);
   if (!theta) return 1;
   x = (double*) malloc(sizeof(double) * 300);
   if (!x) return 1;
   y = (double*) malloc(sizeof(double) * 300);
   if (!y) return 1;
   y_true = (double*) malloc(sizeof(double) * 300);
   if (!y_true) return 1;
   z = (double*) malloc(sizeof(double) * 300);
   if (!z) return 1;
   set_seed(123);
   i = 0;
   while (i < 300) {
      x[i] = (-(4.0)) + (4.0 + 4.0)*((double) i)/((double) 299);
      i += 1;
   }
   fill_true_values(300, x, y_true, (2.0));
   i = 0;
   while (i < 300) {
      y[i] = y_true[i] + 0.15 * normal_rand();
      i += 1;
   }
   scale_x(300, x, z);
   theta[0] = 0.0;
   theta[1] = 1.0;
   theta[2] = 0.0;
   theta[3] = 0.0;
   theta[4] = 0.0;
   theta[5] = 0.0;
   rational_residuals(300, z, 300, y, theta, (0.15), (10.0), r);
   rational_jacobian(300, z, 300, y, theta, (0.15), (10.0), r, jac);
   obj = dot_product_1d_double(600, r, r);
   for (int i_fill = 0; i_fill < 6; ++i_fill) {
      double red = 0;
      for (int k_fill = 0; k_fill < 2*300; ++k_fill) red += jac[k_fill + 600 * i_fill] * r[k_fill];
      g[i_fill] = red;
   }
   for (int j_fill = 0; j_fill < 6; ++j_fill) {
      for (int i_fill = 0; i_fill < 6; ++i_fill) {
         double red = 0;
         for (int k_fill = 0; k_fill < 2*300; ++k_fill) red += jac[k_fill + 600 * i_fill] * jac[k_fill + 600 * j_fill];
         a[i_fill + 6 * j_fill] = red;
      }
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "rational residual and Jacobian check with local MT RNG");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "objective =");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", obj);
      first = 0;
      printf("\n");
   }
   printf("%s\n", "g:");
   {
      int first = 1;
      for (int i_pr = 0; i_pr < 6; ++i_pr) {
         if (first) printf("%13.6f", g[i_pr]);
         else printf("    %13.6f", g[i_pr]);
         first = 0;
      }
      printf("    \n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "diag(a):");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", a[0]);
      first = 0;
      printf("%s%13.6f", first ? "" : " ", a[7]);
      first = 0;
      printf("%s%13.6f", first ? "" : " ", a[14]);
      first = 0;
      printf("%s%13.6f", first ? "" : " ", a[21]);
      first = 0;
      printf("%s%13.6f", first ? "" : " ", a[28]);
      first = 0;
      printf("%s%13.6f", first ? "" : " ", a[35]);
      first = 0;
      printf("\n");
   }
   printf("%s\n", "first row of a:");
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", a[0]);
      first = 0;
      printf("%s%13.6f", first ? "" : " ", a[6]);
      first = 0;
      printf("%s%13.6f", first ? "" : " ", a[12]);
      first = 0;
      printf("%s%13.6f", first ? "" : " ", a[18]);
      first = 0;
      printf("%s%13.6f", first ? "" : " ", a[24]);
      first = 0;
      printf("%s%13.6f", first ? "" : " ", a[30]);
      first = 0;
      printf("\n");
   }
   printf("%s\n", "first row of jac:");
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", jac[0]);
      first = 0;
      printf("%s%13.6f", first ? "" : " ", jac[600]);
      first = 0;
      printf("%s%13.6f", first ? "" : " ", jac[1200]);
      first = 0;
      printf("%s%13.6f", first ? "" : " ", jac[1800]);
      first = 0;
      printf("%s%13.6f", first ? "" : " ", jac[2400]);
      first = 0;
      printf("%s%13.6f", first ? "" : " ", jac[3000]);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "first five residuals:");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", r[0]);
      first = 0;
      printf("%s%13.6f", first ? "" : " ", r[1]);
      first = 0;
      printf("%s%13.6f", first ? "" : " ", r[2]);
      first = 0;
      printf("%s%13.6f", first ? "" : " ", r[3]);
      first = 0;
      printf("%s%13.6f", first ? "" : " ", r[4]);
      first = 0;
      printf("\n");
   }
   free(a);
   free(g);
   free(jac);
   free(r);
   free(theta);
   free(x);
   free(y);
   free(y_true);
   free(z);
   return 0;
}
