/* Generated by xf2c.py from xrational_approx.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"


void set_seed(const int seed);
double normal_rand();
double rmse(const int n_yhat, const double *yhat, const int n_y, const double *y);
double cubic_pos(const double x);
void solve_linear(const int n_a_in_1, const int n_a_in_2, const double *a_in, const int n_b_in, const double *b_in, const int n_x, double *x, int *info);
void solve_least_squares(const int n_a_1, const int n_a_2, const double *a, const int n_y, const double *y, const int n_coef, double *coef, const int n_lambda_diag, const double *lambda_diag);
double true_func_scalar(const double x, const char * true_name, const double k, const double lam, const double c_lin, const double a_log, const double b_log);
void fill_true_values(const int n, const double *x, double *y, const char * true_name, const double k, const double lam, const double c_lin, const double a_log, const double b_log);
void scale_x(const int n, const double *x, double *z);
void fit_cubic_poly(const int n_z, const double *z, const int n_y, const double *y, double *coef);
void eval_cubic_poly(const int n, const double *z, const double *coef, double *yhat);
void rational32(const int n, const double *z, const double *theta, double *yhat, double *den);
void rational_residuals(const int n_z, const double *z, const int n_y, const double *y, const double *theta, const double den_floor, const double penalty_weight, double *r);
void rational_jacobian(const int n_z, const double *z, const int n_y, const double *y, const double *theta, const double den_floor, const double penalty_weight, const double *r, double *jac);
void fit_rational32(const int n_z, const double *z, const int n_y, const double *y, const double *theta0, const double den_floor, const double penalty_weight, double *theta, double *obj, int *iter_used);
void make_knots(const int nknots, double *knots);
void spline_basis(const int n_z, const double *z, const int n_knots, const double *knots, double *b);
void fit_penalized_cubic_spline(const int n_z, const double *z, const int n_y, const double *y, const int nknots, const double lambda, double *knots, double *coef);
void eval_penalized_cubic_spline(const int n_z, const double *z, const int n_knots, const double *knots, const double *coef, double *yhat);

void set_seed(const int seed) {
   int nseed, i, n_seedv = 0;
   int *seedv = NULL;
   nseed = 1;
   if (seedv) free(seedv);
   seedv = (int*) malloc(sizeof(int) * nseed);
   if (!seedv && nseed > 0) return;
   n_seedv = nseed;
   i = 1;
   while (i <= nseed) {
      seedv[i - 1] = fmod(seed + 104729 * i, INT_MAX - 1);
      if (seedv[i - 1] <= 0) {
         seedv[i - 1] = i;
      }
      xf2c_loop_1_continue: ;
      i += 1;
   }
   xf2c_loop_1_break: ;
}

double normal_rand() {
   double result, u1, u2, pi;
   pi = acos(-(1.0));
   u1 = (double)rand() / (double)RAND_MAX;
   u2 = (double)rand() / (double)RAND_MAX;
   if (u1 < 1.0e-12) {
      u1 = 1e-12;
   }
   result = sqrt(-(2.0) * log(u1)) * cos(2.0 * pi * u2);
   return result;
}

double rmse(const int n_yhat, const double *yhat, const int n_y, const double *y) {
   /* n_yhat: extent of yhat (dimension 1) */
   /* n_y: extent of y (dimension 1) */
   double result;
   {
      double red = 0.0;
      for (int i_fill = 0; i_fill < n_yhat; ++i_fill) red += ((yhat[i_fill] - y[i_fill]) * (yhat[i_fill] - y[i_fill]));
      result = (sqrt(red/((double) n_y)));
   }
   return result;
}

double cubic_pos(const double x) {
   double result;
   if (x > 0.0) {
      result = x * x * x;
   }
   else {
      result = 0.0;
   }
   return result;
}

void solve_linear(const int n_a_in_1, const int n_a_in_2, const double *a_in, const int n_b_in, const double *b_in, const int n_x, double *x, int *info) {
   /* n_a_in_1: extent of a_in (dimension 1) */
   /* n_a_in_2: extent of a_in (dimension 2) */
   /* n_b_in: extent of b_in (dimension 1) */
   /* n_x: extent of x (dimension 1) */
   int i, k, piv;
   double a[n_a_in_1 * n_a_in_2], b[n_b_in], factor, tmp, rowtmp[n_a_in_2];
   if (n_a_in_1 != n_b_in || n_a_in_2 != n_b_in || n_x != n_b_in) {
      (*info) = -1;
      return;
   }
   for (int i_fill = 0; i_fill < n_a_in_1 * n_a_in_2; ++i_fill) {
      a[i_fill] = a_in[i_fill];
   }
   for (int p_fill = 0; p_fill < n_b_in; ++p_fill) {
      b[p_fill] = b_in[p_fill];
   }
   (*info) = 0;
   k = 1;
   while (k <= n_b_in - 1) {
      piv = k;
      i = k + 1;
      while (i <= n_b_in) {
         if ((fabs(a[i - 1 + n_a_in_1 * (k - 1)])) > (fabs(a[piv - 1 + n_a_in_1 * (k - 1)]))) {
            piv = i;
         }
         i += 1;
      }
      if ((fabs(a[piv - 1 + n_a_in_1 * (k - 1)])) < 1.0e-14) {
         (*info) = k;
         return;
      }
      if (piv != k) {
         for (int p_fill = 0; p_fill < ((((n_a_in_2 - 1) / 1 + 1))); ++p_fill) {
            rowtmp[p_fill] = a[k - 1 + n_a_in_1 * p_fill];
         }
         for (int p_fill = 0; p_fill < n_a_in_2; ++p_fill) {
            a[k - 1 + n_a_in_1 * p_fill] = a[piv - 1 + n_a_in_1 * p_fill];
         }
         for (int p_fill = 0; p_fill < n_a_in_2; ++p_fill) {
            a[piv - 1 + n_a_in_1 * p_fill] = rowtmp[p_fill];
         }
         tmp = b[k - 1];
         b[k - 1] = b[piv - 1];
         b[piv - 1] = tmp;
      }
      i = k + 1;
      while (i <= n_b_in) {
         factor = a[i - 1 + n_a_in_1 * (k - 1)]/a[k - 1 + n_a_in_1 * (k - 1)];
         for (int p_fill = 0; p_fill < (((n_b_in - k) / 1 + 1)); ++p_fill) {
            a[i - 1 + n_a_in_1 * (k + p_fill - 1)] = a[i - 1 + n_a_in_1 * (k + p_fill - 1)] - factor * a[k - 1 + n_a_in_1 * (k + p_fill - 1)];
         }
         b[i - 1] -= factor*b[k - 1];
         i += 1;
      }
      xf2c_loop_1_continue: ;
      k += 1;
   }
   xf2c_loop_1_break: ;
   if ((fabs(a[n_b_in - 1 + n_a_in_1 * (n_b_in - 1)])) < 1.0e-14) {
      (*info) = n_b_in;
      return;
   }
   x[n_b_in - 1] = b[n_b_in - 1]/a[n_b_in - 1 + n_a_in_1 * (n_b_in - 1)];
   i = n_b_in - 1;
   while (i >= 1) {
      x[i - 1] = (b[i - 1] - ({ double red = 0.0; for (int i_red = 0; i_red < ((((n_b_in - i - 1) / 1 + 1))); ++i_red) red += (a[i - 1 + n_a_in_1 * (i + i_red)]) * (x[i + i_red]); red; }))/a[i - 1 + n_a_in_1 * (i - 1)];
      i += -1;
   }
}

void solve_least_squares(const int n_a_1, const int n_a_2, const double *a, const int n_y, const double *y, const int n_coef, double *coef, const int n_lambda_diag, const double *lambda_diag) {
   /* n_a_1: extent of a (dimension 1) */
   /* n_a_2: extent of a (dimension 2) */
   /* n_y: extent of y (dimension 1) */
   /* n_coef: extent of coef (dimension 1) */
   /* n_lambda_diag: extent of lambda_diag (dimension 1) */
   int i, info;
   double ata[n_coef * n_coef], aty[n_coef];
   if (n_a_1 != n_y || n_a_2 != n_coef) {
      fprintf(stderr, "%s\n", "solve_least_squares: dimension mismatch");
      exit(1);
   }
   for (int j_fill = 0; j_fill < n_a_2; ++j_fill) {
      for (int i_fill = 0; i_fill < n_a_2; ++i_fill) {
         double red = 0;
         for (int k_fill = 0; k_fill < n_a_1; ++k_fill) red += a[k_fill + n_a_1 * i_fill] * a[k_fill + n_a_1 * j_fill];
         ata[i_fill + n_a_2 * j_fill] = red;
      }
   }
   for (int i_fill = 0; i_fill < n_a_2; ++i_fill) {
      double red = 0;
      for (int k_fill = 0; k_fill < n_a_1; ++k_fill) red += a[k_fill + n_a_1 * i_fill] * y[k_fill];
      aty[i_fill] = red;
   }
   if ((lambda_diag != NULL)) {
      if (n_lambda_diag != n_coef) {
         fprintf(stderr, "%s\n", "solve_least_squares: bad lambda_diag size");
         exit(1);
      }
      i = 0;
      while (i < n_coef) {
         ata[i + n_coef * i] += lambda_diag[i];
         xf2c_loop_1_continue: ;
         i += 1;
      }
      xf2c_loop_1_break: ;
   }
   solve_linear(n_coef, n_coef, ata, n_coef, aty, n_coef, coef, &info);
   if (info != 0) {
      fprintf(stderr, "%s\n", "solve_least_squares: singular normal equations");
      exit(1);
   }
}

double true_func_scalar(const double x, const char * true_name, const double k, const double lam, const double c_lin, const double a_log, const double b_log) {
   double result, u;
   {
      if ((strcmp(trim_s(trim_s(true_name)), trim_s("sin")) == 0)) {
         result = sin(k * x);
      }
      else if ((strcmp(trim_s(trim_s(true_name)), trim_s("cos")) == 0)) {
         result = cos(k * x);
      }
      else if ((strcmp(trim_s(trim_s(true_name)), trim_s("sinc")) == 0)) {
         u = k * x;
         if ((fabs(u)) < 1.0e-12) {
            result = 1.0;
         }
         else {
            result = sin(u)/u;
         }
      }
      else if ((strcmp(trim_s(trim_s(true_name)), trim_s("exp_decay_sin")) == 0)) {
         result = exp(-lam * fabs(x)) * sin(k * x);
      }
      else if ((strcmp(trim_s(trim_s(true_name)), trim_s("linear_plus_sin")) == 0)) {
         result = c_lin * x + sin(k * x);
      }
      else if ((strcmp(trim_s(trim_s(true_name)), trim_s("logistic")) == 0)) {
         result = 1.0/(1.0 + exp(-a_log * (x - b_log)));
      }
      else {
         fprintf(stderr, "%s\n", "__result: unknown true_name");
         exit(1);
      }
   }
   return result;
}

void fill_true_values(const int n, const double *x, double *y, const char * true_name, const double k, const double lam, const double c_lin, const double a_log, const double b_log) {
   /* n: extent of x (dimension 1) */
   int i = 1;
   while (i <= n) {
      y[i - 1] = true_func_scalar(x[i - 1], true_name, k, lam, c_lin, a_log, b_log);
      xf2c_loop_1_continue: ;
      i += 1;
   }
   xf2c_loop_1_break: ;
}

void scale_x(const int n, const double *x, double *z) {
   /* n: extent of x (dimension 1) */
   double xmin, xmax;
   xmin = minval_1d_double(n, x);
   xmax = maxval_1d_double(n, x);
   if (xmax <= xmin) {
      fprintf(stderr, "%s\n", "scale_x: xmax <= xmin");
      exit(1);
   }
   for (int p_fill = 0; p_fill < n; ++p_fill) {
      z[p_fill] = 2.0*(x[p_fill] - xmin)/(xmax - xmin) - 1.0;
   }
}

void fit_cubic_poly(const int n_z, const double *z, const int n_y, const double *y, double *coef) {
   /* n_z: extent of z (dimension 1) */
   /* n_y: extent of y (dimension 1) */
   double a[n_z * 4];
   for (int p_fill = 0; p_fill < n_z; ++p_fill) {
      a[p_fill] = 1.0;
   }
   for (int p_fill = 0; p_fill < n_z; ++p_fill) {
      a[p_fill + n_z] = z[p_fill];
   }
   for (int p_fill = 0; p_fill < n_z; ++p_fill) {
      a[p_fill + n_z * 2] = z[p_fill] * z[p_fill];
   }
   for (int p_fill = 0; p_fill < n_z; ++p_fill) {
      a[p_fill + n_z * 3] = z[p_fill] * z[p_fill] * z[p_fill];
   }
   solve_least_squares(n_z, 4, a, n_y, y, 4, coef, 0, NULL);
}

void eval_cubic_poly(const int n, const double *z, const double *coef, double *yhat) {
   /* n: extent of z (dimension 1) */
   for (int p_fill = 0; p_fill < n; ++p_fill) {
      yhat[p_fill] = coef[0] + coef[1] * z[p_fill] + coef[2] * z[p_fill] * z[p_fill] + coef[3] * z[p_fill] * z[p_fill] * z[p_fill];
   }
}

void rational32(const int n, const double *z, const double *theta, double *yhat, double *den) {
   /* n: extent of z (dimension 1) */
   double num[n], den_safe[n];
   for (int p_fill = 0; p_fill < n; ++p_fill) {
      num[p_fill] = theta[0] + theta[1] * z[p_fill] + theta[2] * z[p_fill] * z[p_fill] + theta[3] * z[p_fill] * z[p_fill] * z[p_fill];
   }
   for (int p_fill = 0; p_fill < n; ++p_fill) {
      den[p_fill] = 1.0 + theta[4] * z[p_fill] + theta[5] * z[p_fill] * z[p_fill];
   }
   for (int p_fill = 0; p_fill < n; ++p_fill) {
      den_safe[p_fill] = (((den[p_fill]) >= 0) ? ((((fmax(fabs(den[p_fill]), 1e-12)) < 0) ? -(fmax(fabs(den[p_fill]), 1e-12)) : (fmax(fabs(den[p_fill]), 1e-12)))) : -((((fmax(fabs(den[p_fill]), 1e-12)) < 0) ? -(fmax(fabs(den[p_fill]), 1e-12)) : (fmax(fabs(den[p_fill]), 1e-12)))));
   }
   for (int p_fill = 0; p_fill < n; ++p_fill) {
      yhat[p_fill] = num[p_fill]/den_safe[p_fill];
   }
}

void rational_residuals(const int n_z, const double *z, const int n_y, const double *y, const double *theta, const double den_floor, const double penalty_weight, double *r) {
   /* n_z: extent of z (dimension 1) */
   /* n_y: extent of y (dimension 1) */
   int i;
   double yhat[n_z], den[n_z];
   rational32(n_z, z, theta, yhat, den);
   if (1 > 0) {
      for (int i_fill = 1, p_fill = 0; p_fill < n_y; i_fill += 1, ++p_fill) {
         r[i_fill - 1] = y[p_fill] - yhat[p_fill];
      }
   } else {
      for (int i_fill = 1, p_fill = 0; p_fill < n_y; i_fill += 1, ++p_fill) {
         r[i_fill - 1] = y[p_fill] - yhat[p_fill];
      }
   }
   i = 0;
   while (i < n_z) {
      r[n_z + i] = penalty_weight * fmax(0.0, den_floor - fabs(den[i]));
      xf2c_loop_1_continue: ;
      i += 1;
   }
   xf2c_loop_1_break: ;
}

void rational_jacobian(const int n_z, const double *z, const int n_y, const double *y, const double *theta, const double den_floor, const double penalty_weight, const double *r, double *jac) {
   /* n_z: extent of z (dimension 1) */
   /* n_y: extent of y (dimension 1) */
   int j;
   double h, theta1[6], r1[2 * n_z];
   j = 0;
   while (j < 6) {
      for (int p_fill = 0; p_fill < 6; ++p_fill) {
         theta1[p_fill] = theta[p_fill];
      }
      h = 1e-06 * (1.0 + fabs(theta[j]));
      theta1[j] += h;
      rational_residuals(n_z, z, n_y, y, theta1, den_floor, penalty_weight, r1);
      for (int p_fill = 0; p_fill < 2 * n_z; ++p_fill) {
         jac[p_fill + 2 * n_z * j] = (r1[p_fill] - r[p_fill])/h;
      }
      xf2c_loop_1_continue: ;
      j += 1;
   }
   xf2c_loop_1_break: ;
}

void fit_rational32(const int n_z, const double *z, const int n_y, const double *y, const double *theta0, const double den_floor, const double penalty_weight, double *theta, double *obj, int *iter_used) {
   /* n_z: extent of z (dimension 1) */
   /* n_y: extent of y (dimension 1) */
   enum { max_iter = 200 };
   int iter, j, info;
   const double tol = 1e-10;
   double lambda, obj_new, step_norm, r[2 * n_z], r_new[2 * n_z], jac[2 * n_z * 6], a[36], g[6], rhs[6];
   double delta[6], theta_new[6];
   for (int p_fill = 0; p_fill < 6; ++p_fill) {
      theta[p_fill] = theta0[p_fill];
   }
   lambda = 0.001;
   rational_residuals(n_z, z, n_y, y, theta, den_floor, penalty_weight, r);
   (*obj) = dot_product_1d_double(2 * n_z, r, r);
   (*iter_used) = 0;
   iter = 1;
   while (iter <= 200) {
      (*iter_used) = iter;
      rational_jacobian(n_z, z, n_y, y, theta, den_floor, penalty_weight, r, jac);
      for (int j_fill = 0; j_fill < 6; ++j_fill) {
         for (int i_fill = 0; i_fill < 6; ++i_fill) {
            double red = 0;
            for (int k_fill = 0; k_fill < 2*n_z; ++k_fill) red += jac[k_fill + 2 * n_z * i_fill] * jac[k_fill + 2 * n_z * j_fill];
            a[i_fill + 6 * j_fill] = red;
         }
      }
      for (int i_fill = 0; i_fill < 6; ++i_fill) {
         double red = 0;
         for (int k_fill = 0; k_fill < 2*n_z; ++k_fill) red += jac[k_fill + 2 * n_z * i_fill] * r[k_fill];
         g[i_fill] = red;
      }
      j = 0;
      while (j < 6) {
         a[j + 6 * j] += lambda;
         j += 1;
      }
      for (int p_fill = 0; p_fill < 6; ++p_fill) {
         rhs[p_fill] = -g[p_fill];
      }
      solve_linear(6, 6, a, 6, rhs, 6, delta, &info);
      if (info != 0) {
         lambda = fmin(lambda*10.0, 1.0e12);
         goto xf2c_loop_1_continue;
      }
      {
         double red = 0.0;
         for (int i_fill = 0; i_fill < 6; ++i_fill) red += delta[i_fill]*delta[i_fill];
         step_norm = sqrt(red);
      }
      if (step_norm < (1e-10)*(1.0 + (sqrt(({ double red = 0.0; for (int i_red = 0; i_red < 6; ++i_red) red += theta[i_red]*theta[i_red]; red; }))))) {
         goto xf2c_loop_1_break;
      }
      for (int p_fill = 0; p_fill < 6; ++p_fill) {
         theta_new[p_fill] = theta[p_fill] + delta[p_fill];
      }
      rational_residuals(n_z, z, n_y, y, theta_new, den_floor, penalty_weight, r_new);
      obj_new = dot_product_1d_double(2 * n_z, r_new, r_new);
      if (obj_new < (*obj)) {
         if ((fabs((*obj) - obj_new)) < (1e-10)*(1.0 + (*obj))) {
            for (int p_fill = 0; p_fill < 6; ++p_fill) {
               theta[p_fill] = theta_new[p_fill];
            }
            (*obj) = obj_new;
            goto xf2c_loop_1_break;
         }
         for (int p_fill = 0; p_fill < 6; ++p_fill) {
            theta[p_fill] = theta_new[p_fill];
         }
         for (int p_fill = 0; p_fill < 2 * n_z; ++p_fill) {
            r[p_fill] = r_new[p_fill];
         }
         (*obj) = obj_new;
         lambda = fmax(lambda*0.3, 1.0e-12);
      }
      else {
         lambda = fmin(lambda*10.0, 1.0e12);
      }
      xf2c_loop_1_continue: ;
      iter += 1;
   }
   xf2c_loop_1_break: ;
}

void make_knots(const int nknots, double *knots) {
   int j = 1;
   while (j <= nknots) {
      knots[j - 1] = -1.0 + 2.0*((double) j)/((double) (nknots + 1));
      xf2c_loop_1_continue: ;
      j += 1;
   }
   xf2c_loop_1_break: ;
}

void spline_basis(const int n_z, const double *z, const int n_knots, const double *knots, double *b) {
   /* n_z: extent of z (dimension 1) */
   /* n_knots: extent of knots (dimension 1) */
   int i, j;
   for (int p_fill = 0; p_fill < n_z; ++p_fill) {
      b[p_fill] = 1.0;
   }
   for (int p_fill = 0; p_fill < n_z; ++p_fill) {
      b[p_fill + n_z] = z[p_fill];
   }
   for (int p_fill = 0; p_fill < n_z; ++p_fill) {
      b[p_fill + n_z * 2] = z[p_fill] * z[p_fill];
   }
   for (int p_fill = 0; p_fill < n_z; ++p_fill) {
      b[p_fill + n_z * 3] = z[p_fill] * z[p_fill] * z[p_fill];
   }
   j = 1;
   while (j <= n_knots) {
      i = 0;
      while (i < n_z) {
         b[i + n_z * (j + 3)] = cubic_pos(z[i] - knots[j - 1]);
         i += 1;
      }
      xf2c_loop_1_continue: ;
      j += 1;
   }
   xf2c_loop_1_break: ;
}

void fit_penalized_cubic_spline(const int n_z, const double *z, const int n_y, const double *y, const int nknots, const double lambda, double *knots, double *coef) {
   /* n_z: extent of z (dimension 1) */
   /* n_y: extent of y (dimension 1) */
   double b[n_z * (nknots + 4)];
   double lambda_diag[nknots + 4];
   make_knots(nknots, knots);
   spline_basis(n_z, z, nknots, knots, b);
   for (int i_fill = 0; i_fill < nknots + 4; ++i_fill) {
      lambda_diag[i_fill] = 0.0;
   }
   if (nknots > 0) {
      if (1 > 0) {
         for (int i_fill = 5, p_fill = 0; i_fill <= nknots + 4; i_fill += 1, ++p_fill) {
            lambda_diag[i_fill - 1] = lambda;
         }
      } else {
         for (int i_fill = 5, p_fill = 0; i_fill >= nknots + 4; i_fill += 1, ++p_fill) {
            lambda_diag[i_fill - 1] = lambda;
         }
      }
   }
   solve_least_squares(n_z, 4 + nknots, b, n_y, y, 4 + nknots, coef, 4 + nknots, lambda_diag);
}

void eval_penalized_cubic_spline(const int n_z, const double *z, const int n_knots, const double *knots, const double *coef, double *yhat) {
   /* n_z: extent of z (dimension 1) */
   /* n_knots: extent of knots (dimension 1) */
   double b[n_z * (n_knots + 4)];
   spline_basis(n_z, z, n_knots, knots, b);
   for (int i_fill = 0; i_fill < n_z; ++i_fill) {
      double red = 0;
      for (int k_fill = 0; k_fill < 4 + n_knots; ++k_fill) red += b[i_fill + n_z * k_fill] * coef[k_fill];
      yhat[i_fill] = red;
   }
}

int main(void) {
   enum { n = 300 };
   enum { seed = 123 };
   enum { nknots = 10 };
   const double x_min = -4.0, x_max = 4.0, noise_sd = 0.15, k = 2.0, lam_true = 0.4, c_lin = 0.25;
   const double a_log = 1.0, b_log = 0.0, den_floor = 0.15, penalty_weight = 10.0, spline_lambda = 1.0e-3;
   const char *true_name = "sin";
   int i, iter_rat;
   double obj_rat, min_abs_den;
   double *x = NULL, *z = NULL, *y_true = NULL, *y = NULL, *y_rat = NULL, *y_poly = NULL, *y_spline = NULL;
   double *den = NULL, *theta0 = NULL, *theta_rat = NULL, *coef_poly = NULL, *knots = NULL;
   double *coef_spline = NULL;
   x = (double*) malloc(sizeof(double) * 300);
   if (!x) return 1;
   z = (double*) malloc(sizeof(double) * 300);
   if (!z) return 1;
   y_true = (double*) malloc(sizeof(double) * 300);
   if (!y_true) return 1;
   y = (double*) malloc(sizeof(double) * 300);
   if (!y) return 1;
   y_rat = (double*) malloc(sizeof(double) * 300);
   if (!y_rat) return 1;
   y_poly = (double*) malloc(sizeof(double) * 300);
   if (!y_poly) return 1;
   y_spline = (double*) malloc(sizeof(double) * 300);
   if (!y_spline) return 1;
   den = (double*) malloc(sizeof(double) * 300);
   if (!den) return 1;
   theta0 = (double*) malloc(sizeof(double) * 6);
   if (!theta0) return 1;
   theta_rat = (double*) malloc(sizeof(double) * 6);
   if (!theta_rat) return 1;
   coef_poly = (double*) malloc(sizeof(double) * 4);
   if (!coef_poly) return 1;
   knots = (double*) malloc(sizeof(double) * 10);
   if (!knots) return 1;
   coef_spline = (double*) malloc(sizeof(double) * 14);
   if (!coef_spline) return 1;
   set_seed(123);
   i = 0;
   while (i < 300) {
      x[i] = (-(4.0)) + (4.0 + 4.0)*((double) i)/((double) 299);
      xf2c_loop_1_continue: ;
      i += 1;
   }
   xf2c_loop_1_break: ;
   fill_true_values(300, x, y_true, true_name, (2.0), (0.4), (0.25), (1.0), (0.0));
   i = 0;
   while (i < 300) {
      y[i] = y_true[i] + 0.15 * normal_rand();
      i += 1;
   }
   scale_x(300, x, z);
   theta0[0] = 0.0;
   theta0[1] = 1.0;
   theta0[2] = 0.0;
   theta0[3] = 0.0;
   theta0[4] = 0.0;
   theta0[5] = 0.0;
   fit_rational32(300, z, 300, y, theta0, (0.15), (10.0), theta_rat, &obj_rat, &iter_rat);
   rational32(300, z, theta_rat, y_rat, den);
   fit_cubic_poly(300, z, 300, y, coef_poly);
   eval_cubic_poly(300, z, coef_poly, y_poly);
   fit_penalized_cubic_spline(300, z, 300, y, 10, (0.001), knots, coef_spline);
   eval_penalized_cubic_spline(300, z, 10, knots, coef_spline, y_spline);
   min_abs_den = ({ double red = DBL_MAX; for (int i_red = 0; i_red < n; ++i_red) if ((fabs(den[i_red])) < red) red = (fabs(den[i_red])); red; });
   printf("\n");
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "true function name: ");
      first = 0;
      printf("%s%s", first ? "" : "", trim_s(true_name));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "k        = ");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", (2.0));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "lam_true = ");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", (0.4));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "c_lin    = ");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", (0.25));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "a_log    = ");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", (1.0));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "b_log    = ");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", (0.0));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "noise_sd = ");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", (0.15));
      first = 0;
      printf("\n");
   }
   printf("\n");
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "rational (3,2) fit:");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "iterations                 = ");
      first = 0;
      printf("%s%d", first ? "" : " ", iter_rat);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "objective                  = ");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", obj_rat);
      first = 0;
      printf("\n");
   }
   printf("%s\n", "theta [a0,a1,a2,a3,b1,b2] = ");
   {
      int first = 1;
      for (int i_pr = 0; i_pr < 6; ++i_pr) {
         if (first) printf("%13.6f", theta_rat[i_pr]);
         else printf("    %13.6f", theta_rat[i_pr]);
         first = 0;
      }
      printf("    \n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "rmse vs true               = ");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", rmse(300, y_rat, 300, y_true));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "rmse vs noisy data         = ");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", rmse(300, y_rat, 300, y));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "min(abs(denominator))      = ");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", min_abs_den);
      first = 0;
      printf("\n");
   }
   printf("\n");
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "cubic polynomial fit:");
      first = 0;
      printf("\n");
   }
   printf("%s\n", "coef [c0,c1,c2,c3] = ");
   {
      int first = 1;
      for (int i_pr = 0; i_pr < 4; ++i_pr) {
         if (first) printf("%13.6f", coef_poly[i_pr]);
         else printf("    %13.6f", coef_poly[i_pr]);
         first = 0;
      }
      printf("    \n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "rmse vs true       = ");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", rmse(300, y_poly, 300, y_true));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "rmse vs noisy data = ");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", rmse(300, y_poly, 300, y));
      first = 0;
      printf("\n");
   }
   printf("\n");
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "penalized cubic spline fit:");
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "nknots             = ");
      first = 0;
      printf("%s%d", first ? "" : " ", 10);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "spline_lambda      = ");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", (0.001));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "rmse vs true       = ");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", rmse(300, y_spline, 300, y_true));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "rmse vs noisy data = ");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", rmse(300, y_spline, 300, y));
      first = 0;
      printf("\n");
   }
   printf("\n");
   printf("%s\n", "first five rows: x, y_true, y, y_rat, y_poly, y_spline");
   i = 0;
   while (i < (fmin(5, 300))) {
      {
         int first = 1;
         printf("%s%13.6f", first ? "" : " ", x[i]);
         first = 0;
         printf("%s%13.6f", first ? "" : " ", y_true[i]);
         first = 0;
         printf("%s%13.6f", first ? "" : " ", y[i]);
         first = 0;
         printf("%s%13.6f", first ? "" : " ", y_rat[i]);
         first = 0;
         printf("%s%13.6f", first ? "" : " ", y_poly[i]);
         first = 0;
         printf("%s%13.6f", first ? "" : " ", y_spline[i]);
         first = 0;
         printf("\n");
      }
      i += 1;
   }
   free(x);
   free(z);
   free(y_true);
   free(y);
   free(y_rat);
   free(y_poly);
   free(y_spline);
   free(den);
   free(theta0);
   free(theta_rat);
   free(coef_poly);
   free(knots);
   free(coef_spline);
   return 0;
}
