/* Generated by xf2c.py from xrational_approx_rng_poly.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"


void seed_rng(const int seed);
void local_random_number(double * x);
void set_seed(const int seed);
double normal_rand();
double rmse(const int n_yhat, const double *yhat, const int n_y, const double *y);
void solve_linear(const int n_a_in_1, const int n_a_in_2, const double *a_in, const int n_b_in, const double *b_in, const int n_x, double *x, int *info);
void solve_least_squares(const int n_a_1, const int n_a_2, const double *a, const int n_y, const double *y, const int n_coef, double *coef);
void fill_true_values(const int n, const double *x, double *y, const double k);
void scale_x(const int n, const double *x, double *z);
void fit_cubic_poly(const int n_z, const double *z, const int n_y, const double *y, double *coef);
void eval_cubic_poly(const int n, const double *z, const double *coef, double *yhat);

void seed_rng(const int seed) {
   rng_seed(((long long) seed));
}

void local_random_number(double * x) {
   (*x) = ((double) (runif()));
}

void set_seed(const int seed) {
   seed_rng(seed);
}

double normal_rand() {
   double result, u1, u2, pi;
   pi = acos(-(1.0));
   local_random_number(&u1);
   local_random_number(&u2);
   if (u1 < 1.0e-12) {
      u1 = 1e-12;
   }
   result = sqrt(-(2.0) * log(u1)) * cos(2.0 * pi * u2);
   return result;
}

double rmse(const int n_yhat, const double *yhat, const int n_y, const double *y) {
   /* n_yhat: extent of yhat (dimension 1) */
   /* n_y: extent of y (dimension 1) */
   double result;
   {
      double red = 0.0;
      for (int i_fill = 0; i_fill < n_yhat; ++i_fill) red += ((yhat[i_fill] - y[i_fill]) * (yhat[i_fill] - y[i_fill]));
      result = (sqrt(red/((double) n_y)));
   }
   return result;
}

void solve_linear(const int n_a_in_1, const int n_a_in_2, const double *a_in, const int n_b_in, const double *b_in, const int n_x, double *x, int *info) {
   /* n_a_in_1: extent of a_in (dimension 1) */
   /* n_a_in_2: extent of a_in (dimension 2) */
   /* n_b_in: extent of b_in (dimension 1) */
   /* n_x: extent of x (dimension 1) */
   int i, k, piv;
   double a[n_a_in_1 * n_a_in_2], b[n_b_in], factor, tmp, rowtmp[n_a_in_2];
   if (n_a_in_1 != n_b_in || n_a_in_2 != n_b_in || n_x != n_b_in) {
      (*info) = -1;
      return;
   }
   for (int i_fill = 0; i_fill < n_a_in_1 * n_a_in_2; ++i_fill) {
      a[i_fill] = a_in[i_fill];
   }
   for (int p_fill = 0; p_fill < n_b_in; ++p_fill) {
      b[p_fill] = b_in[p_fill];
   }
   (*info) = 0;
   k = 1;
   while (k <= n_b_in - 1) {
      piv = k;
      i = k + 1;
      while (i <= n_b_in) {
         if ((fabs(a[i - 1 + n_a_in_1 * (k - 1)])) > (fabs(a[piv - 1 + n_a_in_1 * (k - 1)]))) {
            piv = i;
         }
         i += 1;
      }
      if ((fabs(a[piv - 1 + n_a_in_1 * (k - 1)])) < 1.0e-14) {
         (*info) = k;
         return;
      }
      if (piv != k) {
         for (int p_fill = 0; p_fill < ((((n_a_in_2 - 1) / 1 + 1))); ++p_fill) {
            rowtmp[p_fill] = a[k - 1 + n_a_in_1 * p_fill];
         }
         for (int p_fill = 0; p_fill < n_a_in_2; ++p_fill) {
            a[k - 1 + n_a_in_1 * p_fill] = a[piv - 1 + n_a_in_1 * p_fill];
         }
         for (int p_fill = 0; p_fill < n_a_in_2; ++p_fill) {
            a[piv - 1 + n_a_in_1 * p_fill] = rowtmp[p_fill];
         }
         tmp = b[k - 1];
         b[k - 1] = b[piv - 1];
         b[piv - 1] = tmp;
      }
      i = k + 1;
      while (i <= n_b_in) {
         factor = a[i - 1 + n_a_in_1 * (k - 1)]/a[k - 1 + n_a_in_1 * (k - 1)];
         for (int p_fill = 0; p_fill < (((n_b_in - k) / 1 + 1)); ++p_fill) {
            a[i - 1 + n_a_in_1 * (k + p_fill - 1)] = a[i - 1 + n_a_in_1 * (k + p_fill - 1)] - factor * a[k - 1 + n_a_in_1 * (k + p_fill - 1)];
         }
         b[i - 1] -= factor*b[k - 1];
         i += 1;
      }
      k += 1;
   }
   if ((fabs(a[n_b_in - 1 + n_a_in_1 * (n_b_in - 1)])) < 1.0e-14) {
      (*info) = n_b_in;
      return;
   }
   x[n_b_in - 1] = b[n_b_in - 1]/a[n_b_in - 1 + n_a_in_1 * (n_b_in - 1)];
   i = n_b_in - 1;
   while (i >= 1) {
      x[i - 1] = (b[i - 1] - ({ double red = 0.0; for (int i_red = 0; i_red < ((((n_b_in - i - 1) / 1 + 1))); ++i_red) red += (a[i - 1 + n_a_in_1 * (i + i_red)]) * (x[i + i_red]); red; }))/a[i - 1 + n_a_in_1 * (i - 1)];
      i += -1;
   }
}

void solve_least_squares(const int n_a_1, const int n_a_2, const double *a, const int n_y, const double *y, const int n_coef, double *coef) {
   /* n_a_1: extent of a (dimension 1) */
   /* n_a_2: extent of a (dimension 2) */
   /* n_y: extent of y (dimension 1) */
   /* n_coef: extent of coef (dimension 1) */
   int info;
   double ata[n_coef * n_coef], aty[n_coef];
   for (int j_fill = 0; j_fill < n_a_2; ++j_fill) {
      for (int i_fill = 0; i_fill < n_a_2; ++i_fill) {
         double red = 0;
         for (int k_fill = 0; k_fill < n_a_1; ++k_fill) red += a[k_fill + n_a_1 * i_fill] * a[k_fill + n_a_1 * j_fill];
         ata[i_fill + n_a_2 * j_fill] = red;
      }
   }
   for (int i_fill = 0; i_fill < n_a_2; ++i_fill) {
      double red = 0;
      for (int k_fill = 0; k_fill < n_a_1; ++k_fill) red += a[k_fill + n_a_1 * i_fill] * y[k_fill];
      aty[i_fill] = red;
   }
   solve_linear(n_coef, n_coef, ata, n_coef, aty, n_coef, coef, &info);
   if (info != 0) {
      fprintf(stderr, "%s\n", "solve_least_squares failed");
      exit(1);
   }
}

void fill_true_values(const int n, const double *x, double *y, const double k) {
   /* n: extent of x (dimension 1) */
   int i = 1;
   while (i <= n) {
      y[i - 1] = sin(k * x[i - 1]);
      i += 1;
   }
}

void scale_x(const int n, const double *x, double *z) {
   /* n: extent of x (dimension 1) */
   double xmin, xmax;
   xmin = minval_1d_double(n, x);
   xmax = maxval_1d_double(n, x);
   for (int p_fill = 0; p_fill < n; ++p_fill) {
      z[p_fill] = 2.0*(x[p_fill] - xmin)/(xmax - xmin) - 1.0;
   }
}

void fit_cubic_poly(const int n_z, const double *z, const int n_y, const double *y, double *coef) {
   /* n_z: extent of z (dimension 1) */
   /* n_y: extent of y (dimension 1) */
   double a[n_z * 4];
   for (int p_fill = 0; p_fill < n_z; ++p_fill) {
      a[p_fill] = 1.0;
   }
   for (int p_fill = 0; p_fill < n_z; ++p_fill) {
      a[p_fill + n_z] = z[p_fill];
   }
   for (int p_fill = 0; p_fill < n_z; ++p_fill) {
      a[p_fill + n_z * 2] = z[p_fill] * z[p_fill];
   }
   for (int p_fill = 0; p_fill < n_z; ++p_fill) {
      a[p_fill + n_z * 3] = z[p_fill] * z[p_fill] * z[p_fill];
   }
   solve_least_squares(n_z, 4, a, n_y, y, 4, coef);
}

void eval_cubic_poly(const int n, const double *z, const double *coef, double *yhat) {
   /* n: extent of z (dimension 1) */
   for (int p_fill = 0; p_fill < n; ++p_fill) {
      yhat[p_fill] = coef[0] + coef[1] * z[p_fill] + coef[2] * z[p_fill] * z[p_fill] + coef[3] * z[p_fill] * z[p_fill] * z[p_fill];
   }
}

int main(void) {
   enum { n = 300 };
   enum { seed = 123 };
   const double x_min = -4.0, x_max = 4.0, noise_sd = 0.15, k = 2.0;
   int i;
   double *coef = NULL, *x = NULL, *y = NULL, *y_poly = NULL, *y_true = NULL, *z = NULL;
   coef = (double*) malloc(sizeof(double) * 4);
   if (!coef) return 1;
   x = (double*) malloc(sizeof(double) * 300);
   if (!x) return 1;
   y = (double*) malloc(sizeof(double) * 300);
   if (!y) return 1;
   y_poly = (double*) malloc(sizeof(double) * 300);
   if (!y_poly) return 1;
   y_true = (double*) malloc(sizeof(double) * 300);
   if (!y_true) return 1;
   z = (double*) malloc(sizeof(double) * 300);
   if (!z) return 1;
   set_seed(123);
   i = 0;
   while (i < 300) {
      x[i] = (-(4.0)) + (4.0 + 4.0)*((double) i)/((double) 299);
      i += 1;
   }
   fill_true_values(300, x, y_true, (2.0));
   i = 0;
   while (i < 300) {
      y[i] = y_true[i] + 0.15 * normal_rand();
      i += 1;
   }
   scale_x(300, x, z);
   fit_cubic_poly(300, z, 300, y, coef);
   eval_cubic_poly(300, z, coef, y_poly);
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "cubic polynomial fit with local MT RNG");
      first = 0;
      printf("\n");
   }
   printf("%s\n", "coef:");
   {
      int first = 1;
      for (int i_pr = 0; i_pr < 4; ++i_pr) {
         if (first) printf("%13.6f", coef[i_pr]);
         else printf("    %13.6f", coef[i_pr]);
         first = 0;
      }
      printf("    \n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "rmse vs true =");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", rmse(300, y_poly, 300, y_true));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "rmse vs noisy data =");
      first = 0;
      printf("%s%13.6f", first ? "" : " ", rmse(300, y_poly, 300, y));
      first = 0;
      printf("\n");
   }
   printf("%s\n", "first five rows: x, y_true, y, y_poly");
   i = 0;
   while (i < 5) {
      {
         int first = 1;
         printf("%s%13.6f", first ? "" : " ", x[i]);
         first = 0;
         printf("%s%13.6f", first ? "" : " ", y_true[i]);
         first = 0;
         printf("%s%13.6f", first ? "" : " ", y[i]);
         first = 0;
         printf("%s%13.6f", first ? "" : " ", y_poly[i]);
         first = 0;
         printf("\n");
      }
      i += 1;
   }
   free(coef);
   free(x);
   free(y);
   free(y_poly);
   free(y_true);
   free(z);
   return 0;
}
