/* Generated by xf2c.py from xread_words.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"

static int argext_read_words_line_words = 0;

void read_words_line(const int iu, char ***words__arg, int *nread, char * *label); /* read words from line, where the line has the # of words followed by the words */

void read_words_line(const int iu, char ***words__arg, int *nread, char * *label) {
   /* read words from line, where the line has the # of words followed by the words */
   #define words (*words__arg)
   int n_words = argext_read_words_line_words;
   enum { text_len = 10000 };
   char text[text_len + 1] = "";
   int ierr, nw;
   if (read_a(iu, text, text_len) != 0) return;
   ierr = read_first_int_s(text, &nw);
   if (ierr != 0) {
      printf(" %s\n", "in read_words_line, could not read integer from '\" // trim(text) // \"', STOPPING");
      exit(0);
   }
   if (nw > 0) {
      if (words) free_str_array(words, n_words);
      words = (char**) malloc(sizeof(char*) * nw);
      if (!words && nw > 0) return;
      for (int i_fill = 0; i_fill < nw; ++i_fill) words[i_fill] = NULL;
      n_words = nw;
      for (int i_fill = 0; i_fill < nw; ++i_fill) assign_str_alloc(&words[i_fill], "");
      ierr = read_words_after_int_s(text, nw, words);
      if (ierr != 0) {
         printf("%s%12d%s\n", "in read_words_line, could not read", nw, " words from '\" // trim(text) // \"', STOPPING");
         exit(0);
      }
   }
   else {
      if (words) free_str_array(words, n_words);
      words = (char**) malloc(sizeof(char*) * 0);
      if (!words && 0 > 0) return;
      for (int i_fill = 0; i_fill < 0; ++i_fill) words[i_fill] = NULL;
      n_words = 0;
      for (int i_fill = 0; i_fill < 0; ++i_fill) assign_str_alloc(&words[i_fill], "");
   }
   if ((nread != NULL)) {
      (*nread) = n_words;
   }
   if ((label != NULL)) {
      printf(" %s\n", concat_s2(trim_s((*label)), ":"));
   }
   argext_read_words_line_words = n_words;
   #undef words
}

int main(void) {
   enum { iu = 20 };
   const char *xfile = "words.txt";
   char **words = NULL;
   int n_words = 0, nread;
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "hi");
      first = 0;
      printf("\n");
   }
   if (open_unit(20, trim_s(xfile), "write", "replace") != 0) return 1;
   {
      const char *write_words[] = {"dog", "cat", "bird"};
      write_i0_then_words(20, 3, 3, write_words);
   }
   close_unit(20);
   if (open_unit(20, trim_s(xfile), "read", "old") != 0) return 1;
   {
   argext_read_words_line_words = n_words;
      read_words_line(20, &words, &nread, &((char *){concat_s2("words from ", xfile)}));
   n_words = argext_read_words_line_words;
   }
   for (int i_fmt = 0; i_fmt < n_words; ++i_fmt) {
      printf("%10s", words[i_fmt]);
   }
   printf("\n");
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "bye");
      first = 0;
      printf("\n");
   }
   free_str_array(words, n_words);
   return 0;
}
