/* Generated by xf2c.py from xread_star.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"

int main(void) {
   int iu, i;
   iu = alloc_unit();
   if (open_unit(iu, trim_s("nums.txt"), "read", "old") != 0) return 1;
   if (skip_record_unit(iu) != 0) return 1;
   if (read_first_int_unit(iu, &i) != 0) return 1;
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "i =");
      first = 0;
      printf("%s%d", first ? "" : " ", i);
      first = 0;
      printf("\n");
   }
   if (skip_record_unit(iu) != 0) return 1;
   if (read_first_int_unit(iu, &i) != 0) return 1;
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "i =");
      first = 0;
      printf("%s%d", first ? "" : " ", i);
      first = 0;
      printf("\n");
   }
   return 0;
}
