/* Generated by xf2c.py from xread.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"

int main(void) {
   int ios, iu = 20;
   const char *xfile = "data.txt";
   enum { text_len = 100 };
   char text[text_len + 1] = "abc";
   if (open_unit(iu, trim_s(xfile), "write", "replace") != 0) return 1;
   write_a(iu, text);
   close_unit(iu);
   if (open_unit(iu, trim_s(xfile), "read", "old") != 0) return 1;
   ios = read_a(iu, text, text_len);
   if (ios == 0) {
      {
         int first = 1;
         printf("%s%s", first ? "" : " ", trim_s(text));
         first = 0;
         printf("\n");
      }
   }
   else {
      {
         int first = 1;
         printf("%s%s", first ? "" : " ", "ios =");
         first = 0;
         printf("%s%d", first ? "" : " ", ios);
         first = 0;
         printf("\n");
      }
   }
   return 0;
}
