/* Generated by xf2c.py from xrepeat_long.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"

int main(void) {
   enum { s_len = 1105 };
   char s[s_len + 1] = "";
   assign_str(s, s_len, repeat_s("a", 1100));
   {
      int first = 1;
      printf("%s%d", first ? "" : " ", len_trim_s(s));
      first = 0;
      printf("\n");
   }
   return 0;
}
