/* Generated by xf2c.py from xreshape_order.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

void print_i2(const int n_x_1, const int n_x_2, const int *x);

void print_i2(const int n_x_1, const int n_x_2, const int *x) {
   /* n_x_1: extent of x (dimension 1) */
   /* n_x_2: extent of x (dimension 2) */
   int i = 1;
   while (i <= n_x_1) {
      for (int j_fmt = 0; j_fmt < n_x_2; ++j_fmt) {
         printf("%6d", x[i - 1 + n_x_1 * j_fmt]);
      }
      printf("\n");
      i += 1;
   }
}

int main(void) {
   int *a23 = NULL, *a32 = NULL, *a222 = NULL, *b = NULL, *c = NULL;
   a23 = (int*) malloc(sizeof(int) * 6);
   if (!a23) return 1;
   a32 = (int*) malloc(sizeof(int) * 6);
   if (!a32) return 1;
   a222 = (int*) malloc(sizeof(int) * 8);
   if (!a222) return 1;
   b = (int*) malloc(sizeof(int) * 8);
   if (!b) return 1;
   c = (int*) malloc(sizeof(int) * 6);
   if (!c) return 1;
   if (0 < 6) a23[0] = 1;
   if (1 < 6) a23[1] = 2;
   if (2 < 6) a23[2] = 3;
   if (3 < 6) a23[3] = 4;
   if (4 < 6) a23[4] = 5;
   if (5 < 6) a23[5] = 6;
   for (int i_fill = 6; i_fill < 6; ++i_fill) {
      a23[i_fill] = a23[i_fill % 6];
   }
   printf("%s\n", "example 1: a23 = reshape([1,2,3,4,5,6], [2,3])");
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "a23(1,:) =");
      first = 0;
      for (int j_pr = 0; j_pr < 3; ++j_pr) {
         printf("%s%d", first ? "" : " ", a23[2 * j_pr]);
         first = 0;
      }
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "a23(2,:) =");
      first = 0;
      for (int j_pr = 0; j_pr < 3; ++j_pr) {
         printf("%s%d", first ? "" : " ", a23[1 + 2 * j_pr]);
         first = 0;
      }
      printf("\n");
   }
   printf("%s\n", "a23 =");
   print_i2(2, 3, a23);
   printf("\n");
   if (0 < 6) a32[0] = 1;
   if (1 < 6) a32[1] = 2;
   if (2 < 6) a32[2] = 3;
   if (3 < 6) a32[3] = 4;
   if (4 < 6) a32[4] = 5;
   if (5 < 6) a32[5] = 6;
   for (int i_fill = 6; i_fill < 6; ++i_fill) {
      a32[i_fill] = a32[i_fill % 6];
   }
   printf("%s\n", "example 2: a32 = reshape([1,2,3,4,5,6], [3,2])");
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "a32(:,1) =");
      first = 0;
      for (int i_pr = 0; i_pr < 3; ++i_pr) {
         printf("%s%d", first ? "" : " ", a32[i_pr]);
         first = 0;
      }
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "a32(:,2) =");
      first = 0;
      for (int i_pr = 0; i_pr < 3; ++i_pr) {
         printf("%s%d", first ? "" : " ", a32[i_pr + 3]);
         first = 0;
      }
      printf("\n");
   }
   printf("%s\n", "a32 =");
   print_i2(3, 2, a32);
   printf("\n");
   if (0 < 8) a222[0] = 1;
   if (1 < 8) a222[1] = 2;
   if (2 < 8) a222[2] = 3;
   if (3 < 8) a222[3] = 4;
   if (4 < 8) a222[4] = 5;
   if (5 < 8) a222[5] = 6;
   if (6 < 8) a222[6] = 7;
   if (7 < 8) a222[7] = 8;
   for (int i_fill = 8; i_fill < 8; ++i_fill) {
      a222[i_fill] = a222[i_fill % 8];
   }
   printf("%s\n", "example 3: a222 = reshape([1,2,3,4,5,6,7,8], [2,2,2])");
   printf("%s\n", "a222(:,:,1) =");
   print_i2(2, 2, &a222[0]);
   printf("%s\n", "a222(:,:,2) =");
   print_i2(2, 2, &a222[4]);
   printf("\n");
   if (0 < 8) b[0] = 1;
   if (1 < 8) b[1] = 2;
   if (2 < 8) b[2] = 3;
   int pad_0 = 9, pad_1 = 8;
   for (int i_fill = 3; i_fill < 8; ++i_fill) {
      switch ((i_fill - 3) % 2) {
      case 0: b[i_fill] = pad_0; break;
      case 1: b[i_fill] = pad_1; break;
      default: break;
      }
   }
   printf("%s\n", "example 4: reshape([1,2,3], [2,4], pad=[9,8])");
   printf("%s\n", "b =");
   print_i2(2, 4, b);
   printf("\n");
   {
      int reshape_src[] = {1, 2, 3, 4, 5, 6};
      int reshape_pos = 0;
      for (int r1 = 0; r1 < 2; ++r1) {
         for (int r2 = 0; r2 < 3; ++r2) {
            c[r1 + 2 * r2] = reshape_src[reshape_pos % 6];
            reshape_pos += 1;
         }
      }
   }
   printf("%s\n", "example 5: reshape([1,2,3,4,5,6], [2,3], order=[2,1])");
   printf("%s\n", "c =");
   print_i2(2, 3, c);
   printf("\n");
   free(a23);
   free(a32);
   free(a222);
   free(b);
   free(c);
   return 0;
}
