/* Generated by xf2c.py from xreturns_stats.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"

const int dp = 8;

double mean(const int n, const double *x); /* return the mean of a real vector */
double sd(const int n, const double *x); /* return the sample standard deviation of a real vector */
void print_corr_matrix(const int n_x_1, const int n_x_2, const double *x, const int n, char **names); /* print the sample correlation matrix of the columns of x */

double mean(const int n, const double *x) {
   /* return the mean of a real vector */
   /* n: extent of x (dimension 1) */
   double mu;
   /* f90: mu = sum(x) / real(n, kind=dp) */
   {
      double red = 0.0;
      for (int i_fill = 0; i_fill < n; ++i_fill) red += x[i_fill];
      mu = red / ((double) n);
   }
   return mu;
}

double sd(const int n, const double *x) {
   /* return the sample standard deviation of a real vector */
   /* n: extent of x (dimension 1) */
   double sig, mu;
   /* f90: if (n <= 1) then */
   if (n <= 1) {
      /* f90: sig = 0.0_dp */
      sig = 0.0;
   }
   else {
      /* f90: mu = mean(x) */
      mu = mean(n, x);
      /* f90: sig = sqrt(sum((x - mu)**2) / real(n - 1, kind=dp)) */
      {
         double red = 0.0;
         for (int i_fill = 0; i_fill < n; ++i_fill) red += ((x[i_fill] - mu) * (x[i_fill] - mu));
         sig = (sqrt(red / ((double) (n - 1))));
      }
   }
   return sig;
}

void print_corr_matrix(const int n_x_1, const int n_x_2, const double *x, const int n, char **names) {
   /* print the sample correlation matrix of the columns of x */
   /* n_x_1: extent of x (dimension 1) */
   /* n_x_2: extent of x (dimension 2) */
   /* n: extent of names (dimension 1) */
   double *mu = NULL, *sig = NULL, *corr = NULL;
   int n_mu = 0, n_sig = 0, n_corr_1 = 0, n_corr_2 = 0, nobs, nvar, i, j;
   /* f90: nobs = n_x_1 */
   nobs = n_x_1;
   /* f90: nvar = n_x_2 */
   nvar = n_x_2;
   /* f90: if (n /= nvar) then */
   if (n != nvar) {
      /* f90: error stop "size(names) must match number of columns of x" */
      fprintf(stderr, "%s\n", "size(names) must match number of columns of x");
      exit(1);
   }
   /* f90: if (nobs <= 1) then */
   if (nobs <= 1) {
      /* f90: error stop "need at least two rows to compute correlations" */
      fprintf(stderr, "%s\n", "need at least two rows to compute correlations");
      exit(1);
   }
   /* f90: allocate(mu(nvar), sig(nvar), corr(nvar, nvar)) */
   if (mu) free(mu);
   mu = (double*) malloc(sizeof(double) * nvar);
   if (!mu && nvar > 0) return;
   n_mu = nvar;
   if (sig) free(sig);
   sig = (double*) malloc(sizeof(double) * nvar);
   if (!sig && nvar > 0) return;
   n_sig = nvar;
   if (corr) free(corr);
   corr = (double*) malloc(sizeof(double) * nvar * nvar);
   if (!corr && (nvar * nvar) > 0) return;
   n_corr_1 = nvar;
   n_corr_2 = nvar;
   /* f90: do j = 1, nvar */
   j = 1;
   while (j <= nvar) {
      /* f90: mu(j) = mean(x(:, j)) */
      mu[j - 1] = mean(n_x_1, &x[n_x_1 * (j - 1)]);
      /* f90: sig(j) = sd(x(:, j)) */
      sig[j - 1] = sd(n_x_1, &x[n_x_1 * (j - 1)]);
      j += 1;
   }
   xf2c_loop_1_break: ;
   /* f90: do i = 1, nvar */
   i = 1;
   while (i <= nvar) {
      /* f90: do j = 1, nvar */
      j = 1;
      while (j <= nvar) {
         /* f90: if (sig(i) == 0.0_dp .or. sig(j) == 0.0_dp) then */
         if (sig[i - 1] == 0.0 || sig[j - 1] == 0.0) {
            /* f90: corr(i, j) = 0.0_dp */
            corr[i - 1 + n_corr_1 * (j - 1)] = 0.0;
         }
         else {
            /* f90: corr(i, j) = sum((x(:, i) - mu(i)) * (x(:, j) - mu(j))) /                       (real(nobs - 1, kind=dp) * sig(i) * sig(j)) */
            {
               double red = 0.0;
               for (int i_fill = 0; i_fill < (((n_x_1 - 1) / 1 + 1)); ++i_fill) red += (x[i_fill + n_x_1 * (i - 1)] - mu[i - 1]) * (x[i_fill + n_x_1 * (j - 1)] - mu[j - 1]);
               corr[i - 1 + n_corr_1 * (j - 1)] = red /                       (((double) (nobs - 1)) * sig[i - 1] * sig[j - 1]);
            }
         }
         j += 1;
      }
      i += 1;
   }
   /* f90: write(*, "(/,a)") "correlation matrix of returns" */
   printf("\n");
   printf("%s", "correlation matrix of returns");
   printf("\n");
   /* f90: write (*,"(*(a8))") "", (trim(names(j)), j = 1, nvar) */
   printf("%8s", "");
   {
      for (j = 1; j <= nvar; ++j) {
         printf("%8s", trim_s(names[j - 1]));
      }
      printf("\n");
   }
   /* f90: do i = 1, nvar */
   i = 1;
   while (i <= nvar) {
      /* f90: write(*, "(a8,*(f8.3))") trim(names(i)), corr(i,:) */
      /* (corr(i, j), j = 1, nvar) */
      printf("%8s", trim_s(names[i - 1]));
      for (int j_fmt = 0; j_fmt < n_corr_2; ++j_fmt) {
         printf("%8.3f", corr[i - 1 + n_corr_1 * j_fmt]);
      }
      printf("\n");
      i += 1;
   }
}

int main(int argc, char **argv) {
   enum { filename_len = 256, line_len = 4096, first_date_len = 32, last_date_len = 32 };
   char filename[filename_len + 1] = "", line[line_len + 1] = "", first_date[first_date_len + 1] = "";
   char last_date[last_date_len + 1] = "";
   char **names = NULL, **fields = NULL;
   int n_names = 0, n_fields = 0, n_prices_1 = 0, n_prices_2 = 0, n_rets_1 = 0, n_rets_2 = 0, n_mu = 0;
   int n_sig = 0, iu, ios, n_assets, nobs, i, j;
   double *prices = NULL, *rets = NULL, *mu = NULL, *sig = NULL;
   const double ret_scale = 100.0;
   /* f90: call get_command_argument(1, filename) */
   assign_str(filename, filename_len, (1 < argc) ? argv[1] : "");
   /* f90: if (len_trim(filename) == 0) then */
   if (len_trim_s(filename) == 0) {
      /* f90: filename = "spy_efa_eem_tlt_lqd.csv" */
      assign_str(filename, filename_len, "spy_efa_eem_tlt_lqd.csv");
   }
   /* f90: open(newunit=iu, file=trim(filename), status="old", action="read", iostat=ios) */
   iu = alloc_unit();
   ios = open_unit(iu, trim_s(trim_s(filename)), "read", "old");
   /* f90: if (ios /= 0) then */
   if (ios != 0) {
      /* f90: error stop "cannot open input file " // trim(filename) */
      fprintf(stderr, "%s\n", concat_s2("cannot open input file ", trim_s(filename)));
      return 1;
   }
   /* f90: if (ret_scale /= 1.0_dp) then */
   if ((100.0) != 1.0) {
      /* f90: print "('return scaling: ',f0.4)", ret_scale */
      printf("%s", "return scaling: ");
      printf("%.4f", (100.0));
      printf("\n");
   }
   /* f90: read(iu, "(a)", iostat=ios) line */
   ios = read_a(iu, line, line_len);
   /* f90: if (ios /= 0) then */
   if (ios != 0) {
      /* f90: error stop "cannot read header line" */
      fprintf(stderr, "%s\n", "cannot read header line");
      return 1;
   }
   /* f90: n_assets = count_fields(line) - 1 */
   n_assets = count_fields(line) - 1;
   /* f90: if (n_assets <= 0) then */
   if (n_assets <= 0) {
      /* f90: error stop "no asset columns found" */
      fprintf(stderr, "%s\n", "no asset columns found");
      return 1;
   }
   /* f90: nobs = 0 */
   nobs = 0;
   /* f90: do */
   while (1) {
      /* f90: read(iu, "(a)", iostat=ios) line */
      ios = read_a(iu, line, line_len);
      /* f90: if (ios /= 0) then */
      if (ios != 0) {
         /* f90: exit */
         goto xf2c_loop_1_break;
      }
      /* f90: if (len_trim(line) > 0) then */
      if (len_trim_s(line) > 0) {
         /* f90: nobs = nobs + 1 */
         nobs += 1;
      }
   }
   xf2c_loop_1_break: ;
   /* f90: close(iu) */
   close_unit(iu);
   /* f90: if (nobs < 2) then */
   if (nobs < 2) {
      /* f90: error stop "need at least two price rows" */
      fprintf(stderr, "%s\n", "need at least two price rows");
      return 1;
   }
   /* f90: allocate(names(n_assets)) */
   if (names) free_str_array(names, n_names);
   names = (char**) malloc(sizeof(char*) * n_assets);
   if (!names && n_assets > 0) return 1;
   for (int i_fill = 0; i_fill < n_assets; ++i_fill) names[i_fill] = NULL;
   n_names = n_assets;
   for (int i_fill = 0; i_fill < n_assets; ++i_fill) assign_str_alloc(&names[i_fill], "");
   /* f90: allocate(fields(n_assets + 1)) */
   if (fields) free_str_array(fields, n_fields);
   fields = (char**) malloc(sizeof(char*) * (n_assets + 1));
   if (!fields && (n_assets + 1) > 0) return 1;
   for (int i_fill = 0; i_fill < (n_assets + 1); ++i_fill) fields[i_fill] = NULL;
   n_fields = n_assets + 1;
   for (int i_fill = 0; i_fill < (n_assets + 1); ++i_fill) assign_str_alloc(&fields[i_fill], "");
   /* f90: allocate(prices(nobs, n_assets)) */
   if (prices) free(prices);
   prices = (double*) malloc(sizeof(double) * nobs * n_assets);
   if (!prices && (nobs * n_assets) > 0) return 1;
   n_prices_1 = nobs;
   n_prices_2 = n_assets;
   /* f90: allocate(mu(n_assets), sig(n_assets)) */
   if (mu) free(mu);
   mu = (double*) malloc(sizeof(double) * n_assets);
   if (!mu && n_assets > 0) return 1;
   n_mu = n_assets;
   if (sig) free(sig);
   sig = (double*) malloc(sizeof(double) * n_assets);
   if (!sig && n_assets > 0) return 1;
   n_sig = n_assets;
   /* f90: first_date = "" */
   assign_str(first_date, first_date_len, "");
   /* f90: last_date = "" */
   assign_str(last_date, last_date_len, "");
   /* f90: open(newunit=iu, file=filename, status="old", action="read", iostat=ios) */
   iu = alloc_unit();
   ios = open_unit(iu, trim_s(filename), "read", "old");
   /* f90: if (ios /= 0) then */
   if (ios != 0) {
      /* f90: error stop "cannot reopen input file " // trim(filename) */
      fprintf(stderr, "%s\n", concat_s2("cannot reopen input file ", trim_s(filename)));
      return 1;
   }
   /* f90: print "('prices file: ',a)", trim(filename) */
   printf("%s", "prices file: ");
   printf("%s", trim_s(filename));
   printf("\n");
   /* f90: read(iu, "(a)", iostat=ios) line */
   ios = read_a(iu, line, line_len);
   /* f90: if (ios /= 0) then */
   if (ios != 0) {
      /* f90: error stop "cannot reread header line" */
      fprintf(stderr, "%s\n", "cannot reread header line");
      return 1;
   }
   /* f90: call split_csv_line(trim(line), fields) */
   {
   char *arg_str_0 = copy_str_s(trim_s(line));
      split_csv_line(arg_str_0, n_fields, fields);
   if (arg_str_0) free(arg_str_0);
   }
   /* f90: names = fields(2:) */
   {
      int n_tmp = 0;
      if (1 > 0) {
         for (int i_fill = 2; i_fill <= n_fields; i_fill += 1) ++n_tmp;
      } else {
         for (int i_fill = 2; i_fill >= n_fields; i_fill += 1) ++n_tmp;
      }
      if (names) free_str_array(names, n_names);
      names = (char**) malloc(sizeof(char*) * n_tmp);
      if (!names && n_tmp > 0) return 1;
      for (int p_fill = 0; p_fill < n_tmp; ++p_fill) names[p_fill] = NULL;
      n_names = n_tmp;
      for (int p_fill = 0; p_fill < n_tmp; ++p_fill) {
         assign_str_alloc(&names[p_fill], fields[p_fill + 1]);
      }
   }
   /* f90: do i = 1, nobs */
   i = 1;
   while (i <= nobs) {
      /* f90: read(iu, "(a)", iostat=ios) line */
      ios = read_a(iu, line, line_len);
      /* f90: if (ios /= 0) then */
      if (ios != 0) {
         /* f90: error stop "unexpected end of file while reading prices" */
         fprintf(stderr, "%s\n", "unexpected end of file while reading prices");
         return 1;
      }
      /* f90: call split_csv_line(trim(line), fields) */
      {
      char *arg_str_0 = copy_str_s(trim_s(line));
         split_csv_line(arg_str_0, n_fields, fields);
      if (arg_str_0) free(arg_str_0);
      }
      /* f90: if (i == 1) then */
      if (i == 1) {
         /* f90: first_date = trim(fields(1)) */
         assign_str(first_date, first_date_len, trim_s(fields[0]));
      }
      /* f90: last_date = trim(fields(1)) */
      assign_str(last_date, last_date_len, trim_s(fields[0]));
      /* f90: do j = 1, n_assets */
      j = 1;
      while (j <= n_assets) {
         /* f90: read(fields(j + 1), *, iostat=ios) prices(i, j) */
         ios = read_first_double_s(fields[j], &(prices[i - 1 + n_prices_1 * (j - 1)]));
         /* f90: if (ios /= 0) then */
         if (ios != 0) {
            /* f90: write(*,"(a,i0,a,i0)") "error reading price at row ", i, ", column ", j */
            printf("%s", "error reading price at row ");
            printf("%d", i);
            printf("%s", ", column ");
            printf("%d", j);
            printf("\n");
            /* f90: error stop */
            return 1;
         }
         j += 1;
      }
      i += 1;
   }
   /* f90: close(iu) */
   close_unit(iu);
   /* f90: print "('date range: ',a,' to ',a)", trim(first_date), trim(last_date) */
   printf("%s", "date range: ");
   printf("%s", trim_s(first_date));
   printf("%s", " to ");
   printf("%s", trim_s(last_date));
   printf("\n");
   /* f90: print "('# days read: ',i0)", nobs */
   printf("%s", "# days read: ");
   printf("%d", nobs);
   printf("\n");
   /* f90: rets = ret_scale * (prices(2:nobs, :) / prices(1:nobs - 1, :) - 1.0_dp) */
   if (rets) free(rets);
   rets = (double*) malloc(sizeof(double) * (((((nobs - 2) / 1 + 1)) * (((n_prices_2 - 1) / 1 + 1)))));
   if (!rets && (((((nobs - 2) / 1 + 1)) * (((n_prices_2 - 1) / 1 + 1)))) > 0) return 1;
   n_rets_1 = ((nobs - 2) / 1 + 1);
   n_rets_2 = ((n_prices_2 - 1) / 1 + 1);
   for (int i2_fill = 0; i2_fill < ((n_prices_2 - 1) / 1 + 1); ++i2_fill) {
      for (int i1_fill = 0; i1_fill < ((nobs - 2) / 1 + 1); ++i1_fill) {
         rets[i1_fill + (((nobs - 2) / 1 + 1)) * i2_fill] = (100.0) * (prices[i1_fill + 1 + n_prices_1 * i2_fill] / prices[i1_fill + n_prices_1 * i2_fill] - 1.0);
      }
   }
   /* f90: do j = 1, n_assets */
   j = 1;
   while (j <= n_assets) {
      /* f90: mu(j) = mean(rets(:, j)) */
      mu[j - 1] = mean(n_rets_1, &rets[n_rets_1 * (j - 1)]);
      /* f90: sig(j) = sd(rets(:, j)) */
      sig[j - 1] = sd(n_rets_1, &rets[n_rets_1 * (j - 1)]);
      j += 1;
   }
   /* f90: write (*,"(*(a8))") "symbol", "mean", "sd" */
   printf("%8s", "symbol");
   printf("%8s", "mean");
   printf("%8s", "sd");
   printf("\n");
   /* f90: do j = 1, n_assets */
   j = 1;
   while (j <= n_assets) {
      /* f90: write(*, "(a8, *(f8.4))") trim(names(j)), mu(j), sig(j) */
      printf("%8s", trim_s(names[j - 1]));
      printf("%8.4f", mu[j - 1]);
      printf("%8.4f", sig[j - 1]);
      printf("\n");
      j += 1;
   }
   /* f90: call print_corr_matrix(rets, names) */
   print_corr_matrix(n_rets_1, n_rets_2, rets, n_names, names);
   free_str_array(names, n_names);
   free_str_array(fields, n_fields);
   free(prices);
   free(rets);
   free(mu);
   free(sig);
   return 0;
}
