/* Generated by xf2c.py from xrunif.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"

int main(void) {
   enum { n = 10000000 };
   double *x = NULL;
   double xmean, xsd;
   x = (double*) malloc(sizeof(double) * 10000000);
   if (!x) return 1;
   rng_seed(42);
   fill_runif_1d(10000000, x);
   {
      double red = 0.0;
      for (int i_fill = 0; i_fill < 10000000; ++i_fill) red += x[i_fill];
      xmean = red / 10000000;
   }
   {
      double red = 0.0;
      for (int i_fill = 0; i_fill < 10000000; ++i_fill) red += ((x[i_fill] - xmean) * (x[i_fill] - xmean));
      xsd = (sqrt(red / 9999999));
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", xmean);
      first = 0;
      printf("%s%13.6f", first ? "" : " ", xsd);
      first = 0;
      printf("%s%13.6f", first ? "" : " ", (xsd * xsd));
      first = 0;
      printf("\n");
   }
   free(x);
   return 0;
}
