/* Generated by xf2c.py from xsection.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"

int main(void) {
   enum { n1 = 10 };
   enum { n2 = 20 };
   double *x = NULL;
   int i;
   x = (double*) malloc(sizeof(double) * 200);
   if (!x) return 1;
   rng_seed(42);
   i = 0;
   while (i < 20) {
      fill_runif_1d(10, &x[10 * i]);
      i += 1;
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", minval_1d_double(200, x));
      first = 0;
      printf("\n");
   }
   printf("%g\n", ({ double red_sec = DBL_MAX; for (int is1 = 1; 2 > 0 ? is1 <= 10 : is1 >= 10; is1 += 2) { for (int is2 = 1; 3 > 0 ? is2 <= 20 : is2 >= 20; is2 += 3) { if (x[is1 - 1 + 10 * (is2 - 1)] < red_sec) red_sec = x[is1 - 1 + 10 * (is2 - 1)]; } } red_sec; }));
   printf("%g\n", ({ double red_sec = DBL_MAX; for (int is1 = 1; 1 > 0 ? is1 <= 2 : is1 >= 2; is1 += 1) { for (int is2 = 2; 1 > 0 ? is2 <= 4 : is2 >= 4; is2 += 1) { if (x[is1 - 1 + 10 * (is2 - 1)] < red_sec) red_sec = x[is1 - 1 + 10 * (is2 - 1)]; } } red_sec; }));
   printf("%g\n", ({ double red_sec = DBL_MAX; for (int is1 = 1; 2 > 0 ? is1 <= 2 : is1 >= 2; is1 += 2) { for (int is2 = 2; 2 > 0 ? is2 <= 4 : is2 >= 4; is2 += 2) { if (x[is1 - 1 + 10 * (is2 - 1)] < red_sec) red_sec = x[is1 - 1 + 10 * (is2 - 1)]; } } red_sec; }));
   free(x);
   return 0;
}
