/* Generated by xf2c.py from xselect_case.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"

int main(void) {
   enum { abbrev_len = 2, state_len = 20 };
   char abbrev[abbrev_len + 1] = "", state[state_len + 1] = "";
   assign_str(abbrev, abbrev_len, "MA");
   {
      if ((strcmp(trim_s(abbrev), trim_s("MA")) == 0)) {
         assign_str(state, state_len, "Massachusetts");
      }
      else if ((strcmp(trim_s(abbrev), trim_s("VA")) == 0)) {
         assign_str(state, state_len, "Virginia");
      }
      else if ((strcmp(trim_s(abbrev), trim_s("WA")) == 0)) {
         assign_str(state, state_len, "Washington");
      }
      else {
         assign_str(state, state_len, "???");
      }
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", concat_s2(concat_s2(abbrev, " "), state));
      first = 0;
      printf("\n");
   }
   return 0;
}
