/* Generated by xf2c.py from xsize.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   float *x = NULL;
   x = (float*) malloc(sizeof(float) * 12);
   if (!x) return 1;
   {
      int first = 1;
      printf("%s%d", first ? "" : " ", 12);
      first = 0;
      printf("%s%d", first ? "" : " ", 3);
      first = 0;
      printf("%s%d", first ? "" : " ", 4);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%d", first ? "" : " ", ((((2 / 2 + 1))) * (((3 / 3 + 1)))));
      first = 0;
      printf("%s%d", first ? "" : " ", ((2 / 2 + 1)));
      first = 0;
      printf("%s%d", first ? "" : " ", ((3 / 3 + 1)));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%d", first ? "" : " ", ((((1 / 1 + 1))) * (((2 / 1 + 1)))));
      first = 0;
      printf("%s%d", first ? "" : " ", ((1 / 1 + 1)));
      first = 0;
      printf("%s%d", first ? "" : " ", ((2 / 1 + 1)));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%d", first ? "" : " ", ((((1 / 2 + 1))) * (((2 / 2 + 1)))));
      first = 0;
      printf("%s%d", first ? "" : " ", ((1 / 2 + 1)));
      first = 0;
      printf("%s%d", first ? "" : " ", ((2 / 2 + 1)));
      first = 0;
      printf("\n");
   }
   free(x);
   return 0;
}
