/* Generated by xf2c.py from xspread_tmp.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   int *v = NULL, *m23 = NULL, *m32 = NULL;
   int i;
   v = (int*) malloc(sizeof(int) * 3);
   if (!v) return 1;
   m23 = (int*) malloc(sizeof(int) * 6);
   if (!m23) return 1;
   m32 = (int*) malloc(sizeof(int) * 6);
   if (!m32) return 1;
   v[0] = 1;
   v[1] = 2;
   v[2] = 3;
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "example 1: spread a rank-1 array into rows");
      first = 0;
      printf("\n");
   }
   {
      int first_pr = 1;
      printf("%s%s", first_pr ? "" : " ", "v = ");
      first_pr = 0;
      for (int i_pr = 0; i_pr < 3; ++i_pr) {
         printf("%s%d", first_pr ? "" : " ", v[i_pr]);
         first_pr = 0;
      }
      printf("\n");
   }
   for (int j_fill = 0; j_fill < 3; ++j_fill) {
      for (int i_fill = 0; i_fill < 2; ++i_fill) {
         m23[i_fill + 2 * j_fill] = v[j_fill];
      }
   }
   i = 0;
   while (i < 2) {
      {
         int first = 1;
         for (int i2 = 1; i2 <= 3; i2 += 1) {
            printf("%s%d", first ? "" : " ", m23[i + 2 * (i2 - 1)]);
            first = 0;
         }
         printf("\n");
      }
      i += 1;
   }
   printf("\n");
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "example 2: spread a rank-1 array into columns");
      first = 0;
      printf("\n");
   }
   for (int j_fill = 0; j_fill < 2; ++j_fill) {
      for (int i_fill = 0; i_fill < 3; ++i_fill) {
         m32[i_fill + 3 * j_fill] = v[i_fill];
      }
   }
   i = 0;
   while (i < 3) {
      {
         int first = 1;
         for (int i2 = 1; i2 <= 2; i2 += 1) {
            printf("%s%d", first ? "" : " ", m32[i + 3 * (i2 - 1)]);
            first = 0;
         }
         printf("\n");
      }
      i += 1;
   }
   free(v);
   free(m23);
   free(m32);
   return 0;
}
