/* Generated by xf2c.py from xstats_sd_tmp.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

double sd(const int n, const double *x);

double sd(const int n, const double *x) {
   /* n: extent of x (dimension 1) */
   double sig, mu;
   if (n <= 1) {
      sig = 0.0;
   }
   else {
      {
         double red = 0.0;
         for (int i_fill = 0; i_fill < n; ++i_fill) red += x[i_fill];
         mu = red / ((float) n);
      }
      {
         double red = 0.0;
         for (int i_fill = 0; i_fill < n; ++i_fill) red += ((x[i_fill] - mu) * (x[i_fill] - mu));
         sig = (sqrtf(red / ((float) (n - 1))));
      }
   }
   return sig;
}

int main(void) {
   double *x = NULL;
   double s;
   x = (double*) malloc(sizeof(double) * 4);
   if (!x) return 1;
   x[0] = 1.0;
   x[1] = 2.0;
   x[2] = 3.0;
   x[3] = 5.0;
   s = sd(4, x);
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", s);
      first = 0;
      printf("\n");
   }
   free(x);
   return 0;
}
