/* Generated by xf2c.py from xsum_dim.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"

static float sum_2d_float(const int n1, const int n2, const float *x) {
   float s = 0.0f;
   for (int i = 0; i < n1 * n2; ++i) s += x[i];
   return s;
}

int main(void) {
   float x[3] = {10.0, 20.0, 30.0};
   float *y = NULL;
   y = (float*) malloc(sizeof(float) * 6);
   if (!y) return 1;
   /* overall sum */
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", sum_1d_float(3, x));
      first = 0;
      printf("\n");
   }
   printf("%g\n", sum_1d_float(3, x));
   for (int p_fill = 0; p_fill < 3; ++p_fill) {
      y[2 * p_fill] = x[p_fill];
   }
   for (int p_fill = 0; p_fill < 3; ++p_fill) {
      y[1 + 2 * p_fill] = 10 * x[p_fill];
   }
   {
      int first = 1;
      for (int i_pr = 0; i_pr < 6; ++i_pr) {
         if (first) printf("%13.6f", y[i_pr]);
         else printf("    %13.6f", y[i_pr]);
         first = 0;
      }
      printf("    \n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", sum_2d_float(2, 3, y));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      float xsum;
      for (int j = 0; j < 3; ++j) {
         xsum = 0;
         for (int i = 0; i < 2; ++i) xsum += y[i + 2 * j];
         printf("%s%g", first ? "" : " ", xsum);
         first = 0;
      }
      printf("\n");
   }
   {
      int first = 1;
      float xsum;
      for (int i = 0; i < 2; ++i) {
         xsum = 0;
         for (int j = 0; j < 3; ++j) xsum += y[i + 2 * j];
         printf("%s%g", first ? "" : " ", xsum);
         first = 0;
      }
      printf("\n");
   }
   free(y);
   return 0;
}
