/* Generated by xf2c.py from xsum_generic_vec.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

float *g_vec(const int n, const int *stdz);

float *g_vec(const int n, const int *stdz) {
   float *x = (float*) malloc(sizeof(float) * n);
   if (!x) return NULL;
   int i = 1;
   while (i <= n) {
      x[i - 1] = ((float) i);
      i += 1;
   }
   if ((stdz != NULL)) {
      if ((*stdz)) {
         for (int p_fill = 0; p_fill < n; ++p_fill) {
            x[p_fill] = x[p_fill] / 2.0;
         }
      }
   }
   return x;
}

int main(void) {
   float s1, s2;
   {
   float *arr_sum_tmp = g_vec(4, NULL);
   int arr_sum_n = 4;
      float red = 0.0f;
      for (int i_fill = 0; i_fill < arr_sum_n; ++i_fill) red += (arr_sum_tmp[i_fill] * arr_sum_tmp[i_fill]);
      s1 = red;
   free(arr_sum_tmp);
   }
   {
   float *arr_sum_tmp = g_vec(4, &((int){1}));
   int arr_sum_n = 4;
      float red = 0.0f;
      for (int i_fill = 0; i_fill < arr_sum_n; ++i_fill) red += (arr_sum_tmp[i_fill] * arr_sum_tmp[i_fill]);
      s2 = red;
   free(arr_sum_tmp);
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", s1);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", s2);
      first = 0;
      printf("\n");
   }
   return 0;
}
