/* Generated by xf2c.py from xsum_dim_expr_print.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   double *rets = NULL;
   int n_rets_1 = 0, n_rets_2 = 0, nobs;
   if (rets) free(rets);
   rets = (double*) malloc(sizeof(double) * 6);
   if (!rets && 6 > 0) return 1;
   n_rets_1 = 2;
   n_rets_2 = 3;
   nobs = 3;
   rets[0] = -(0.1);
   rets[1] = 0.3;
   rets[n_rets_1] = 0.02;
   rets[n_rets_1 + 1] = 0.04;
   rets[n_rets_1 * 2] = 0.01;
   rets[1 + n_rets_1 * 2] = -(0.03);
   {
      int first = 1;
      double red;
      printf("%s%s", first ? "" : " ", "mu:");
      first = 0;
      for (int j = 0; j < n_rets_2; ++j) {
         red = 0;
         for (int i = 0; i < n_rets_1; ++i) red += rets[i + n_rets_1 * j];
         printf("%s%g", first ? "" : " ", red / (nobs - 1));
         first = 0;
      }
      printf("\n");
   }
   free(rets);
   return 0;
}
