/* Generated by xf2c.py from xsum_dim_assign.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   double *rets = NULL, *mu = NULL;
   int n_rets_1 = 0, n_rets_2 = 0, n_mu = 0;
   if (rets) free(rets);
   rets = (double*) malloc(sizeof(double) * 6);
   if (!rets && 6 > 0) return 1;
   n_rets_1 = 2;
   n_rets_2 = 3;
   if (mu) free(mu);
   mu = (double*) malloc(sizeof(double) * 3);
   if (!mu && 3 > 0) return 1;
   n_mu = 3;
   rets[0] = -(0.1);
   rets[1] = 0.3;
   rets[n_rets_1] = 0.02;
   rets[n_rets_1 + 1] = 0.04;
   rets[n_rets_1 * 2] = 0.01;
   rets[1 + n_rets_1 * 2] = -(0.03);
   if (mu) free(mu);
   mu = (double*) malloc(sizeof(double) * n_rets_2);
   if (!mu && n_rets_2 > 0) return 1;
   n_mu = n_rets_2;
   {
      double red;
      for (int j_fill = 0; j_fill < n_rets_2; ++j_fill) {
         red = 0;
         for (int i_fill = 0; i_fill < n_rets_1; ++i_fill) red += rets[i_fill + n_rets_1 * j_fill];
         mu[j_fill] = red / ((float) n_rets_1);
      }
   }
   {
      int first = 1;
      for (int i_pr = 0; i_pr < n_mu; ++i_pr) {
         if (first) printf("%13.6f", mu[i_pr]);
         else printf("    %13.6f", mu[i_pr]);
         first = 0;
      }
      printf("    \n");
   }
   free(rets);
   free(mu);
   return 0;
}
