/* Generated by xf2c.py from xtext.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"

int main(void) {
   char s[4] = "def";
   char t[2][4] = {"ghi", "jkl"};
   int i = 1;
   while (i <= 3) {
      {
         int first = 1;
         printf("%s%s", first ? "" : " ", substr_s(s, i, i));
         first = 0;
         printf("%s%s", first ? "" : "", substr_s(t[0], i, i));
         first = 0;
         printf("%s%s", first ? "" : "", substr_s(t[1], i, i));
         first = 0;
         printf("\n");
      }
      i += 1;
   }
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", substr_s(s, 2, 3));
      first = 0;
      printf("\n");
   }
   return 0;
}
