/* Generated by xf2c.py from xtype_bound.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

typedef struct {
   float x, y;
} point2d;

point2d make_point(const float x, const float y);
void shift(point2d *self, const float dx, const float dy);
void scale(point2d *self, const float a);
float sum_xy(const point2d self);

point2d make_point(const float x, const float y) {
   point2d p;
   p.x = x;
   p.y = y;
   return p;
}

void shift(point2d *self, const float dx, const float dy) {
   self->x = self->x + dx;
   self->y = self->y + dy;
}

void scale(point2d *self, const float a) {
   self->x = a*self->x;
   self->y = a*self->y;
}

float sum_xy(const point2d self) {
   float total = self.x + self.y;
   return total;
}

int main(void) {
   point2d p = {0};
   p = make_point(1.0, 2.0);
   shift(&p, 3.0, -1.0);
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", p.x);
      first = 0;
      printf("%s%13.6f", first ? "" : " ", p.y);
      first = 0;
      printf("\n");
   }
   scale(&p, 10.0);
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", p.x);
      first = 0;
      printf("%s%13.6f", first ? "" : " ", p.y);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", sum_xy(p));
      first = 0;
      printf("\n");
   }
   return 0;
}
