/* Generated by xf2c.py from xuncmin.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

const double zero = 0.0, one = 1.0;

double dnrm2(const int n, const int n_x, const double *x, const int incx); /* Euclidean norm of the n-vector stored in x() with storage increment incx . */
void dswap(const int n, const int n_x, double *x, const int incx, const int n_y, double *y, const int incy); /* interchanges two vectors. */
int idamax(const int n, const int n_x, const double *x, const int incx); /* finds the index of element having max. absolute value. */
void dgemv(const char * trans, const int m, const int n, const double alpha, const int n_a_1, const int n_a_2, const double *a, const int lda, const int n_x, const double *x, const int incx, const double beta, const int n_y, double *y, const int incy); /* ELF90 translation by Alan Miller   31-Aug-1997 */
void bakslv(const int n, const int n_a_1, const int n_a_2, const double *a, const int n_x, double *x, const int n_b, const double *b); /* PURPOSE */
void choldc(const int n, const int n_a_1, const int n_a_2, double *a, const double diagmx, const double tol, double *addmax); /* PURPOSE */
void chlhsn(const int n, const int n_a_1, const int n_a_2, double *a, const double epsm, const int n_sx, const double *sx, const int n_udiag, double *udiag); /* PURPOSE */
void dfaut(const int n, const int n_typsiz, double *typsiz, double *fscale, int *method, int *iexp, int *msg, int *ndigit, int *itnlim, int *iagflg, int *iahflg, int *ipr, double *dlt, double *gradtl, double *stepmx, double *steptl);
void dogdrv(const int n, const int n_x, const double *x, const double f, const int n_g, const double *g, const int n_a_1, const int n_a_2, const double *a, const int n_p, const double *p, const int n_xpls, double *xpls, double *fpls, void (*fcn)(const int n, const int n_x, const double *x, double *f), const int n_sx, const double *sx, const double stepmx, const double steptl, double *dlt, int *iretcd, int *mxtake);
void dogstp(const int n, const int n_g, const double *g, const int n_a_1, const int n_a_2, const double *a, const int n_p, const double *p, const int n_sx, const double *sx, const double rnwtln, double *dlt, int *nwtake, int *fstdog, const int n_ssd, double *ssd, const int n_v, double *v, double *cln, double *eta, const int n_sc, double *sc, const double stepmx);
void forslv(const int n, const int n_a_1, const int n_a_2, const double *a, const int n_x, double *x, const int n_b, const double *b); /* PURPOSE */
void fstocd(const int n, const int n_x, double *x, void (*fcn)(const int n, const int n_x, const double *x, double *f), const int n_sx, const double *sx, const double rnoise, const int n_g, double *g); /* PURPOSE */
void fstofd(const int m, const int n, const int n_xpls, double *xpls, void (*fcn)(const int n, const int n_x, const double *x, double *f), const int n_fpls, const double *fpls, const int n_a_1, const int n_a_2, double *a, const int n_sx, const double *sx, const double rnoise, const int icase); /* PURPOSE */
void estimate_hessian(const int m, const int n, const int n_xpls, double *xpls, void (*d1fcn)(const int n, const int n_x, const double *x, const int n_g, double *g), const int n_fpls, const double *fpls, const int n_a_1, const int n_a_2, double *a, const int n_sx, const double *sx, const double rnoise, const int icase); /* PURPOSE */
void hookdr(const int n, const int n_g, const double *g, const int n_a_1, const int n_a_2, double *a, const int n_udiag, const double *udiag, const int n_p, const double *p, const int n_sx, const double *sx, const double stepmx, double *dlt, int *iretcd, double *amu, double *dltp, double *phi, double *phip0, const double epsm, const int itncnt);
void hookst(const int n, const int n_g, const double *g, const int n_a_1, const int n_a_2, double *a, const int n_udiag, const double *udiag, const int n_p, const double *p, const int n_sx, const double *sx, const double rnwtln, double *dlt, double *amu, const double dltp, double *phi, double *phip0, int *fstime, const double epsm);
void hsnint(const int n, const int n_a_1, const int n_a_2, double *a, const int n_sx, const double *sx, const int method); /* PURPOSE */
void lltslv(const int n, const int n_a_1, const int n_a_2, const double *a, const int n_x, double *x, const int n_b, const double *b); /* PURPOSE */
void optchk(const int n, const int n_x, const double *x, const int n_typsiz, double *typsiz, const int n_sx, double *sx, double *fscale, int *itnlim, int *ndigit, const double epsm, double *dlt, int *method, int *iexp, int *iagflg, int *iahflg, double *stepmx, int *msg);
void optdrv(const int nr, const int n, const int n_x, double *x, void (*fcn)(const int n, const int n_x, const double *x, double *f), void (*d1fcn)(const int n, const int n_x, const double *x, const int n_g, double *g), void (*d2fcn)(const int nr, const int n, const int n_x, const double *x, const int n_h_1, const int n_h_2, double *h), const int n_typsiz, double *typsiz, double *fscale, int *method, int *iexp, int *msg, int *ndigit, int *itnlim, int *iagflg, int *iahflg, double *dlt, const double gradtl, double *stepmx, const double steptl, const int n_xpls, double *xpls, double *fpls, const int n_gpls, double *gpls, int *itrmcd);
void optif9(const int nr, const int n, const int n_x, double *x, void (*fcn)(const int n, const int n_x, const double *x, double *f), void (*d1fcn)(const int n, const int n_x, const double *x, const int n_g, double *g), void (*d2fcn)(const int nr, const int n, const int n_x, const double *x, const int n_h_1, const int n_h_2, double *h), const int n_typsiz, double *typsiz, double *fscale, int *method, int *iexp, int *msg, int *ndigit, int *itnlim, int *iagflg, int *iahflg, double *dlt, const double gradtl, double *stepmx, const double steptl, const int n_xpls, double *xpls, double *fpls, const int n_gpls, double *gpls, int *itrmcd);
void optstp(const int n, const int n_xpls, const double *xpls, const double fpls, const int n_gpls, const double *gpls, const int n_x, const double *x, const int itncnt, int *icscmx, int *itrmcd, const double gradtl, const double steptl, const int n_sx, const double *sx, const double fscale, const int itnlim, const int iretcd, const int mxtake);
void sndofd(const int n, const int n_xpls, double *xpls, void (*fcn)(const int n, const int n_x, const double *x, double *f), const double fpls, const int n_a_1, const int n_a_2, double *a, const int n_sx, const double *sx, const double rnoise); /* PURPOSE */
void tregup(const int n, const int n_x, const double *x, const double f, const int n_g, const double *g, const int n_a_1, const int n_a_2, const double *a, void (*fcn)(const int n, const int n_x, const double *x, double *f), const int n_sc, const double *sc, const int n_sx, const double *sx, const int nwtake, const double stepmx, const double steptl, double *dlt, int *iretcd, const int n_xplsp, double *xplsp, double *fplsp, const int n_xpls, double *xpls, double *fpls, int *mxtake, const int method, const int n_udiag, const double *udiag);
void fcn(const int n, const int n_x, const double *x, double *f);
void d1fcn(const int n, const int n_x, const double *x, const int n_g, double *g);
void d2fcn(const int nr, const int n, const int n_x, const double *x, const int n_h_1, const int n_h_2, double *h);

double dnrm2(const int n, const int n_x, const double *x, const int incx) {
   /* Euclidean norm of the n-vector stored in x() with storage increment incx . */
   /* n_x: extent of x (dimension 1) */
   double fn_val, cuthi, cutlo, hitest, sum, xmax;
   int i, ix, next;
   if (n <= 0 || incx <= 0) {
      fn_val = 0.0;
      return fn_val;
   }
   cutlo = (sqrt(DBL_MIN / DBL_EPSILON));
   cuthi = sqrt(DBL_MAX);
   next = 1;
   sum = 0.0;
   i = 1;
   ix = 1;
   xf2c_stmt_20: ;
   switch (next) {
      case 1:
      {
         if ((fabs(x[i - 1])) > cutlo) {
            goto xf2c_stmt_85;
         }
         next = 2;
         xmax = 0.0;
         goto xf2c_stmt_20;
         break;
      }
      case 2:
      {
         if (x[i - 1] == (0.0)) {
            goto xf2c_stmt_200;
         }
         if ((fabs(x[i - 1])) > cutlo) {
            goto xf2c_stmt_85;
         }
         next = 3;
         goto xf2c_stmt_105;
         break;
      }
      case 3:
      {
         if ((fabs(x[i - 1])) > cutlo) {
            sum = sum * xmax * xmax;
            goto xf2c_stmt_85;
         }
         break;
      }
      case 4:
      {
         goto xf2c_stmt_110;
         break;
      }
   }
   xf2c_stmt_110: ;
   if ((fabs(x[i - 1])) <= xmax) goto xf2c_stmt_115;
   sum = (1.0) + sum * ((xmax / x[i - 1]) * (xmax / x[i - 1]));
   xmax = fabs(x[i - 1]);
   goto xf2c_stmt_200;
   xf2c_stmt_85: ;
   hitest = cuthi / ((double) n);
   while (ix <= n) {
      if ((fabs(x[i - 1])) >= hitest) {
         goto xf2c_stmt_100;
      }
      sum += (x[i - 1] * x[i - 1]);
      i += incx;
      xf2c_loop_1_continue: ;
      ix += 1;
   }
   xf2c_loop_1_break: ;
   fn_val = sqrt(sum);
   return fn_val;
   xf2c_stmt_100: ;
   ix = ix;
   next = 4;
   sum = (sum / x[i - 1]) / x[i - 1];
   xf2c_stmt_105: ;
   xmax = fabs(x[i - 1]);
   xf2c_stmt_115: ;
   sum += ((x[i - 1]/xmax) * (x[i - 1]/xmax));
   xf2c_stmt_200: ;
   ix += 1;
   i += incx;
   if (ix <= n) {
      goto xf2c_stmt_20;
   }
   fn_val = xmax * sqrt(sum);
   return fn_val;
   return fn_val;
}

void dswap(const int n, const int n_x, double *x, const int incx, const int n_y, double *y, const int incy) {
   /* interchanges two vectors. */
   /* n_x: extent of x (dimension 1) */
   /* n_y: extent of y (dimension 1) */
   double temp[n];
   if (n <= 0) {
      return;
   }
   if (incx == 1 && incy == 1) {
      for (int p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); ++p_fill) {
         temp[p_fill] = x[p_fill];
      }
      if (1 > 0) {
         for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
            x[i_fill - 1] = y[p_fill];
         }
      } else {
         for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
            x[i_fill - 1] = y[p_fill];
         }
      }
      if (1 > 0) {
         for (int i_fill = 1, p_fill = 0; p_fill < n; i_fill += 1, ++p_fill) {
            y[i_fill - 1] = temp[p_fill];
         }
      } else {
         for (int i_fill = 1, p_fill = 0; p_fill < n; i_fill += 1, ++p_fill) {
            y[i_fill - 1] = temp[p_fill];
         }
      }
      return;
   }
   for (int p_fill = 0; p_fill < ((((incx > 0) ? ((n * incx - 1) / incx + 1) : ((1 - n * incx) / (-incx) + 1)))); ++p_fill) {
      temp[p_fill] = x[1 + p_fill * incx - 1];
   }
   if (incx > 0) {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((incy > 0) ? ((n * incy - 1) / incy + 1) : ((1 - n * incy) / (-incy) + 1)))); i_fill += incx, ++p_fill) {
         x[i_fill - 1] = y[1 + p_fill * incy - 1];
      }
   } else {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((incy > 0) ? ((n * incy - 1) / incy + 1) : ((1 - n * incy) / (-incy) + 1)))); i_fill += incx, ++p_fill) {
         x[i_fill - 1] = y[1 + p_fill * incy - 1];
      }
   }
   if (incy > 0) {
      for (int i_fill = 1, p_fill = 0; p_fill < n; i_fill += incy, ++p_fill) {
         y[i_fill - 1] = temp[p_fill];
      }
   } else {
      for (int i_fill = 1, p_fill = 0; p_fill < n; i_fill += incy, ++p_fill) {
         y[i_fill - 1] = temp[p_fill];
      }
   }
   return;
}

int idamax(const int n, const int n_x, const double *x, const int incx) {
   /* finds the index of element having max. absolute value. */
   /* n_x: extent of x (dimension 1) */
   int fn_val, imax[1];
   fn_val = 0;
   if (n < 1 || incx <= 0) {
      return fn_val;
   }
   fn_val = 1;
   if (n == 1) {
      return fn_val;
   }
   if (incx == 1) {
      {
         int loc = 0, i_pr = 0;
         double best = fabs(x[i_pr]);
         for (i_pr = 1; i_pr < (((n - 1) / 1 + 1)); ++i_pr) {
            if ((fabs(x[i_pr])) > best || (0 && ((fabs(x[i_pr])) == best))) { best = (fabs(x[i_pr])); loc = i_pr; }
         }
      imax[0] = loc + 1;
      }
   }
   else {
      {
         int loc = 0, i_pr = 0;
         double best = fabs(x[1 + i_pr * incx - 1]);
         for (i_pr = 1; i_pr < (((incx > 0) ? ((n * incx - 1) / incx + 1) : ((1 - n * incx) / (-incx) + 1))); ++i_pr) {
            if ((fabs(x[1 + i_pr * incx - 1])) > best || (0 && ((fabs(x[1 + i_pr * incx - 1])) == best))) { best = (fabs(x[1 + i_pr * incx - 1])); loc = i_pr; }
         }
      imax[0] = loc + 1;
      }
   }
   fn_val = imax[0];
   return fn_val;
   return fn_val;
}

void dgemv(const char * trans, const int m, const int n, const double alpha, const int n_a_1, const int n_a_2, const double *a, const int lda, const int n_x, const double *x, const int incx, const double beta, const int n_y, double *y, const int incy) {
   /* ELF90 translation by Alan Miller   31-Aug-1997 */
   /* n_a_1: extent of a (dimension 1) */
   /* n_a_2: extent of a (dimension 2) */
   /* n_x: extent of x (dimension 1) */
   /* n_y: extent of y (dimension 1) */
   double temp;
   int i, info, ix, iy, j, jx, jy, kx, ky, lenx, leny;
   info = 0;
   if (strcmp(trans, "N") != 0 && strcmp(trans, "n") != 0 && strcmp(trans, "T") != 0 && strcmp(trans, "t") != 0      && strcmp(trans, "C") != 0 && strcmp(trans, "c") != 0) {
      info = 1;
   }
   else if (m < 0) {
      info = 2;
   }
   else if (n < 0) {
      info = 3;
   }
   else if (lda < fmax( 1, m )) {
      info = 6;
   }
   else if (incx == 0) {
      info = 8;
   }
   else if (incy == 0) {
      info = 11;
   }
   if (info != 0) {
      printf("%s", " Error number: ");
      printf("%4d", info);
      printf("%s", " in BLAS2 routine DGEMV");
      printf("\n");
      return;
   }
   if (( m == 0 ) || ( n == 0 )||     ( ( alpha == (0.0) ) && ( beta == (1.0) ) )) return;
   if (strcmp(trans, "N") == 0 || strcmp(trans, "n") == 0) {
      lenx = n;
      leny = m;
   }
   else {
      lenx = m;
      leny = n;
   }
   if (incx > 0) {
      kx = 1;
   }
   else {
      kx = 1 - (lenx - 1) * incx;
   }
   if (incy > 0) {
      ky = 1;
   }
   else {
      ky = 1 - (leny - 1) * incy;
   }
   if (beta != (1.0)) {
      if (incy == 1) {
         if (beta == (0.0)) {
            if (1 > 0) {
               for (int i_fill = 1, p_fill = 0; i_fill <= leny; i_fill += 1, ++p_fill) {
                  y[i_fill - 1] = 0.0;
               }
            } else {
               for (int i_fill = 1, p_fill = 0; i_fill >= leny; i_fill += 1, ++p_fill) {
                  y[i_fill - 1] = 0.0;
               }
            }
         }
         else {
            if (1 > 0) {
               for (int i_fill = 1, p_fill = 0; p_fill < ((((leny - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
                  y[i_fill - 1] = beta * y[p_fill];
               }
            } else {
               for (int i_fill = 1, p_fill = 0; p_fill < ((((leny - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
                  y[i_fill - 1] = beta * y[p_fill];
               }
            }
         }
      }
      else {
         iy = ky;
         if (beta == (0.0)) {
            i = 0;
            while (i < leny) {
               y[iy - 1] = 0.0;
               iy += incy;
               xf2c_loop_1_continue: ;
               i += 1;
            }
            xf2c_loop_1_break: ;
         }
         else {
            i = 0;
            while (i < leny) {
               y[iy - 1] = beta * y[iy - 1];
               iy += incy;
               i += 1;
            }
         }
      }
   }
   if (alpha == (0.0)) {
      return;
   }
   if (strcmp(trans, "N") == 0 || strcmp(trans, "n") == 0) {
      jx = kx;
      if (incy == 1) {
         j = 0;
         while (j < n) {
            if (x[jx - 1] != (0.0)) {
               temp = alpha * x[jx - 1];
               if (1 > 0) {
                  for (int i_fill = 1, p_fill = 0; p_fill < ((((m - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
                     y[i_fill - 1] = y[p_fill] + temp * a[p_fill + n_a_1 * j];
                  }
               } else {
                  for (int i_fill = 1, p_fill = 0; p_fill < ((((m - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
                     y[i_fill - 1] = y[p_fill] + temp * a[p_fill + n_a_1 * j];
                  }
               }
            }
            jx += incx;
            xf2c_loop_3_continue: ;
            j += 1;
         }
      }
      else {
         j = 0;
         while (j < n) {
            if (x[jx - 1] != (0.0)) {
               temp = alpha * x[jx - 1];
               iy = ky;
               i = 0;
               while (i < m) {
                  y[iy - 1] += temp*a[i + n_a_1 * j];
                  iy += incy;
                  i += 1;
               }
            }
            jx += incx;
            j += 1;
         }
      }
   }
   else {
      jy = ky;
      if (incx == 1) {
         j = 0;
         while (j < n) {
            temp = ({ double red = 0.0; for (int i_red = 0; i_red < ((((m - 1) / 1 + 1))); ++i_red) red += (a[i_red + n_a_1 * j]) * (x[i_red]); red; });
            y[jy - 1] += alpha*temp;
            jy += incy;
            xf2c_loop_6_continue: ;
            j += 1;
         }
      }
      else {
         j = 0;
         while (j < n) {
            temp = 0.0;
            ix = kx;
            i = 0;
            while (i < m) {
               temp += a[i + n_a_1 * j]*x[ix - 1];
               ix += incx;
               i += 1;
            }
            y[jy - 1] += alpha*temp;
            jy += incy;
            j += 1;
         }
      }
   }
   return;
}

void bakslv(const int n, const int n_a_1, const int n_a_2, const double *a, const int n_x, double *x, const int n_b, const double *b) {
   /* PURPOSE */
   /* n_a_1: extent of a (dimension 1) */
   /* n_a_2: extent of a (dimension 2) */
   /* n_x: extent of x (dimension 1) */
   /* n_b: extent of b (dimension 1) */
   int i;
   double sum;
   i = n;
   x[i - 1] = b[i - 1] / a[i - 1 + n_a_1 * (i - 1)];
   if (n == 1) {
      return;
   }
   while (1) {
      i -= 1;
      sum = ({ double red = 0.0; for (int i_red = 0; i_red < ((((n - i) / 1 + 1))); ++i_red) red += (a[i + i_red - 1 + n_a_1 * (i - 1)]) * (x[i + i_red - 1]); red; });
      x[i - 1] = (b[i - 1] - sum)/a[i - 1 + n_a_1 * (i - 1)];
      if (i <= 1) {
         goto xf2c_loop_1_break;
      }
      xf2c_loop_1_continue: ;
   }
   xf2c_loop_1_break: ;
   return;
}

void choldc(const int n, const int n_a_1, const int n_a_2, double *a, const double diagmx, const double tol, double *addmax) {
   /* PURPOSE */
   /* n_a_1: extent of a (dimension 1) */
   /* n_a_2: extent of a (dimension 2) */
   int j, i;
   double aminl, total, temp, amnlsq, offmax;
   if ((addmax != NULL)) {
      (*addmax) = 0.0;
   }
   aminl = sqrt(diagmx * tol);
   amnlsq = aminl * aminl;
   j = 1;
   while (j <= n) {
      {
         double red = 0.0;
         for (int i_fill = 0; i_fill < (((j - 2) / 1 + 1)); ++i_fill) red += (a[j - 1 + n_a_1 * i_fill] * a[j - 1 + n_a_1 * i_fill]);
         temp = a[j - 1 + n_a_1 * (j - 1)] - red;
      }
      if (temp > amnlsq) {
         a[j - 1 + n_a_1 * (j - 1)] = sqrt(temp);
      }
      else {
         offmax = 0.0;
         i = j + 1;
         while (i <= n) {
            if ((fabs(a[i - 1 + n_a_1 * (j - 1)])) > offmax) {
               offmax = fabs(a[i - 1 + n_a_1 * (j - 1)]);
            }
            i += 1;
         }
         if (offmax <= amnlsq) {
            offmax = amnlsq;
         }
         a[j - 1 + n_a_1 * (j - 1)] = sqrt(offmax);
         if ((addmax != NULL)) {
            (*addmax) = fmax((*addmax),offmax-temp);
         }
      }
      i = j + 1;
      while (i <= n) {
         total = ({ double red = 0.0; for (int i_red = 0; i_red < ((((j - 2) / 1 + 1))); ++i_red) red += (a[i - 1 + n_a_1 * i_red]) * (a[j - 1 + n_a_1 * i_red]); red; });
         a[i - 1 + n_a_1 * (j - 1)] = (a[i - 1 + n_a_1 * (j - 1)] - total) / a[j - 1 + n_a_1 * (j - 1)];
         xf2c_loop_3_continue: ;
         i += 1;
      }
      xf2c_loop_1_continue: ;
      j += 1;
   }
   xf2c_loop_1_break: ;
   return;
}

void chlhsn(const int n, const int n_a_1, const int n_a_2, double *a, const double epsm, const int n_sx, const double *sx, const int n_udiag, double *udiag) {
   /* PURPOSE */
   /* n_a_1: extent of a (dimension 1) */
   /* n_a_2: extent of a (dimension 2) */
   /* n_sx: extent of sx (dimension 1) */
   /* n_udiag: extent of udiag (dimension 1) */
   int i, j;
   double tol, diagmx, diagmn, posmax, amu, offmax, addmax, evmin, evmax, offrow, sdd;
   j = 1;
   while (j <= n) {
      for (int p_fill = 0; p_fill < (((n - j) / 1 + 1)); ++p_fill) {
         a[j + p_fill - 1 + n_a_1 * (j - 1)] = a[j + p_fill - 1 + n_a_1 * (j - 1)] / (sx[j + p_fill - 1] * sx[j - 1]);
      }
      xf2c_loop_1_continue: ;
      j += 1;
   }
   xf2c_loop_1_break: ;
   tol = sqrt(epsm);
   diagmx = a[0];
   diagmn = a[0];
   i = 2;
   while (i <= n) {
      if (a[i - 1 + n_a_1 * (i - 1)] < diagmn) {
         diagmn = a[i - 1 + n_a_1 * (i - 1)];
      }
      if (a[i - 1 + n_a_1 * (i - 1)] > diagmx) {
         diagmx = a[i - 1 + n_a_1 * (i - 1)];
      }
      i += 1;
   }
   posmax = fmax(diagmx, 0.0);
   if (diagmn <= posmax*tol) {
      amu = tol * (posmax - diagmn) - diagmn;
      if (amu == (0.0)) {
         offmax = 0.0;
         i = 2;
         while (i <= n) {
            j = 0;
            while (j < i - 1) {
               if ((fabs(a[i - 1 + n_a_1 * j])) > offmax) {
                  offmax = fabs(a[i - 1 + n_a_1 * j]);
               }
               j += 1;
            }
            xf2c_loop_3_continue: ;
            i += 1;
         }
         amu = offmax;
         if (amu == (0.0)) {
            amu = 1.0;
         }
         else {
            amu = amu * (1.0 + tol);
         }
      }
      i = 0;
      while (i < n) {
         a[i + n_a_1 * i] += amu;
         i += 1;
      }
      diagmx += amu;
   }
   j = 1;
   while (j <= n) {
      udiag[j - 1] = a[j - 1 + n_a_1 * (j - 1)];
      if (j == n) {
         goto xf2c_loop_6_continue;
      }
      for (int p_fill = 0; p_fill < (((n - j - 1) / 1 + 1)); ++p_fill) {
         a[j - 1 + n_a_1 * (j + p_fill)] = a[j + p_fill + n_a_1 * (j - 1)];
      }
      xf2c_loop_6_continue: ;
      j += 1;
   }
   choldc(n, n_a_1, n_a_2, a, diagmx, tol, &addmax);
   if (addmax > (0.0)) {
      j = 1;
      while (j <= n) {
         a[j - 1 + n_a_1 * (j - 1)] = udiag[j - 1];
         i = j + 1;
         while (i <= n) {
            a[i - 1 + n_a_1 * (j - 1)] = a[j - 1 + n_a_1 * (i - 1)];
            i += 1;
         }
         j += 1;
      }
      evmin = 0.0;
      evmax = a[0];
      i = 1;
      while (i <= n) {
         offrow = 0.0;
         j = 0;
         while (j < i - 1) {
            offrow += (fabs(a[i - 1 + n_a_1 * j]));
            j += 1;
         }
         j = i + 1;
         while (j <= n) {
            offrow += (fabs(a[j - 1 + n_a_1 * (i - 1)]));
            j += 1;
         }
         evmin = fmin(evmin, a[i - 1 + n_a_1 * (i - 1)] - offrow);
         evmax = fmax(evmax, a[i - 1 + n_a_1 * (i - 1)] + offrow);
         i += 1;
      }
      sdd = tol * (evmax - evmin) - evmin;
      amu = fmin(sdd, addmax);
      i = 0;
      while (i < n) {
         a[i + n_a_1 * i] += amu;
         udiag[i] = a[i + n_a_1 * i];
         i += 1;
      }
      choldc(n, n_a_1, n_a_2, a, (0.0), tol, &addmax);
   }
   j = 1;
   while (j <= n) {
      for (int p_fill = 0; p_fill < (((n - j) / 1 + 1)); ++p_fill) {
         a[j + p_fill - 1 + n_a_1 * (j - 1)] = sx[j + p_fill - 1] * a[j + p_fill - 1 + n_a_1 * (j - 1)];
      }
      for (int p_fill = 0; p_fill < (((j - 2) / 1 + 1)); ++p_fill) {
         a[p_fill + n_a_1 * (j - 1)] = sx[p_fill] * sx[j - 1] * a[p_fill + n_a_1 * (j - 1)];
      }
      udiag[j - 1] = udiag[j - 1] * sx[j - 1] * sx[j - 1];
      j += 1;
   }
   return;
}

void dfaut(const int n, const int n_typsiz, double *typsiz, double *fscale, int *method, int *iexp, int *msg, int *ndigit, int *itnlim, int *iagflg, int *iahflg, int *ipr, double *dlt, double *gradtl, double *stepmx, double *steptl) {
   /* n_typsiz: extent of typsiz (dimension 1) */
   const double epsm = DBL_EPSILON, three = 3.0;
   if (1 > 0) {
      for (int i_fill = 1, p_fill = 0; i_fill <= n; i_fill += 1, ++p_fill) {
         typsiz[i_fill - 1] = 1.0;
      }
   } else {
      for (int i_fill = 1, p_fill = 0; i_fill >= n; i_fill += 1, ++p_fill) {
         typsiz[i_fill - 1] = 1.0;
      }
   }
   (*fscale) = 1.0;
   (*dlt) = -(1.0);
   (*gradtl) = pow(DBL_EPSILON, ((1.0)/(3.0)));
   (*stepmx) = 0.0;
   (*steptl) = sqrt(DBL_EPSILON);
   (*method) = 1;
   (*iexp) = 1;
   (*msg) = 0;
   (*ndigit) = -1;
   (*itnlim) = 150;
   (*iagflg) = 0;
   (*iahflg) = 0;
   (*ipr) = 6;
   return;
}

void dogdrv(const int n, const int n_x, const double *x, const double f, const int n_g, const double *g, const int n_a_1, const int n_a_2, const double *a, const int n_p, const double *p, const int n_xpls, double *xpls, double *fpls, void (*fcn)(const int n, const int n_x, const double *x, double *f), const int n_sx, const double *sx, const double stepmx, const double steptl, double *dlt, int *iretcd, int *mxtake) {
   /* n_x: extent of x (dimension 1) */
   /* n_g: extent of g (dimension 1) */
   /* n_a_1: extent of a (dimension 1) */
   /* n_a_2: extent of a (dimension 2) */
   /* n_p: extent of p (dimension 1) */
   /* n_xpls: extent of xpls (dimension 1) */
   /* n_sx: extent of sx (dimension 1) */
   double wrk1[n], wrk2[n], wrk3[n], sc[n], rnwtln, cln, eta, fplsp;
   int fstdog, nwtake;
   /* unsupported: INTERFACE */
   /* unsupported: SUBROUTINE fcn(n, x, f) */
   /* unsupported: END SUBROUTINE fcn */
   /* unsupported: END INTERFACE */
   (*iretcd) = 4;
   fstdog = 1;
   rnwtln = ({ int n_arg_1 = ((n - 1) / 1 + 1); double *tmp_arg_1 = (double*) malloc(sizeof(double) * n_arg_1); if(!tmp_arg_1 && n_arg_1 > 0) exit(1); for(int i_arg_1 = 0; i_arg_1 < n_arg_1; ++i_arg_1) tmp_arg_1[i_arg_1] = sx[i_arg_1]*p[i_arg_1]; double xf2c_ret = dnrm2(n, n_arg_1, tmp_arg_1, 1); free(tmp_arg_1); xf2c_ret; });
   xf2c_stmt_100: ;
   dogstp(n, n_g, g, n_a_1, n_a_2, a, n_p, p, n_sx, sx, rnwtln, dlt, &nwtake, &fstdog, n, wrk1, n, wrk2, &cln, &eta, n, sc, stepmx);
   tregup(n, n_x, x, f, n_g, g, n_a_1, n_a_2, a, fcn, n, sc, n_sx, sx, nwtake, stepmx, steptl, dlt, iretcd, n, wrk3, &fplsp, n_xpls, xpls, fpls, mxtake, 2, n, wrk1);
   if ((*iretcd) <= 1) {
      return;
   }
   goto xf2c_stmt_100;
}

void dogstp(const int n, const int n_g, const double *g, const int n_a_1, const int n_a_2, const double *a, const int n_p, const double *p, const int n_sx, const double *sx, const double rnwtln, double *dlt, int *nwtake, int *fstdog, const int n_ssd, double *ssd, const int n_v, double *v, double *cln, double *eta, const int n_sc, double *sc, const double stepmx) {
   /* n_g: extent of g (dimension 1) */
   /* n_a_1: extent of a (dimension 1) */
   /* n_a_2: extent of a (dimension 2) */
   /* n_p: extent of p (dimension 1) */
   /* n_sx: extent of sx (dimension 1) */
   /* n_ssd: extent of ssd (dimension 1) */
   /* n_v: extent of v (dimension 1) */
   /* n_sc: extent of sc (dimension 1) */
   int i;
   double alpha, beta, tmp, dot1, dot2, alam;
   if (rnwtln > (*dlt)) {
      goto xf2c_stmt_100;
   }
   (*nwtake) = 1;
   if (1 > 0) {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
         sc[i_fill - 1] = p[p_fill];
      }
   } else {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
         sc[i_fill - 1] = p[p_fill];
      }
   }
   (*dlt) = rnwtln;
   goto xf2c_stmt_700;
   xf2c_stmt_100: ;
   (*nwtake) = 0;
   if (! (*fstdog)) {
      goto xf2c_stmt_200;
   }
   (*fstdog) = 0;
   if (1 > 0) {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
         ssd[i_fill - 1] = g[p_fill]/sx[p_fill];
      }
   } else {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
         ssd[i_fill - 1] = g[p_fill]/sx[p_fill];
      }
   }
   {
      double red = 0.0;
      for (int i_fill = 0; i_fill < (((n - 1) / 1 + 1)); ++i_fill) red += (ssd[i_fill] * ssd[i_fill]);
      alpha = red;
   }
   beta = 0.0;
   i = 1;
   while (i <= n) {
      tmp = 0.0;
      while (i <= n) {
         tmp += (a[i - 1 + n_a_1 * (i - 1)]/sx[i - 1])*ssd[i - 1];
         i += 1;
      }
      beta += tmp*tmp;
      xf2c_loop_1_continue: ;
      i += 1;
   }
   xf2c_loop_1_break: ;
   if (1 > 0) {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
         ssd[i_fill - 1] = -(alpha/beta)*ssd[p_fill];
      }
   } else {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
         ssd[i_fill - 1] = -(alpha/beta)*ssd[p_fill];
      }
   }
   (*cln) = alpha*(sqrt(alpha))/beta;
   (*eta) = .2 + (0.8 * alpha * alpha) / (-beta * ({ double red = 0.0; for (int i_red = 0; i_red < ((((n - 1) / 1 + 1))); ++i_red) red += (g[i_red]) * (p[i_red]); red; }));
   if (1 > 0) {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
         v[i_fill - 1] = (*eta)*sx[p_fill]*p[p_fill] - ssd[p_fill];
      }
   } else {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
         v[i_fill - 1] = (*eta)*sx[p_fill]*p[p_fill] - ssd[p_fill];
      }
   }
   if ((*dlt) == -(1.0)) {
      (*dlt) = fmin((*cln), stepmx);
   }
   xf2c_stmt_200: ;
   if ((*eta)*rnwtln > (*dlt)) goto xf2c_stmt_220;
   if (1 > 0) {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
         sc[i_fill - 1] = ((*dlt)/rnwtln)*p[p_fill];
      }
   } else {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
         sc[i_fill - 1] = ((*dlt)/rnwtln)*p[p_fill];
      }
   }
   goto xf2c_stmt_700;
   xf2c_stmt_220: ;
   if ((*cln) < (*dlt)) goto xf2c_stmt_240;
   if (1 > 0) {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
         sc[i_fill - 1] = ((*dlt)/(*cln))*ssd[p_fill]/sx[p_fill];
      }
   } else {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
         sc[i_fill - 1] = ((*dlt)/(*cln))*ssd[p_fill]/sx[p_fill];
      }
   }
   goto xf2c_stmt_700;
   xf2c_stmt_240: ;
   dot1 = ({ double red = 0.0; for (int i_red = 0; i_red < ((((n - 1) / 1 + 1))); ++i_red) red += (v[i_red]) * (ssd[i_red]); red; });
   {
      double red = 0.0;
      for (int i_fill = 0; i_fill < (((n - 1) / 1 + 1)); ++i_fill) red += (v[i_fill] * v[i_fill]);
      dot2 = red;
   }
   alam = (-dot1 + (sqrt(dot1*dot1 - dot2*((*cln)*(*cln) - (*dlt)*(*dlt)))))/dot2;
   if (1 > 0) {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
         sc[i_fill - 1] = (ssd[p_fill] + alam * v[p_fill])/sx[p_fill];
      }
   } else {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
         sc[i_fill - 1] = (ssd[p_fill] + alam * v[p_fill])/sx[p_fill];
      }
   }
   xf2c_stmt_700: ;
   return;
}

void forslv(const int n, const int n_a_1, const int n_a_2, const double *a, const int n_x, double *x, const int n_b, const double *b) {
   /* PURPOSE */
   /* n_a_1: extent of a (dimension 1) */
   /* n_a_2: extent of a (dimension 2) */
   /* n_x: extent of x (dimension 1) */
   /* n_b: extent of b (dimension 1) */
   int i;
   double sum;
   x[0] = b[0]/a[0];
   i = 2;
   while (i <= n) {
      sum = ({ double red = 0.0; for (int i_red = 0; i_red < ((((i - 2) / 1 + 1))); ++i_red) red += (a[i - 1 + n_a_1 * i_red]) * (x[i_red]); red; });
      x[i - 1] = (b[i - 1] - sum)/a[i - 1 + n_a_1 * (i - 1)];
      xf2c_loop_1_continue: ;
      i += 1;
   }
   xf2c_loop_1_break: ;
   return;
}

void fstocd(const int n, const int n_x, double *x, void (*fcn)(const int n, const int n_x, const double *x, double *f), const int n_sx, const double *sx, const double rnoise, const int n_g, double *g) {
   /* PURPOSE */
   /* n_x: extent of x (dimension 1) */
   /* n_sx: extent of sx (dimension 1) */
   /* n_g: extent of g (dimension 1) */
   double third, xtempi, fplus, fminus, stepi;
   int i;
   /* unsupported: INTERFACE */
   /* unsupported: SUBROUTINE fcn(n, x, f) */
   /* unsupported: END SUBROUTINE fcn */
   /* unsupported: END INTERFACE */
   third = (1.0)/3.0;
   i = 0;
   while (i < n) {
      stepi = pow(rnoise, third) * fmax((fabs(x[i])), (1.0)/sx[i]);
      xtempi = x[i];
      x[i] = xtempi + stepi;
      fcn(n, n_x, x, &fplus);
      x[i] = xtempi - stepi;
      fcn(n, n_x, x, &fminus);
      x[i] = xtempi;
      g[i] = (fplus - fminus)/(2.0 * stepi);
      xf2c_loop_1_continue: ;
      i += 1;
   }
   xf2c_loop_1_break: ;
   return;
}

void fstofd(const int m, const int n, const int n_xpls, double *xpls, void (*fcn)(const int n, const int n_x, const double *x, double *f), const int n_fpls, const double *fpls, const int n_a_1, const int n_a_2, double *a, const int n_sx, const double *sx, const double rnoise, const int icase) {
   /* PURPOSE */
   /* n_xpls: extent of xpls (dimension 1) */
   /* n_fpls: extent of fpls (dimension 1) */
   /* n_a_1: extent of a (dimension 1) */
   /* n_a_2: extent of a (dimension 2) */
   /* n_sx: extent of sx (dimension 1) */
   double fhat[m], stepsz, xtmpj, sqrtr, rstepsz;
   int i, j, nm1, jp1;
   const double half = 0.5;
   /* unsupported: INTERFACE */
   /* unsupported: SUBROUTINE fcn(n, x, f) */
   /* unsupported: END SUBROUTINE fcn */
   /* unsupported: END INTERFACE */
   sqrtr = sqrt(rnoise);
   j = 0;
   while (j < n) {
      stepsz = sqrtr * fmax((fabs(xpls[j])), (1.0)/sx[j]);
      xtmpj = xpls[j];
      xpls[j] = xtmpj + stepsz;
      fcn(n, n_xpls, xpls, &(fhat[j]));
      xpls[j] = xtmpj;
      rstepsz = (1.0)/stepsz;
      i = 0;
      while (i < m) {
         a[i + n_a_1 * j] = (fhat[i] - fpls[i]) * rstepsz;
         i += 1;
      }
      xf2c_loop_1_continue: ;
      j += 1;
   }
   xf2c_loop_1_break: ;
   if (icase != 3) {
      return;
   }
   if (n == 1) {
      return;
   }
   nm1 = n - 1;
   j = 1;
   while (j <= nm1) {
      jp1 = j + 1;
      i = jp1;
      while (i <= m) {
         a[i - 1 + n_a_1 * (j - 1)] = (a[i - 1 + n_a_1 * (j - 1)] + a[j - 1 + n_a_1 * (i - 1)]) * 0.5;
         i += 1;
      }
      xf2c_loop_3_continue: ;
      j += 1;
   }
   return;
}

void estimate_hessian(const int m, const int n, const int n_xpls, double *xpls, void (*d1fcn)(const int n, const int n_x, const double *x, const int n_g, double *g), const int n_fpls, const double *fpls, const int n_a_1, const int n_a_2, double *a, const int n_sx, const double *sx, const double rnoise, const int icase) {
   /* PURPOSE */
   /* n_xpls: extent of xpls (dimension 1) */
   /* n_fpls: extent of fpls (dimension 1) */
   /* n_a_1: extent of a (dimension 1) */
   /* n_a_2: extent of a (dimension 2) */
   /* n_sx: extent of sx (dimension 1) */
   double fhat[m], stepsz, xtmpj, sqrtr, rstepsz;
   int i, j, nm1, jp1;
   const double half = 0.5;
   /* unsupported: INTERFACE */
   /* unsupported: SUBROUTINE d1fcn(n, x, g) */
   /* unsupported: END SUBROUTINE d1fcn */
   /* unsupported: END INTERFACE */
   sqrtr = sqrt(rnoise);
   j = 0;
   while (j < n) {
      stepsz = sqrtr * fmax((fabs(xpls[j])), (1.0)/sx[j]);
      xtmpj = xpls[j];
      xpls[j] = xtmpj + stepsz;
      d1fcn(n, n_xpls, xpls, m, fhat);
      xpls[j] = xtmpj;
      rstepsz = (1.0)/stepsz;
      i = 0;
      while (i < m) {
         a[i + n_a_1 * j] = (fhat[i] - fpls[i]) * rstepsz;
         i += 1;
      }
      xf2c_loop_1_continue: ;
      j += 1;
   }
   xf2c_loop_1_break: ;
   if (icase != 3) {
      return;
   }
   if (n == 1) {
      return;
   }
   nm1 = n - 1;
   j = 1;
   while (j <= nm1) {
      jp1 = j + 1;
      i = jp1;
      while (i <= m) {
         a[i - 1 + n_a_1 * (j - 1)] = (a[i - 1 + n_a_1 * (j - 1)] + a[j - 1 + n_a_1 * (i - 1)]) * 0.5;
         i += 1;
      }
      xf2c_loop_3_continue: ;
      j += 1;
   }
   return;
}

void hookdr(const int n, const int n_g, const double *g, const int n_a_1, const int n_a_2, double *a, const int n_udiag, const double *udiag, const int n_p, const double *p, const int n_sx, const double *sx, const double stepmx, double *dlt, int *iretcd, double *amu, double *dltp, double *phi, double *phip0, const double epsm, const int itncnt) {
   /* n_g: extent of g (dimension 1) */
   /* n_a_1: extent of a (dimension 1) */
   /* n_a_2: extent of a (dimension 2) */
   /* n_udiag: extent of udiag (dimension 1) */
   /* n_p: extent of p (dimension 1) */
   /* n_sx: extent of sx (dimension 1) */
   int i, fstime;
   double tmp, rnwtln, alpha, beta;
   (*iretcd) = 4;
   fstime = 1;
   {
      double red = 0.0;
      for (int i_fill = 0; i_fill < (((n - 1) / 1 + 1)); ++i_fill) red += (sx[i_fill] * p[i_fill] * sx[i_fill] * p[i_fill]);
      tmp = red;
   }
   rnwtln = sqrt(tmp);
   if (itncnt == 1) {
      (*amu) = 0.0;
      if ((*dlt) == -(1.0)) {
         {
            double red = 0.0;
            for (int i_fill = 0; i_fill < (((n - 1) / 1 + 1)); ++i_fill) red += ((g[i_fill]/sx[i_fill]) * (g[i_fill]/sx[i_fill]));
            alpha = red;
         }
         beta = 0.0;
         i = 1;
         while (i <= n) {
            {
               double red = 0.0;
               for (int i_fill = 0; i_fill < (((n - i) / 1 + 1)); ++i_fill) red += a[i + i_fill - 1 + n_a_1 * (i - 1)]*g[i + i_fill - 1] / (sx[i + i_fill - 1] * sx[i + i_fill - 1]);
               tmp = red;
            }
            beta += tmp*tmp;
            xf2c_loop_1_continue: ;
            i += 1;
         }
         xf2c_loop_1_break: ;
         (*dlt) = alpha*(sqrt(alpha))/beta;
         (*dlt) = fmin((*dlt), stepmx);
      }
   }
   hookst(n, n_g, g, n_a_1, n_a_2, a, n_udiag, udiag, n_p, p, n_sx, sx, rnwtln, dlt, amu, (*dltp), phi, phip0, &fstime, epsm);
   (*dltp) = (*dlt);
   return;
}

void hookst(const int n, const int n_g, const double *g, const int n_a_1, const int n_a_2, double *a, const int n_udiag, const double *udiag, const int n_p, const double *p, const int n_sx, const double *sx, const double rnwtln, double *dlt, double *amu, const double dltp, double *phi, double *phip0, int *fstime, const double epsm) {
   /* n_g: extent of g (dimension 1) */
   /* n_a_1: extent of a (dimension 1) */
   /* n_a_2: extent of a (dimension 2) */
   /* n_udiag: extent of udiag (dimension 1) */
   /* n_p: extent of p (dimension 1) */
   /* n_sx: extent of sx (dimension 1) */
   double wrk0[n], sc[n], hi, alo, phip, amuup, stepln, amulo;
   int jp1, j, done;
   hi = 1.5;
   alo = 0.75;
   if (rnwtln <= hi*(*dlt)) {
      if (1 > 0) {
         for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
            sc[i_fill - 1] = p[p_fill];
         }
      } else {
         for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
            sc[i_fill - 1] = p[p_fill];
         }
      }
      (*dlt) = fmin((*dlt),rnwtln);
      (*amu) = 0.0;
      return;
   }
   phip = 1.0;
   if ((*amu) > (0.0)) {
      (*amu) = (*amu) - ((*phi)+dltp) *((dltp-(*dlt)) + (*phi)) / ((*dlt)*phip);
   }
   (*phi) = rnwtln - (*dlt);
   if ((*fstime)) {
      if (1 > 0) {
         for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
            wrk0[i_fill - 1] = sx[p_fill] * sx[p_fill] * p[p_fill];
         }
      } else {
         for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
            wrk0[i_fill - 1] = sx[p_fill] * sx[p_fill] * p[p_fill];
         }
      }
      forslv(n, n_a_1, n_a_2, a, n, wrk0, n, wrk0);
      (*phip0) = - (dnrm2(n, n, wrk0, 1) * dnrm2(n, n, wrk0, 1)) / rnwtln;
      (*fstime) = 0;
   }
   phip = (*phip0);
   amulo = -(*phi)/phip;
   {
      double red = 0.0;
      for (int i_fill = 0; i_fill < (((n - 1) / 1 + 1)); ++i_fill) red += ((g[i_fill]/sx[i_fill]) * (g[i_fill]/sx[i_fill]));
      amuup = red;
   }
   amuup = (sqrt(amuup))/(*dlt);
   done = 0;
   xf2c_stmt_100: ;
   if (done) return;
   if ((*amu) < amulo || (*amu) > amuup) {
      (*amu) = fmax(sqrt(amulo * amuup), amuup * 0.001);
   }
   j = 1;
   while (j <= n) {
      a[j - 1 + n_a_1 * (j - 1)] = udiag[j - 1] + (*amu)*sx[j - 1]*sx[j - 1];
      if (j == n) {
         goto xf2c_loop_1_continue;
      }
      jp1 = j + 1;
      while (jp1 <= n) {
         a[jp1 - 1 + n_a_1 * (j - 1)] = a[j - 1 + n_a_1 * (jp1 - 1)];
         jp1 += 1;
      }
      xf2c_loop_1_continue: ;
      j += 1;
   }
   xf2c_loop_1_break: ;
   choldc(n, n_a_1, n_a_2, a, (0.0), (sqrt(epsm)), NULL);
   if (1 > 0) {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
         wrk0[i_fill - 1] = -g[p_fill];
      }
   } else {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
         wrk0[i_fill - 1] = -g[p_fill];
      }
   }
   lltslv(n, n_a_1, n_a_2, a, n, sc, n, wrk0);
   {
      double red = 0.0;
      for (int i_fill = 0; i_fill < (((n - 1) / 1 + 1)); ++i_fill) red += (sx[i_fill] * sx[i_fill]) * (sc[i_fill] * sc[i_fill]);
      stepln = red;
   }
   stepln = sqrt(stepln);
   (*phi) = stepln - (*dlt);
   if (1 > 0) {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
         wrk0[i_fill - 1] = sx[p_fill] * sx[p_fill] * sc[p_fill];
      }
   } else {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
         wrk0[i_fill - 1] = sx[p_fill] * sx[p_fill] * sc[p_fill];
      }
   }
   forslv(n, n_a_1, n_a_2, a, n, wrk0, n, wrk0);
   phip = -(dnrm2(n, n, wrk0, 1) * dnrm2(n, n, wrk0, 1))/stepln;
   if ((alo*(*dlt) > stepln || stepln > hi*(*dlt)) &&     (amuup-amulo > (0.0))) goto xf2c_stmt_170;
   done = 1;
   goto xf2c_stmt_100;
   xf2c_stmt_170: ;
   amulo = fmax(amulo, (*amu)-((*phi)/phip));
   if ((*phi) < (0.0)) {
      amuup = fmin(amuup,(*amu));
   }
   (*amu) = (*amu) - (stepln*(*phi))/((*dlt)*phip);
   goto xf2c_stmt_100;
}

void hsnint(const int n, const int n_a_1, const int n_a_2, double *a, const int n_sx, const double *sx, const int method) {
   /* PURPOSE */
   /* n_a_1: extent of a (dimension 1) */
   /* n_a_2: extent of a (dimension 2) */
   /* n_sx: extent of sx (dimension 1) */
   int j = 1;
   while (j <= n) {
      if (method == 3) {
         a[j - 1 + n_a_1 * (j - 1)] = sx[j - 1] * sx[j - 1];
      }
      if (method != 3) {
         a[j - 1 + n_a_1 * (j - 1)] = sx[j - 1];
      }
      if (j == n) {
         goto xf2c_loop_1_continue;
      }
      for (int p_fill = 0; p_fill < (((n - j - 1) / 1 + 1)); ++p_fill) {
         a[j + p_fill + n_a_1 * (j - 1)] = 0.0;
      }
      xf2c_loop_1_continue: ;
      j += 1;
   }
   xf2c_loop_1_break: ;
   return;
}

void lltslv(const int n, const int n_a_1, const int n_a_2, const double *a, const int n_x, double *x, const int n_b, const double *b) {
   /* PURPOSE */
   /* n_a_1: extent of a (dimension 1) */
   /* n_a_2: extent of a (dimension 2) */
   /* n_x: extent of x (dimension 1) */
   /* n_b: extent of b (dimension 1) */
   double wk[n];
   forslv(n, n_a_1, n_a_2, a, n, wk, n_b, b);
   bakslv(n, n_a_1, n_a_2, a, n_x, x, n, wk);
   return;
}

void optchk(const int n, const int n_x, const double *x, const int n_typsiz, double *typsiz, const int n_sx, double *sx, double *fscale, int *itnlim, int *ndigit, const double epsm, double *dlt, int *method, int *iexp, int *iagflg, int *iahflg, double *stepmx, int *msg) {
   /* n_x: extent of x (dimension 1) */
   /* n_typsiz: extent of typsiz (dimension 1) */
   /* n_sx: extent of sx (dimension 1) */
   double stpsiz;
   int i = 1;
   while (i <= n) {
      if (typsiz[i - 1] == (0.0)) {
         typsiz[i - 1] = 1.0;
      }
      if (typsiz[i - 1] < (0.0)) {
         typsiz[i - 1] = -typsiz[i - 1];
      }
      sx[i - 1] = (1.0)/typsiz[i - 1];
      xf2c_loop_1_continue: ;
      i += 1;
   }
   xf2c_loop_1_break: ;
   stpsiz = 0.0;
   i = 0;
   while (i < n) {
      stpsiz += x[i]*x[i]*sx[i]*sx[i];
      i += 1;
   }
   stpsiz = sqrt(stpsiz);
   (*stepmx) = fmax(1000.0 * stpsiz, 1000.0);
   (*ndigit) = -log10(epsm);
   return;
}

void optdrv(const int nr, const int n, const int n_x, double *x, void (*fcn)(const int n, const int n_x, const double *x, double *f), void (*d1fcn)(const int n, const int n_x, const double *x, const int n_g, double *g), void (*d2fcn)(const int nr, const int n, const int n_x, const double *x, const int n_h_1, const int n_h_2, double *h), const int n_typsiz, double *typsiz, double *fscale, int *method, int *iexp, int *msg, int *ndigit, int *itnlim, int *iagflg, int *iahflg, double *dlt, const double gradtl, double *stepmx, const double steptl, const int n_xpls, double *xpls, double *fpls, const int n_gpls, double *gpls, int *itrmcd) {
   /* n_x: extent of x (dimension 1) */
   /* n_typsiz: extent of typsiz (dimension 1) */
   /* n_xpls: extent of xpls (dimension 1) */
   /* n_gpls: extent of gpls (dimension 1) */
   double a[n * n], udiag[n], g[n], p[n], sx[n], wrk1[n], epsm, f, rnf, dltsav, amusav, amu, dlpsav, dltp;
   double phisav, phi, phpsav, phip0, work2[n];
   int i, itncnt, iretcd, icscmx, mxtake;
   /* unsupported: INTERFACE */
   /* unsupported: SUBROUTINE fcn(n, x, f) */
   /* unsupported: END SUBROUTINE fcn */
   /* unsupported: SUBROUTINE d1fcn(n, x, g) */
   /* unsupported: END SUBROUTINE d1fcn */
   /* unsupported: SUBROUTINE d2fcn(nr, n, x, h) */
   /* unsupported: END SUBROUTINE d2fcn */
   /* unsupported: END INTERFACE */
   if (1 > 0) {
      for (int i_fill = 1, p_fill = 0; i_fill <= n; i_fill += 1, ++p_fill) {
         p[i_fill - 1] = 0.0;
      }
   } else {
      for (int i_fill = 1, p_fill = 0; i_fill >= n; i_fill += 1, ++p_fill) {
         p[i_fill - 1] = 0.0;
      }
   }
   itncnt = 0;
   iretcd = -1;
   epsm = DBL_EPSILON;
   optchk(n, n_x, x, n_typsiz, typsiz, n, sx, fscale, itnlim, ndigit, epsm, dlt, method, iexp, iagflg, iahflg, stepmx, msg);
   if ((*msg) < 0) {
      return;
   }
   rnf = fmax(pow(10.0e0, (-(*ndigit))), epsm);
   fcn(n, n_x, x, &f);
   if ((*iagflg) == 1) {
      d1fcn(n, n_x, x, n, g);
   }
   else {
      fstofd(1, n, n_x, x, fcn, n, g, n, n, a, n, sx, rnf, 1);
   }
   optstp(n, n_x, x, f, n, g, n, wrk1, itncnt, &icscmx, itrmcd, gradtl, steptl, n, sx, (*fscale), (*itnlim), iretcd, mxtake);
   if ((*itrmcd) != 0) {
      goto xf2c_stmt_700;
   }
   if ((*iexp) != 1) {
      goto xf2c_stmt_80;
   }
   hsnint(n, n, n, a, n, sx, (*method));
   goto xf2c_stmt_100;
   xf2c_stmt_80: ;
   if ((*iahflg) == 0) {
      if ((*iagflg) == 1) {
         estimate_hessian(n, n, n_x, x, d1fcn, n, g, n, n, a, n, sx, rnf, 3);
      }
      if ((*iagflg) != 1) {
         sndofd(n, n_x, x, fcn, f, n, n, a, n, sx, rnf);
      }
   }
   else {
      /* Inserted by AJM */
      d2fcn(nr, n, n_x, x, n, n, a);
   }
   xf2c_stmt_100: ;
   itncnt += 1;
   if ((*iexp) == 1 && (*method) != 3) {
      goto xf2c_stmt_105;
   }
   xf2c_stmt_103: ;
   chlhsn(n, n, n, a, epsm, n, sx, n, udiag);
   xf2c_stmt_105: ;
   if (1 > 0) {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
         wrk1[i_fill - 1] = -g[p_fill];
      }
   } else {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
         wrk1[i_fill - 1] = -g[p_fill];
      }
   }
   lltslv(n, n, n, a, n, p, n, wrk1);
   if ((*iagflg) != 0 || (*method) == 1) {
      goto xf2c_stmt_111;
   }
   dltsav = (*dlt);
   if ((*method) == 2) {
      goto xf2c_stmt_111;
   }
   amusav = amu;
   dlpsav = dltp;
   phisav = phi;
   phpsav = phip0;
   xf2c_stmt_111: ;
   if ((*method) == 2) dogdrv(n, n_x, x, f, n, g, n, n, a, n, p, n_xpls, xpls, fpls, fcn, n, sx, (*stepmx), steptl, dlt, &iretcd, &mxtake);
   if ((*method) == 3) hookdr(n, n, g, n, n, a, n, udiag, n, p, n, sx, (*stepmx), dlt, &iretcd, &amu, &dltp, &phi, &phip0, epsm, itncnt);
   if ((*method) != 2) {
      /* Added by AJM */
      if (1 > 0) {
         for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
            xpls[i_fill - 1] = x[p_fill] + p[p_fill];
         }
      } else {
         for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
            xpls[i_fill - 1] = x[p_fill] + p[p_fill];
         }
      }
   }
   if (iretcd == 1 && (*iagflg) == 0) {
      (*iagflg) = -1;
      fstocd(n, n_x, x, fcn, n, sx, rnf, n, g);
      if ((*method) == 1) {
         goto xf2c_stmt_105;
      }
      (*dlt) = dltsav;
      if ((*method) == 2) {
         goto xf2c_stmt_105;
      }
      amu = amusav;
      dltp = dlpsav;
      phi = phisav;
      phip0 = phpsav;
      goto xf2c_stmt_103;
   }
   if (1 > 0) {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
         p[i_fill - 1] = xpls[p_fill] - x[p_fill];
      }
   } else {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
         p[i_fill - 1] = xpls[p_fill] - x[p_fill];
      }
   }
   if ((*iagflg) == -1) {
      goto xf2c_stmt_116;
   }
   if ((*iagflg) == 0) {
      goto xf2c_stmt_118;
   }
   d1fcn(n, n_xpls, xpls, n_gpls, gpls);
   goto xf2c_stmt_120;
   xf2c_stmt_116: ;
   fstocd(n, n_xpls, xpls, fcn, n, sx, rnf, n_gpls, gpls);
   goto xf2c_stmt_120;
   xf2c_stmt_118: ;
   fstofd(1, n, n_xpls, xpls, fcn, n, wrk1, n, 1, work2, n, sx, rnf, 1);
   if (1 > 0) {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
         gpls[i_fill - 1] = work2[p_fill];
      }
   } else {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
         gpls[i_fill - 1] = work2[p_fill];
      }
   }
   xf2c_stmt_120: ;
   optstp(n, n_xpls, xpls, (*fpls), n_gpls, gpls, n_x, x, itncnt, &icscmx, itrmcd, gradtl, steptl, n, sx, (*fscale), (*itnlim), iretcd, mxtake);
   if ((*itrmcd) != 0) {
      goto xf2c_stmt_690;
   }
   if ((*iexp) != 0) {
      goto xf2c_stmt_150;
   }
   if ((*iahflg) == 1) {
      goto xf2c_stmt_140;
   }
   if ((*iagflg) == 1) {
      estimate_hessian(n, n, n_xpls, xpls, d1fcn, n_gpls, gpls, n, n, a, n, sx, rnf, 3);
   }
   if ((*iagflg) != 1) {
      sndofd(n, n_xpls, xpls, fcn, (*fpls), n, n, a, n, sx, rnf);
   }
   goto xf2c_stmt_150;
   xf2c_stmt_140: ;
   d2fcn(nr, n, n_xpls, xpls, n, n, a);
   xf2c_stmt_150: ;
   f = (*fpls);
   i = 0;
   while (i < n) {
      x[i] = xpls[i];
      g[i] = gpls[i];
      xf2c_loop_1_continue: ;
      i += 1;
   }
   xf2c_loop_1_break: ;
   goto xf2c_stmt_100;
   xf2c_stmt_690: ;
   if ((*itrmcd) != 3) goto xf2c_stmt_710;
   xf2c_stmt_700: ;
   (*fpls) = f;
   i = 0;
   while (i < n) {
      xpls[i] = x[i];
      gpls[i] = g[i];
      i += 1;
   }
   xf2c_stmt_710: ;
   (*msg) = 0;
   return;
}

void optif9(const int nr, const int n, const int n_x, double *x, void (*fcn)(const int n, const int n_x, const double *x, double *f), void (*d1fcn)(const int n, const int n_x, const double *x, const int n_g, double *g), void (*d2fcn)(const int nr, const int n, const int n_x, const double *x, const int n_h_1, const int n_h_2, double *h), const int n_typsiz, double *typsiz, double *fscale, int *method, int *iexp, int *msg, int *ndigit, int *itnlim, int *iagflg, int *iahflg, double *dlt, const double gradtl, double *stepmx, const double steptl, const int n_xpls, double *xpls, double *fpls, const int n_gpls, double *gpls, int *itrmcd) {
   /* n_x: extent of x (dimension 1) */
   /* n_typsiz: extent of typsiz (dimension 1) */
   /* n_xpls: extent of xpls (dimension 1) */
   /* n_gpls: extent of gpls (dimension 1) */
   /* unsupported: INTERFACE */
   /* unsupported: SUBROUTINE fcn(n, x, f) */
   /* unsupported: END SUBROUTINE fcn */
   /* unsupported: SUBROUTINE d1fcn(n, x, g) */
   /* unsupported: END SUBROUTINE d1fcn */
   /* unsupported: SUBROUTINE d2fcn(nr, n, x, h) */
   /* unsupported: END SUBROUTINE d2fcn */
   /* unsupported: END INTERFACE */
   optdrv(nr, n, n_x, x, fcn, d1fcn, d2fcn, n_typsiz, typsiz, fscale, method, iexp, msg, ndigit, itnlim, iagflg, iahflg, dlt, gradtl, stepmx, steptl, n_xpls, xpls, fpls, n_gpls, gpls, itrmcd);
   return;
}

void optstp(const int n, const int n_xpls, const double *xpls, const double fpls, const int n_gpls, const double *gpls, const int n_x, const double *x, const int itncnt, int *icscmx, int *itrmcd, const double gradtl, const double steptl, const int n_sx, const double *sx, const double fscale, const int itnlim, const int iretcd, const int mxtake) {
   /* n_xpls: extent of xpls (dimension 1) */
   /* n_gpls: extent of gpls (dimension 1) */
   /* n_x: extent of x (dimension 1) */
   /* n_sx: extent of sx (dimension 1) */
   int i, jtrmcd;
   double d, rgx, relgrd, relstp, rsx;
   (*itrmcd) = 0;
   if (iretcd == 1) {
      jtrmcd = 3;
      goto xf2c_stmt_600;
   }
   d = fmax(fabs(fpls), fscale);
   rgx = 0.0;
   i = 0;
   while (i < n) {
      relgrd = (fabs(gpls[i])) * fmax((fabs(xpls[i])), (1.0)/sx[i])/d;
      rgx = fmax(rgx, relgrd);
      xf2c_loop_1_continue: ;
      i += 1;
   }
   xf2c_loop_1_break: ;
   jtrmcd = 1;
   if (rgx <= gradtl) {
      goto xf2c_stmt_600;
   }
   if (itncnt == 0) {
      return;
   }
   rsx = 0.0;
   i = 0;
   while (i < n) {
      relstp = (fabs(xpls[i] - x[i])) / fmax((fabs(xpls[i])), (1.0)/sx[i]);
      rsx = fmax(rsx, relstp);
      i += 1;
   }
   jtrmcd = 2;
   if (rsx <= steptl) {
      goto xf2c_stmt_600;
   }
   jtrmcd = 4;
   if (itncnt >= itnlim) {
      goto xf2c_stmt_600;
   }
   if (! mxtake) {
      (*icscmx) = 0;
      return;
   }
   (*icscmx) = (*icscmx) + 1;
   if ((*icscmx) < 5) {
      return;
   }
   jtrmcd = 5;
   xf2c_stmt_600: ;
   (*itrmcd) = jtrmcd;
   return;
}

void sndofd(const int n, const int n_xpls, double *xpls, void (*fcn)(const int n, const int n_x, const double *x, double *f), const double fpls, const int n_a_1, const int n_a_2, double *a, const int n_sx, const double *sx, const double rnoise) {
   /* PURPOSE */
   /* n_xpls: extent of xpls (dimension 1) */
   /* n_a_1: extent of a (dimension 1) */
   /* n_a_2: extent of a (dimension 2) */
   /* n_sx: extent of sx (dimension 1) */
   double stepsz[n], anbr[n], ov3, xtmpi, xtmpj, fhat;
   int i, ip1;
   /* unsupported: INTERFACE */
   /* unsupported: SUBROUTINE fcn(n, x, f) */
   /* unsupported: END SUBROUTINE fcn */
   /* unsupported: END INTERFACE */
   ov3 = (1.0)/3.0;
   i = 0;
   while (i < n) {
      stepsz[i] = pow(rnoise, ov3) * fmax((fabs(xpls[i])), (1.0)/sx[i]);
      xtmpi = xpls[i];
      xpls[i] = xtmpi + stepsz[i];
      fcn(n, n_xpls, xpls, &(anbr[i]));
      xpls[i] = xtmpi;
      xf2c_loop_1_continue: ;
      i += 1;
   }
   xf2c_loop_1_break: ;
   i = 1;
   while (i <= n) {
      xtmpi = xpls[i - 1];
      xpls[i - 1] = xtmpi + 2.0 * stepsz[i - 1];
      fcn(n, n_xpls, xpls, &fhat);
      a[i - 1 + n_a_1 * (i - 1)] = (fpls - anbr[i - 1] + fhat - anbr[i - 1]) / (stepsz[i - 1] * stepsz[i - 1]);
      if (i == n) {
         goto xf2c_stmt_25;
      }
      xpls[i - 1] = xtmpi + stepsz[i - 1];
      ip1 = i + 1;
      while (ip1 <= n) {
         xtmpj = xpls[ip1 - 1];
         xpls[ip1 - 1] = xtmpj + stepsz[ip1 - 1];
         fcn(n, n_xpls, xpls, &fhat);
         a[ip1 - 1 + n_a_1 * (i - 1)] = (fpls - anbr[i - 1] + fhat - anbr[ip1 - 1]) / (stepsz[i - 1] * stepsz[ip1 - 1]);
         xpls[ip1 - 1] = xtmpj;
         xf2c_loop_3_continue: ;
         ip1 += 1;
      }
      xf2c_stmt_25: ;
      xpls[i - 1] = xtmpi;
      i += 1;
   }
   return;
}

void tregup(const int n, const int n_x, const double *x, const double f, const int n_g, const double *g, const int n_a_1, const int n_a_2, const double *a, void (*fcn)(const int n, const int n_x, const double *x, double *f), const int n_sc, const double *sc, const int n_sx, const double *sx, const int nwtake, const double stepmx, const double steptl, double *dlt, int *iretcd, const int n_xplsp, double *xplsp, double *fplsp, const int n_xpls, double *xpls, double *fpls, int *mxtake, const int method, const int n_udiag, const double *udiag) {
   /* n_x: extent of x (dimension 1) */
   /* n_g: extent of g (dimension 1) */
   /* n_a_1: extent of a (dimension 1) */
   /* n_a_2: extent of a (dimension 2) */
   /* n_sc: extent of sc (dimension 1) */
   /* n_sx: extent of sx (dimension 1) */
   /* n_xplsp: extent of xplsp (dimension 1) */
   /* n_xpls: extent of xpls (dimension 1) */
   /* n_udiag: extent of udiag (dimension 1) */
   int i, ip1;
   double slp, rln, dltmp, dltfp, temp, dltf;
   /* unsupported: INTERFACE */
   /* unsupported: SUBROUTINE fcn(n, x, f) */
   /* unsupported: END SUBROUTINE fcn */
   /* unsupported: END INTERFACE */
   (*mxtake) = 0;
   if (1 > 0) {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
         xpls[i_fill - 1] = x[p_fill] + sc[p_fill];
      }
   } else {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
         xpls[i_fill - 1] = x[p_fill] + sc[p_fill];
      }
   }
   fcn(n, n_xpls, xpls, fpls);
   dltf = (*fpls) - f;
   slp = ({ double red = 0.0; for (int i_red = 0; i_red < ((((n - 1) / 1 + 1))); ++i_red) red += (g[i_red]) * (sc[i_red]); red; });
   if ((*iretcd) == 4) {
      (*fplsp) = 0.0;
   }
   if ((*iretcd) != 3 || ((*fpls) < (*fplsp) && dltf <= 1.e-4*slp)) {
      goto xf2c_stmt_130;
   }
   (*iretcd) = 0;
   if (1 > 0) {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
         xpls[i_fill - 1] = xplsp[p_fill];
      }
   } else {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
         xpls[i_fill - 1] = xplsp[p_fill];
      }
   }
   (*fpls) = (*fplsp);
   (*dlt) = .5*(*dlt);
   goto xf2c_stmt_230;
   xf2c_stmt_130: ;
   if (dltf <= 1.e-4*slp) goto xf2c_stmt_170;
   rln = 0.0;
   i = 0;
   while (i < n) {
      rln = fmax(rln,(fabs(sc[i])) / fmax((fabs(xpls[i])),1./sx[i]));
      xf2c_loop_1_continue: ;
      i += 1;
   }
   xf2c_loop_1_break: ;
   if (rln >= steptl) {
      goto xf2c_stmt_150;
   }
   (*iretcd) = 1;
   goto xf2c_stmt_230;
   xf2c_stmt_150: ;
   (*iretcd) = 2;
   dltmp = -slp*(*dlt)/(2.0 * (dltf - slp));
   if (dltmp >= .1*(*dlt)) {
      goto xf2c_stmt_155;
   }
   (*dlt) = .1*(*dlt);
   goto xf2c_stmt_160;
   xf2c_stmt_155: ;
   (*dlt) = dltmp;
   xf2c_stmt_160: ;
   goto xf2c_stmt_230;
   xf2c_stmt_170: ;
   dltfp = 0.0;
   if (method == 3) {
      goto xf2c_stmt_180;
   }
   i = 1;
   while (i <= n) {
      temp = ({ double red = 0.0; for (int i_red = 0; i_red < ((((n - i) / 1 + 1))); ++i_red) red += (a[i + i_red - 1 + n_a_1 * (i - 1)]) * (sc[i + i_red - 1]); red; });
      dltfp += temp*temp;
      i += 1;
   }
   goto xf2c_stmt_190;
   xf2c_stmt_180: ;
   i = 1;
   while (i <= n) {
      dltfp += udiag[i - 1]*sc[i - 1]*sc[i - 1];
      if (i == n) {
         goto xf2c_loop_3_continue;
      }
      temp = 0;
      ip1 = i + 1;
      while (ip1 <= n) {
         temp += a[i - 1 + n_a_1 * (ip1 - 1)]*sc[i - 1]*sc[ip1 - 1];
         ip1 += 1;
      }
      dltfp += 2.0*temp;
      xf2c_loop_3_continue: ;
      i += 1;
   }
   xf2c_stmt_190: ;
   dltfp = slp + dltfp/2.0;
   if ((*iretcd) == 2 || ((fabs(dltfp - dltf)) > .1*(fabs(dltf)))     || nwtake || ((*dlt) > .99*stepmx)) goto xf2c_stmt_210;
   (*iretcd) = 3;
   if (1 > 0) {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
         xplsp[i_fill - 1] = xpls[p_fill];
      }
   } else {
      for (int i_fill = 1, p_fill = 0; p_fill < ((((n - 1) / 1 + 1))); i_fill += 1, ++p_fill) {
         xplsp[i_fill - 1] = xpls[p_fill];
      }
   }
   (*fplsp) = (*fpls);
   (*dlt) = fmin(2.0e0*(*dlt),stepmx);
   goto xf2c_stmt_230;
   xf2c_stmt_210: ;
   (*iretcd) = 0;
   if ((*dlt) > .99*stepmx) {
      (*mxtake) = 1;
   }
   if (dltf < .1*dltfp) {
      goto xf2c_stmt_220;
   }
   (*dlt) = .5*(*dlt);
   goto xf2c_stmt_230;
   xf2c_stmt_220: ;
   if (dltf <= .75*dltfp) (*dlt) = fmin(2.*(*dlt),stepmx);
   xf2c_stmt_230: ;
   return;
}

void fcn(const int n, const int n_x, const double *x, double *f) {
   /* n_x: extent of x (dimension 1) */
   const double one = 1.0;
   if (n != 2) {
      exit(0);
   }
   (*f) = 100.0 * (x[1] - x[0] * x[0]) * (x[1] - x[0] * x[0]) + (1.0 - x[0]) * (1.0 - x[0]);
   return;
}

void d1fcn(const int n, const int n_x, const double *x, const int n_g, double *g) {
   /* n_x: extent of x (dimension 1) */
   /* n_g: extent of g (dimension 1) */
   const double one = 1.0;
   if (n != 2) {
      exit(0);
   }
   g[0] = -(400.0) * (x[1] - x[0] * x[0]) * x[0] - 2.0 * (1.0 - x[0]);
   g[1] = 200.0 * (x[1] - x[0] * x[0]);
   return;
}

void d2fcn(const int nr, const int n, const int n_x, const double *x, const int n_h_1, const int n_h_2, double *h) {
   /* n_x: extent of x (dimension 1) */
   /* n_h_1: extent of h (dimension 1) */
   /* n_h_2: extent of h (dimension 2) */
   if (nr != 2) {
      exit(0);
   }
   if (n != 2) {
      exit(0);
   }
   h[0] = -(400.0) * (x[1] - 3.0 * x[0] * x[0]) + 2.0;
   h[n_h_1] = -(400.0) * x[0];
   h[1] = -(400.0) * x[0];
   h[n_h_1 + 1] = 200.0;
   return;
}

int main(void) {
   /* Test the unconstrained minimization package UNCMIN */
   double *x = NULL, *typsiz = NULL, *xpls = NULL, *gpls = NULL;
   double fscale, dlt, gradtl, stepmx, steptl, fpls;
   int nr, n, m, iexp, msg, ndigit, itnlim, iagflg, iahflg, itrmcd;
   const double zero = 0.0, one = 1.0;
   x = (double*) malloc(sizeof(double) * 2);
   if (!x) return 1;
   typsiz = (double*) malloc(sizeof(double) * 2);
   if (!typsiz) return 1;
   xpls = (double*) malloc(sizeof(double) * 2);
   if (!xpls) return 1;
   gpls = (double*) malloc(sizeof(double) * 2);
   if (!gpls) return 1;
   /* unsupported: INTERFACE */
   /* unsupported: SUBROUTINE fcn(n, x, f) */
   /* unsupported: END SUBROUTINE fcn */
   /* unsupported: SUBROUTINE d1fcn(n, x, g) */
   /* unsupported: END SUBROUTINE d1fcn */
   /* unsupported: SUBROUTINE d2fcn(nr, n, x, h) */
   /* unsupported: END SUBROUTINE d2fcn */
   /* unsupported: END INTERFACE */
   m = 1;
   while (m <= 3) {
      nr = 2;
      n = 2;
      x[0] = 0.0;
      x[1] = 0.0;
      for (int i_fill = 0; i_fill < 2; ++i_fill) {
         typsiz[i_fill] = 1.0;
      }
      fscale = 10.0;
      iexp = 0;
      msg = 0;
      ndigit = 12;
      itnlim = 500;
      iagflg = 1;
      iahflg = 1;
      dlt = 1.0;
      gradtl = 0.0001;
      stepmx = 1.0;
      steptl = 0.0001;
      printf("%s%12d\n", "METHOD:", m);
      optdrv(nr, n, 2, x, fcn, d1fcn, d2fcn, 2, typsiz, &fscale, &m, &iexp, &msg, &ndigit, &itnlim, &iagflg, &iahflg, &dlt, gradtl, &stepmx, steptl, 2, xpls, &fpls, 2, gpls, &itrmcd);
      printf("%s%12d\n", "ITRMCD =", itrmcd);
      printf("%s%12d\n", "MSG    =", msg);
      printf("%s", " Final X: ");
      for (int idx_arr = 0; idx_arr < 2; ) {
         if (idx_arr < 2) printf("%12.8f", xpls[idx_arr]);
         ++idx_arr;
      }
      printf("\n");
      printf("%s", " Function value: ");
      printf("%13.5g", fpls);
      printf("\n");
      printf("%s", " Gradients: ");
      for (int idx_arr = 0; idx_arr < 2; ) {
         if (idx_arr < 2) printf("%13.5g", gpls[idx_arr]);
         ++idx_arr;
      }
      printf("\n");
      printf("\n");
      xf2c_loop_1_continue: ;
      m += 1;
   }
   xf2c_loop_1_break: ;
   return 0;
   free(x);
   free(typsiz);
   free(xpls);
   free(gpls);
   return 0;
}
