/* Generated by xf2c.py from xvec_sub.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   float x[2] = {10.0, 20.0};
   {
      int first = 1;
      printf("%s%g", first ? "" : " ", x[0]);
      first = 0;
      printf("%s%g", first ? "" : " ", x[1]);
      first = 0;
      printf("%s%g", first ? "" : " ", x[0]);
      first = 0;
      printf("\n");
   }
   return 0;
}
