/* Generated by xf2c.py from xwrite.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   printf("%3d", 3);
   printf("%3d", 4);
   printf("%6.2f", 3.0);
   printf("%6.2f", 4.0);
   printf("%3d", 10);
   printf("%3d", 20);
   printf("\n");
   return 0;
}
