/* Generated by xf2c.py from xwrite_rename.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   printf(" %s\n", "hi");
   return 0;
}
