/* Generated by xf2c.py from xxchar.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"

int main(void) {
   const char *newl = achar_s(10);
   const char *lower_case = "abcdefghijklmnopqrstuvwxyz", *upper_case = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
   const char *newline = achar_s(10);
   const char *bad_char = "???";
   {
      int first = 1;
      printf("%s%s", first ? "" : " ", "abc");
      first = 0;
      printf("%s%s", first ? "" : "", newl);
      first = 0;
      printf("%s%s", first ? "" : "", lower_case);
      first = 0;
      printf("%s%s", first ? "" : "", newline);
      first = 0;
      printf("%s%s", first ? "" : "", upper_case);
      first = 0;
      printf("\n");
   }
   return 0;
}
