/* Generated by xf2c.py from xxprimes.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   int i, j, is_prime;
   enum { n = 100 };
   i = 2;
   while (i <= 100) {
      is_prime = 1;
      j = 2;
      while (j <= (((int) ((sqrtf(((float) i))))))) {
         if (((i % j)) == 0) {
            is_prime = 0;
            goto xf2c_loop_2_break;
         }
         j += 1;
      }
      xf2c_loop_2_break: ;
      if (is_prime) {
         {
            int first = 1;
            printf("%s%d", first ? "" : " ", i);
            first = 0;
            printf("\n");
         }
      }
      i += 1;
   }
   return 0;
}
