/* Generated by xf2c.py from xxprint.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

int main(void) {
   printf("%s", "z");
   printf("\n");
   return 0;
}
