/* Generated by xf2c.py from xzero_size.f90 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <complex.h>
#include <float.h>
#include <limits.h>
#include <string.h>

#include "fortran_runtime.h"

int main(void) {
   const float r0[1] = {0};
   {
      int first = 1;
      printf("%s%d", first ? "" : " ", 0);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%d", first ? "" : " ", 0);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%d", first ? "" : " ", 1);
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", sum_1d_float(0, r0));
      first = 0;
      printf("\n");
   }
   {
      int first = 1;
      printf("%s%13.6f", first ? "" : " ", product_1d_float(0, r0));
      first = 0;
      printf("\n");
   }
   return 0;
}
